# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ...node import ShaderNode


class ShaderNodeCompiled_Simple_Pantyhose_Type_1(ShaderNode):
    bl_label = 'lscherry.utils.procedural.Procedural.Simple Pantyhose Type 1'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['UV'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Combined'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Color'].default_value = (0.5, 0.5, 0.5, 1.0)
        self.inputs['Factor'].default_value = 1.0
        self.inputs['Scale'].default_value = 50.0

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'COLOR'

        _sock_out_Combined = nt.interface.new_socket(name='Combined', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Combined.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_out_Pattern = nt.interface.new_socket(name='Pattern', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Pattern.default_value = 0.0
        _sock_out_Pattern.min_value = -3.4028234663852886e+38
        _sock_out_Pattern.max_value = 3.4028234663852886e+38
        _sock_out_Pattern.hide_value = True
        _sock_inp_UV = nt.interface.new_socket(name='UV', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_UV.default_value = (0.0, 0.0, 0.0)
        _sock_inp_UV.min_value = -3.4028234663852886e+38
        _sock_inp_UV.max_value = 3.4028234663852886e+38
        _sock_inp_UV.hide_value = True
        _sock_inp_UV.dimensions = 3
        _sock_inp_Combined = nt.interface.new_socket(name='Combined', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Combined.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Combined.hide_value = True
        _sock_inp_Color = nt.interface.new_socket(name='Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Color.default_value = (0.5, 0.5, 0.5, 1.0)
        _sock_inp_Factor = nt.interface.new_socket(name='Factor', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Factor.default_value = 1.0
        _sock_inp_Factor.min_value = 0.0
        _sock_inp_Factor.max_value = 1.0
        _sock_inp_Factor.subtype = 'FACTOR'
        _sock_inp_Scale = nt.interface.new_socket(name='Scale', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Scale.default_value = 50.0
        _sock_inp_Scale.min_value = 0.0
        _sock_inp_Scale.max_value = 1000.0

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1597.96, 370.55)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-571.8, 2.38)

        Brick_Texture = nt.nodes.new('ShaderNodeTexBrick')
        Brick_Texture.location = (0.9, 217.58)
        Brick_Texture.width = 150.0
        Brick_Texture.offset = 0.0
        Brick_Texture.offset_frequency = 2
        Brick_Texture.squash = 1.0
        Brick_Texture.squash_frequency = 2
        Brick_Texture.inputs[1].default_value = (1.0, 1.0, 1.0, 1.0)
        Brick_Texture.inputs[2].default_value = (1.0, 1.0, 1.0, 1.0)
        Brick_Texture.inputs[3].default_value = (0.0, 0.0, 0.0, 1.0)
        Brick_Texture.inputs[5].default_value = 0.10000000149011612
        Brick_Texture.inputs[6].default_value = 1.0
        Brick_Texture.inputs[7].default_value = 0.0
        Brick_Texture.inputs[8].default_value = 0.30000001192092896
        Brick_Texture.inputs[9].default_value = 0.10000000149011612

        Invert_Color = nt.nodes.new('ShaderNodeInvert')
        Invert_Color.location = (230.47, 70.99)
        Invert_Color.inputs[0].default_value = 1.0

        Invert_Color_001 = nt.nodes.new('ShaderNodeInvert')
        Invert_Color_001.location = (230.47, -119.01)
        Invert_Color_001.inputs[0].default_value = 0.0

        Mapping = nt.nodes.new('ShaderNodeMapping')
        Mapping.location = (-215.35, 145.64)
        Mapping.vector_type = 'POINT'
        Mapping.inputs[1].default_value = (0.0, 0.0, 0.0)
        Mapping.inputs[2].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mapping.inputs[3].default_value = (1.0, 1.0, 1.0)

        Geometry = nt.nodes.new('ShaderNodeNewGeometry')
        Geometry.location = (-234.95, -182.9)

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (-239.86, -262.22)
        Math.operation = 'MULTIPLY'
        Math.use_clamp = False
        Math.inputs[1].default_value = 3.0
        Math.inputs[2].default_value = 0.5

        Voronoi_Texture = nt.nodes.new('ShaderNodeTexVoronoi')
        Voronoi_Texture.location = (0.82, -169.97)
        Voronoi_Texture.distance = 'EUCLIDEAN'
        Voronoi_Texture.feature = 'DISTANCE_TO_EDGE'
        Voronoi_Texture.voronoi_dimensions = '3D'
        Voronoi_Texture.inputs[1].default_value = 0.0
        Voronoi_Texture.inputs[3].default_value = 0.0
        Voronoi_Texture.inputs[4].default_value = 0.5
        Voronoi_Texture.inputs[5].default_value = 2.0
        Voronoi_Texture.inputs[6].default_value = 1.0
        Voronoi_Texture.inputs[7].default_value = 0.5
        Voronoi_Texture.inputs[8].default_value = 0.0

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (450.95, 96.89)
        Mix.data_type = 'RGBA'
        Mix.blend_type = 'SUBTRACT'
        Mix.clamp_result = False
        Mix.clamp_factor = True
        Mix.factor_mode = 'UNIFORM'
        Mix.inputs[0].default_value = 1.0
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Mix_001 = nt.nodes.new('ShaderNodeMix')
        Mix_001.location = (1267.34, 581.93)
        Mix_001.data_type = 'RGBA'
        Mix_001.blend_type = 'MULTIPLY'
        Mix_001.clamp_result = False
        Mix_001.clamp_factor = True
        Mix_001.factor_mode = 'UNIFORM'
        Mix_001.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_001.inputs[2].default_value = 0.0
        Mix_001.inputs[3].default_value = 0.0
        Mix_001.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix_001.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Mix_002 = nt.nodes.new('ShaderNodeMix')
        Mix_002.location = (1081.68, 391.4)
        Mix_002.data_type = 'RGBA'
        Mix_002.blend_type = 'MULTIPLY'
        Mix_002.clamp_result = False
        Mix_002.clamp_factor = True
        Mix_002.factor_mode = 'UNIFORM'
        Mix_002.inputs[0].default_value = 1.0
        Mix_002.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_002.inputs[2].default_value = 0.0
        Mix_002.inputs[3].default_value = 0.0
        Mix_002.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix_002.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Color_Ramp = nt.nodes.new('ShaderNodeValToRGB')
        Color_Ramp.location = (656.12, 154.59)
        Color_Ramp.width = 240.0

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (668.2, 564.77)


        nt.links.new(Mix_001.outputs['Result'], Group_Output.inputs['Combined'])
        nt.links.new(Color_Ramp.outputs['Color'], Group_Output.inputs['Pattern'])
        nt.links.new(Mapping.outputs['Vector'], Brick_Texture.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Scale'], Brick_Texture.inputs['Scale'])
        nt.links.new(Brick_Texture.outputs['Factor'], Invert_Color.inputs['Color'])
        nt.links.new(Voronoi_Texture.outputs['Distance'], Invert_Color_001.inputs['Color'])
        nt.links.new(Group_Input.outputs['UV'], Mapping.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Scale'], Math.inputs['Value'])
        nt.links.new(Geometry.outputs['Incoming'], Voronoi_Texture.inputs['Vector'])
        nt.links.new(Math.outputs['Value'], Voronoi_Texture.inputs['Scale'])
        nt.links.new(Invert_Color.outputs['Color'], Mix.inputs['A'])
        nt.links.new(Invert_Color_001.outputs['Color'], Mix.inputs['B'])
        nt.links.new(Group_Input_001.outputs['Factor'], Mix_001.inputs['Factor'])
        nt.links.new(Group_Input_001.outputs['Combined'], Mix_001.inputs['A'])
        nt.links.new(Mix_002.outputs['Result'], Mix_001.inputs['B'])
        nt.links.new(Color_Ramp.outputs['Color'], Mix_002.inputs['A'])
        nt.links.new(Group_Input_001.outputs['Color'], Mix_002.inputs['B'])
        nt.links.new(Mix.outputs['Result'], Color_Ramp.inputs['Factor'])
