# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# ============================================================


from .add_core_specular import *
from .add_frequent_hair_highlight import *
from .add_highlight import *
from .add_hightlight_from_lightmap import *
from .add_hightlight_from_spheremap import *
from .add_invert_tint_v_body import *
from .add_random_toon_highlight import *
from .add_tint_v_body import *
from .add_toon_highlight import *
from .disable_all_shader import *
from .random_color import *
