# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ...node import ShaderNode


class ShaderNodeCompiled_Blend_Color(ShaderNode):
    bl_label = 'lscherry.combiner.Combiner.Blend Color'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Mix'].default_value = 1.0
        self.inputs['Base Color'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Outer Color'].default_value = (1.0, 1.0, 1.0, 1.0)

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'CONVERTER'

        _sock_out_Blend_Color = nt.interface.new_socket(name='Blend Color', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Blend_Color.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_out_Blend_Color.hide_value = True
        _sock_inp_Mix = nt.interface.new_socket(name='Mix', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Mix.default_value = 1.0
        _sock_inp_Mix.min_value = 0.0
        _sock_inp_Mix.max_value = 1.0
        _sock_inp_Mix.subtype = 'FACTOR'
        _sock_inp_Base_Color = nt.interface.new_socket(name='Base Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Base_Color.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Outer_Color = nt.interface.new_socket(name='Outer Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Outer_Color.default_value = (1.0, 1.0, 1.0, 1.0)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (770.76, 317.99)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-550.53, 257.16)

        Separate_Color = nt.nodes.new('ShaderNodeSeparateColor')
        Separate_Color.location = (-307.21, 71.15)

        Combine_Color = nt.nodes.new('ShaderNodeCombineColor')
        Combine_Color.location = (314.9, 57.46)

        Separate_Color_001 = nt.nodes.new('ShaderNodeSeparateColor')
        Separate_Color_001.location = (-307.21, -98.39)

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (-104.34, 158.22)
        Math.operation = 'ADD'
        Math.use_clamp = False
        Math.inputs[2].default_value = 0.5

        Math_001 = nt.nodes.new('ShaderNodeMath')
        Math_001.location = (-104.34, 2.9)
        Math_001.operation = 'ADD'
        Math_001.use_clamp = False
        Math_001.inputs[2].default_value = 0.5

        Math_002 = nt.nodes.new('ShaderNodeMath')
        Math_002.location = (-104.34, -158.22)
        Math_002.operation = 'ADD'
        Math_002.use_clamp = False
        Math_002.inputs[2].default_value = 0.5

        Math_003 = nt.nodes.new('ShaderNodeMath')
        Math_003.location = (96.61, 158.22)
        Math_003.operation = 'DIVIDE'
        Math_003.use_clamp = False
        Math_003.inputs[1].default_value = 2.0
        Math_003.inputs[2].default_value = 0.5

        Math_004 = nt.nodes.new('ShaderNodeMath')
        Math_004.location = (96.61, 2.37)
        Math_004.operation = 'DIVIDE'
        Math_004.use_clamp = False
        Math_004.inputs[1].default_value = 2.0
        Math_004.inputs[2].default_value = 0.5

        Math_005 = nt.nodes.new('ShaderNodeMath')
        Math_005.location = (96.61, -152.43)
        Math_005.operation = 'DIVIDE'
        Math_005.use_clamp = False
        Math_005.inputs[1].default_value = 2.0
        Math_005.inputs[2].default_value = 0.5

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (521.65, 332.63)
        Mix.data_type = 'RGBA'
        Mix.blend_type = 'MIX'
        Mix.clamp_result = False
        Mix.clamp_factor = True
        Mix.factor_mode = 'UNIFORM'
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (295.2, 299.82)


        nt.links.new(Mix.outputs['Result'], Group_Output.inputs['Blend Color'])
        nt.links.new(Group_Input.outputs['Base Color'], Separate_Color.inputs['Color'])
        nt.links.new(Math_003.outputs['Value'], Combine_Color.inputs['Red'])
        nt.links.new(Math_004.outputs['Value'], Combine_Color.inputs['Green'])
        nt.links.new(Math_005.outputs['Value'], Combine_Color.inputs['Blue'])
        nt.links.new(Group_Input.outputs['Outer Color'], Separate_Color_001.inputs['Color'])
        nt.links.new(Separate_Color.outputs['Red'], Math.inputs['Value'])
        nt.links.new(Separate_Color_001.outputs['Red'], Math.inputs['Value'])
        nt.links.new(Separate_Color.outputs['Green'], Math_001.inputs['Value'])
        nt.links.new(Separate_Color_001.outputs['Green'], Math_001.inputs['Value'])
        nt.links.new(Separate_Color.outputs['Blue'], Math_002.inputs['Value'])
        nt.links.new(Separate_Color_001.outputs['Blue'], Math_002.inputs['Value'])
        nt.links.new(Math.outputs['Value'], Math_003.inputs['Value'])
        nt.links.new(Math_001.outputs['Value'], Math_004.inputs['Value'])
        nt.links.new(Math_002.outputs['Value'], Math_005.inputs['Value'])
        nt.links.new(Group_Input_001.outputs['Mix'], Mix.inputs['Factor'])
        nt.links.new(Group_Input.outputs['Base Color'], Mix.inputs['A'])
        nt.links.new(Combine_Color.outputs['Color'], Mix.inputs['B'])
