# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from .....node import ShaderNode


class ShaderNodeCompiled_Build_Face_Ramp(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Build_Face_Ramp'
    bl_label = 'lscherry.utils.procedural.Build Face Ramp'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Face Value'].default_value = 0.5
        self.inputs['Face Map'].default_value = 0.5

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'CONVERTER'

        _sock_out_Custom_Ramp = nt.interface.new_socket(name='Custom Ramp', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Custom_Ramp.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_out_Custom_Ramp.hide_value = True
        _sock_inp_Face_Value = nt.interface.new_socket(name='Face Value', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Face_Value.default_value = 0.5
        _sock_inp_Face_Value.min_value = -10000.0
        _sock_inp_Face_Value.max_value = 10000.0
        _sock_inp_Face_Value.hide_value = True
        _sock_inp_Face_Map = nt.interface.new_socket(name='Face Map', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Face_Map.default_value = 0.5
        _sock_inp_Face_Map.min_value = -10000.0
        _sock_inp_Face_Map.max_value = 10000.0
        _sock_inp_Face_Map.hide_value = True

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (229.33, 59.68)
        Math.operation = 'GREATER_THAN'
        Math.use_clamp = False
        Math.inputs[2].default_value = 0.5

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1624.71, 14.53)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (6.52, -12.79)


        nt.links.new(Group_Input.outputs['Face Map'], Math.inputs['Value'])
        nt.links.new(Group_Input.outputs['Face Value'], Math.inputs['Value'])
        nt.links.new(Math.outputs['Value'], Group_Output.inputs['Custom Ramp'])
