# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from .....node import ShaderNode


class ShaderNodeCompiled_Mix_Transparent_VFX(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Mix_Transparent_VFX'
    bl_label = 'lscherry.utils.procedural.Mix Transparent VFX'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Mix Transparent VFX'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Fac'].default_value = 2.9802322387695312e-08

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'SHADER'

        _sock_out_Mask = nt.interface.new_socket(name='Mask', in_out='OUTPUT', socket_type='NodeSocketShader')
        _sock_inp_Fac = nt.interface.new_socket(name='Fac', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Fac.default_value = 2.9802322387695312e-08
        _sock_inp_Fac.min_value = 0.0
        _sock_inp_Fac.max_value = 1.0
        _sock_inp_Fac.subtype = 'FACTOR'
        _sock_inp_Shader = nt.interface.new_socket(name='Shader', in_out='INPUT', socket_type='NodeSocketShader')

        Fresnel = nt.nodes.new('ShaderNodeFresnel')
        Fresnel.location = (-138.72, -70.05)
        Fresnel.inputs[0].default_value = 0.9500001668930054
        Fresnel.inputs[1].default_value = (0.0, 0.0, 0.0)

        Transparent_BSDF = nt.nodes.new('ShaderNodeBsdfTransparent')
        Transparent_BSDF.location = (180.15, 217.36)
        Transparent_BSDF.inputs[0].default_value = (1.0, 1.0, 1.0, 1.0)
        Transparent_BSDF.inputs[1].default_value = 0.0

        Mix_Shader_001 = nt.nodes.new('ShaderNodeMixShader')
        Mix_Shader_001.location = (720.47, 181.57)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (933.08, 158.39)
        Group_Output.width = 155.69
        Group_Output.is_active_output = True

        Mix_Shader = nt.nodes.new('ShaderNodeMixShader')
        Mix_Shader.location = (556.09, 86.75)

        Emission = nt.nodes.new('ShaderNodeEmission')
        Emission.location = (403.24, -57.5)
        Emission.inputs[0].default_value = (0.8611106276512146, 0.8611106276512146, 0.8611106276512146, 1.0)
        Emission.inputs[1].default_value = 1.0
        Emission.inputs[2].default_value = 0.0

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-313.89, 123.09)

        ColorRamp = nt.nodes.new('ShaderNodeValToRGB')
        ColorRamp.location = (75.56, 50.88)
        ColorRamp.width = 240.0
        _cr = ColorRamp.color_ramp
        _cr.color_mode = 'RGB'
        _cr.interpolation = 'LINEAR'
        _cr.hue_interpolation = 'NEAR'
        while len(_cr.elements) > 1:
            _cr.elements.remove(_cr.elements[-1])
        _cr.elements[0].position = 0.07727271318435669
        _cr.elements[0].color = (0.017052238807082176, 0.017052238807082176, 0.017052238807082176, 1.0)
        _e = _cr.elements.new(0.5272728800773621)
        _e.color = (0.4075973629951477, 0.4075973629951477, 0.4075973629951477, 1.0)
        _e = _cr.elements.new(0.8999999761581421)
        _e.color = (0.7026252150535583, 0.7026252150535583, 0.7026252150535583, 1.0)


        nt.links.new(Group_Input.outputs['Fac'], Mix_Shader_001.inputs['Factor'])
        nt.links.new(Mix_Shader.outputs['Shader'], Mix_Shader_001.inputs[1])
        nt.links.new(Group_Input.outputs['Shader'], Mix_Shader_001.inputs[2])
        nt.links.new(Mix_Shader_001.outputs['Shader'], Group_Output.inputs['Mask'])
        nt.links.new(ColorRamp.outputs['Color'], Mix_Shader.inputs['Factor'])
        nt.links.new(Transparent_BSDF.outputs['BSDF'], Mix_Shader.inputs[1])
        nt.links.new(Emission.outputs['Emission'], Mix_Shader.inputs[2])
        nt.links.new(Fresnel.outputs['Factor'], ColorRamp.inputs['Factor'])
