# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from .....node import ShaderNode


class ShaderNodeCompiled_SST1__Moles(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_SST1__Moles'
    bl_label = 'lscherry.utils.procedural.SST1: Moles'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'SST1: Moles'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Builder'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Red Color'].default_value = (0.800000011920929, 0.35005807876586914, 0.20150570571422577, 1.0)
        self.inputs['Scale'].default_value = 75.0
        self.inputs['Threadhold'].default_value = 0
        self.inputs['UV'].default_value = (0.0, 0.0, 0.0)

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'CONVERTER'

        _sock_out_Builder = nt.interface.new_socket(name='Builder', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Builder.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_out_UV = nt.interface.new_socket(name='UV', in_out='OUTPUT', socket_type='NodeSocketVector')
        _sock_out_UV.default_value = (0.0, 0.0, 0.0)
        _sock_out_UV.min_value = -3.4028234663852886e+38
        _sock_out_UV.max_value = 3.4028234663852886e+38
        _sock_out_UV.hide_value = True
        _sock_out_UV.dimensions = 3
        _sock_inp_Builder = nt.interface.new_socket(name='Builder', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Builder.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Builder.hide_value = True
        _sock_inp_Red_Color = nt.interface.new_socket(name='Red Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Red_Color.default_value = (0.800000011920929, 0.35005807876586914, 0.20150570571422577, 1.0)
        _sock_inp_Scale = nt.interface.new_socket(name='Scale', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Scale.default_value = 75.0
        _sock_inp_Scale.min_value = 0.0
        _sock_inp_Scale.max_value = 1000.0999755859375
        _sock_inp_Threadhold = nt.interface.new_socket(name='Threadhold', in_out='INPUT', socket_type='NodeSocketInt')
        _sock_inp_Threadhold.default_value = 0
        _sock_inp_Threadhold.min_value = 0
        _sock_inp_Threadhold.max_value = 1000
        _sock_inp_UV = nt.interface.new_socket(name='UV', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_UV.default_value = (0.0, 0.0, 0.0)
        _sock_inp_UV.min_value = -3.4028234663852886e+38
        _sock_inp_UV.max_value = 3.4028234663852886e+38
        _sock_inp_UV.hide_value = True
        _sock_inp_UV.dimensions = 3

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (838.15, 75.12)

        Voronoi_Texture = nt.nodes.new('ShaderNodeTexVoronoi')
        Voronoi_Texture.location = (-787.48, 299.27)
        Voronoi_Texture.distance = 'EUCLIDEAN'
        Voronoi_Texture.feature = 'F1'
        Voronoi_Texture.voronoi_dimensions = '3D'
        Voronoi_Texture.inputs[1].default_value = 0.0
        Voronoi_Texture.inputs[3].default_value = 0.0
        Voronoi_Texture.inputs[4].default_value = 0.5
        Voronoi_Texture.inputs[5].default_value = 2.0
        Voronoi_Texture.inputs[6].default_value = 1.0
        Voronoi_Texture.inputs[7].default_value = 0.5
        Voronoi_Texture.inputs[8].default_value = 1.0

        Voronoi_Texture_001 = nt.nodes.new('ShaderNodeTexVoronoi')
        Voronoi_Texture_001.location = (-792.29, 670.42)
        Voronoi_Texture_001.distance = 'EUCLIDEAN'
        Voronoi_Texture_001.feature = 'F1'
        Voronoi_Texture_001.voronoi_dimensions = '3D'
        Voronoi_Texture_001.inputs[1].default_value = 0.0
        Voronoi_Texture_001.inputs[3].default_value = 0.0
        Voronoi_Texture_001.inputs[4].default_value = 0.5
        Voronoi_Texture_001.inputs[5].default_value = 2.0
        Voronoi_Texture_001.inputs[6].default_value = 1.0
        Voronoi_Texture_001.inputs[7].default_value = 0.5
        Voronoi_Texture_001.inputs[8].default_value = 1.0

        ColorRamp_001 = nt.nodes.new('ShaderNodeValToRGB')
        ColorRamp_001.location = (-613.23, 609.36)
        ColorRamp_001.width = 240.0

        Mapping = nt.nodes.new('ShaderNodeMapping')
        Mapping.location = (-967.48, 259.27)
        Mapping.hide = True
        Mapping.vector_type = 'POINT'
        Mapping.inputs[1].default_value = (0.7999999523162842, 0.0, 0.0)
        Mapping.inputs[2].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mapping.inputs[3].default_value = (1.5, 1.0, 1.0)

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (-271.35, 397.84)
        Mix.data_type = 'RGBA'
        Mix.blend_type = 'MULTIPLY'
        Mix.clamp_result = False
        Mix.clamp_factor = True
        Mix.factor_mode = 'UNIFORM'
        Mix.inputs[0].default_value = 1.0
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Mapping_001 = nt.nodes.new('ShaderNodeMapping')
        Mapping_001.location = (-972.29, 630.42)
        Mapping_001.hide = True
        Mapping_001.vector_type = 'POINT'
        Mapping_001.inputs[1].default_value = (0.0, 0.0, 0.0)
        Mapping_001.inputs[2].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mapping_001.inputs[3].default_value = (1.2000000476837158, 1.8000000715255737, 1.2000000476837158)

        Mapping_002 = nt.nodes.new('ShaderNodeMapping')
        Mapping_002.location = (-958.64, 751.02)
        Mapping_002.hide = True
        Mapping_002.vector_type = 'POINT'
        Mapping_002.inputs[1].default_value = (0.09999999403953552, 0.0, 0.0)
        Mapping_002.inputs[2].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mapping_002.inputs[3].default_value = (1.0, 1.0, 1.0)

        Noise_Texture = nt.nodes.new('ShaderNodeTexNoise')
        Noise_Texture.location = (-453.08, 1043.51)
        Noise_Texture.noise_dimensions = '3D'
        Noise_Texture.inputs[1].default_value = 0.0
        Noise_Texture.inputs[3].default_value = 2.0
        Noise_Texture.inputs[4].default_value = 0.5
        Noise_Texture.inputs[5].default_value = 2.0
        Noise_Texture.inputs[6].default_value = 0.0
        Noise_Texture.inputs[7].default_value = 1.0
        Noise_Texture.inputs[8].default_value = 0.0

        ColorRamp = nt.nodes.new('ShaderNodeValToRGB')
        ColorRamp.location = (-587.33, 272.91)
        ColorRamp.width = 240.0

        Mix_001 = nt.nodes.new('ShaderNodeMix')
        Mix_001.location = (561.31, 11.55)
        Mix_001.data_type = 'RGBA'
        Mix_001.blend_type = 'MULTIPLY'
        Mix_001.clamp_result = False
        Mix_001.clamp_factor = True
        Mix_001.factor_mode = 'UNIFORM'
        Mix_001.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_001.inputs[3].default_value = 0.0
        Mix_001.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix_001.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-1490.28, 234.9)

        Invert = nt.nodes.new('ShaderNodeInvert')
        Invert.location = (-24.34, 139.37)
        Invert.inputs[0].default_value = 1.0

        Mix_002 = nt.nodes.new('ShaderNodeMix')
        Mix_002.location = (294.1, 221.12)
        Mix_002.data_type = 'RGBA'
        Mix_002.blend_type = 'MIX'
        Mix_002.clamp_result = False
        Mix_002.clamp_factor = True
        Mix_002.factor_mode = 'UNIFORM'
        Mix_002.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_002.inputs[2].default_value = 0.0
        Mix_002.inputs[3].default_value = 0.0
        Mix_002.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[6].default_value = (0.0, 0.0, 0.0, 1.0)
        Mix_002.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix_002.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        ColorRamp_002 = nt.nodes.new('ShaderNodeValToRGB')
        ColorRamp_002.location = (-210.73, 999.43)
        ColorRamp_002.width = 240.0

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (90.96, 643.02)
        Math.operation = 'ADD'
        Math.use_clamp = False
        Math.inputs[2].default_value = 0.5

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (-670.09, 760.68)

        Group_Input_002 = nt.nodes.new('NodeGroupInput')
        Group_Input_002.location = (278.7, -152.37)


        nt.links.new(Mix_001.outputs['Result'], Group_Output.inputs['Builder'])
        nt.links.new(Group_Input.outputs['UV'], Group_Output.inputs['UV'])
        nt.links.new(Mapping.outputs['Vector'], Voronoi_Texture.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Scale'], Voronoi_Texture.inputs['Scale'])
        nt.links.new(Mapping_001.outputs['Vector'], Voronoi_Texture_001.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Scale'], Voronoi_Texture_001.inputs['Scale'])
        nt.links.new(Voronoi_Texture_001.outputs['Distance'], ColorRamp_001.inputs['Factor'])
        nt.links.new(Group_Input.outputs['UV'], Mapping.inputs['Vector'])
        nt.links.new(ColorRamp_001.outputs['Color'], Mix.inputs['A'])
        nt.links.new(ColorRamp.outputs['Color'], Mix.inputs['B'])
        nt.links.new(ColorRamp_001.outputs['Color'], Mix.inputs['A'])
        nt.links.new(ColorRamp.outputs['Color'], Mix.inputs['B'])
        nt.links.new(Group_Input.outputs['UV'], Mapping_001.inputs['Vector'])
        nt.links.new(Group_Input.outputs['UV'], Mapping_002.inputs['Vector'])
        nt.links.new(Mapping_002.outputs['Vector'], Noise_Texture.inputs['Vector'])
        nt.links.new(Group_Input_001.outputs['Threadhold'], Noise_Texture.inputs['Scale'])
        nt.links.new(Voronoi_Texture.outputs['Distance'], ColorRamp.inputs['Factor'])
        nt.links.new(Mix_002.outputs['Result'], Mix_001.inputs['Factor'])
        nt.links.new(Mix.outputs['Result'], Mix_001.inputs['A'])
        nt.links.new(Group_Input_002.outputs['Builder'], Mix_001.inputs['A'])
        nt.links.new(Group_Input_002.outputs['Red Color'], Mix_001.inputs['B'])
        nt.links.new(Mix.outputs['Result'], Invert.inputs['Color'])
        nt.links.new(ColorRamp_002.outputs['Color'], Mix_002.inputs['Factor'])
        nt.links.new(Invert.outputs['Color'], Mix_002.inputs['B'])
        nt.links.new(Noise_Texture.outputs['Color'], ColorRamp_002.inputs['Factor'])
        nt.links.new(ColorRamp_002.outputs['Color'], Math.inputs['Value'])
        nt.links.new(Group_Input_001.outputs['Threadhold'], Math.inputs['Value'])
