# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from .....node import ShaderNode


class ShaderNodeCompiled_SST1__Veins(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_SST1__Veins'
    bl_label = 'lscherry.utils.procedural.SST1: Veins'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'SST1: Veins'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Builder'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Blue Color'].default_value = (0.35572776198387146, 0.082790806889534, 0.800000011920929, 1.0)
        self.inputs['Scale'].default_value = 1.0
        self.inputs['Mask Scale'].default_value = 7.0
        self.inputs['Strength'].default_value = 1.0
        self.inputs['UV'].default_value = (0.0, 0.0, 0.0)

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'CONVERTER'

        _sock_out_Builder = nt.interface.new_socket(name='Builder', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Builder.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_out_UV = nt.interface.new_socket(name='UV', in_out='OUTPUT', socket_type='NodeSocketVector')
        _sock_out_UV.default_value = (0.0, 0.0, 0.0)
        _sock_out_UV.min_value = -3.4028234663852886e+38
        _sock_out_UV.max_value = 3.4028234663852886e+38
        _sock_out_UV.hide_value = True
        _sock_out_UV.dimensions = 3
        _sock_inp_Builder = nt.interface.new_socket(name='Builder', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Builder.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Builder.hide_value = True
        _sock_inp_Blue_Color = nt.interface.new_socket(name='Blue Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Blue_Color.default_value = (0.35572776198387146, 0.082790806889534, 0.800000011920929, 1.0)
        _sock_inp_Scale = nt.interface.new_socket(name='Scale', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Scale.default_value = 1.0
        _sock_inp_Scale.min_value = 0.0
        _sock_inp_Scale.max_value = 100.0
        _sock_inp_Mask_Scale = nt.interface.new_socket(name='Mask Scale', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Mask_Scale.default_value = 7.0
        _sock_inp_Mask_Scale.min_value = 0.0
        _sock_inp_Mask_Scale.max_value = 100.0
        _sock_inp_Strength = nt.interface.new_socket(name='Strength', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Strength.default_value = 1.0
        _sock_inp_Strength.min_value = 0.0
        _sock_inp_Strength.max_value = 100.0
        _sock_inp_UV = nt.interface.new_socket(name='UV', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_UV.default_value = (0.0, 0.0, 0.0)
        _sock_inp_UV.min_value = -3.4028234663852886e+38
        _sock_inp_UV.max_value = 3.4028234663852886e+38
        _sock_inp_UV.hide_value = True
        _sock_inp_UV.dimensions = 3

        Noise_Texture = nt.nodes.new('ShaderNodeTexNoise')
        Noise_Texture.location = (-406.43, 100.43)
        Noise_Texture.noise_dimensions = '3D'
        Noise_Texture.noise_type = 'FBM'
        Noise_Texture.normalize = True
        Noise_Texture.inputs[1].default_value = 0.0
        Noise_Texture.inputs[2].default_value = 38.599998474121094
        Noise_Texture.inputs[3].default_value = 2.0
        Noise_Texture.inputs[4].default_value = 0.5
        Noise_Texture.inputs[5].default_value = 2.0
        Noise_Texture.inputs[6].default_value = 0.0
        Noise_Texture.inputs[7].default_value = 1.0
        Noise_Texture.inputs[8].default_value = 0.0

        Mapping = nt.nodes.new('ShaderNodeMapping')
        Mapping.location = (-603.99, 72.61)
        Mapping.vector_type = 'POINT'
        Mapping.inputs[1].default_value = (0.09999999403953552, 0.0, 0.0)
        Mapping.inputs[2].default_value = (0.0, 0.0, 0.0)

        Noise_Texture_001 = nt.nodes.new('ShaderNodeTexNoise')
        Noise_Texture_001.location = (39.6, 194.28)
        Noise_Texture_001.noise_dimensions = '3D'
        Noise_Texture_001.noise_type = 'FBM'
        Noise_Texture_001.normalize = True
        Noise_Texture_001.inputs[1].default_value = 0.0
        Noise_Texture_001.inputs[2].default_value = 50.0
        Noise_Texture_001.inputs[3].default_value = 2.0
        Noise_Texture_001.inputs[4].default_value = 0.5
        Noise_Texture_001.inputs[5].default_value = 2.0
        Noise_Texture_001.inputs[6].default_value = 0.0
        Noise_Texture_001.inputs[7].default_value = 1.0
        Noise_Texture_001.inputs[8].default_value = 0.0

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-1107.0, -133.71)

        ColorRamp_002 = nt.nodes.new('ShaderNodeValToRGB')
        ColorRamp_002.location = (271.86, 471.76)
        ColorRamp_002.width = 240.0

        Noise_Texture_002 = nt.nodes.new('ShaderNodeTexNoise')
        Noise_Texture_002.location = (36.51, 497.97)
        Noise_Texture_002.noise_dimensions = '3D'
        Noise_Texture_002.noise_type = 'FBM'
        Noise_Texture_002.normalize = True
        Noise_Texture_002.inputs[1].default_value = 0.0
        Noise_Texture_002.inputs[3].default_value = 2.0
        Noise_Texture_002.inputs[4].default_value = 0.5
        Noise_Texture_002.inputs[5].default_value = 2.0
        Noise_Texture_002.inputs[6].default_value = 0.0
        Noise_Texture_002.inputs[7].default_value = 1.0
        Noise_Texture_002.inputs[8].default_value = 0.0

        Mix_001 = nt.nodes.new('ShaderNodeMix')
        Mix_001.location = (684.01, 170.97)
        Mix_001.data_type = 'RGBA'
        Mix_001.factor_mode = 'UNIFORM'
        Mix_001.blend_type = 'MULTIPLY'
        Mix_001.clamp_factor = True
        Mix_001.clamp_result = False
        Mix_001.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_001.inputs[2].default_value = 0.0
        Mix_001.inputs[3].default_value = 0.0
        Mix_001.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[7].default_value = (0.0, 0.0, 0.0, 1.0)
        Mix_001.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[9].default_value = (0.0, 0.0, 0.0)

        ColorRamp_001 = nt.nodes.new('ShaderNodeValToRGB')
        ColorRamp_001.location = (263.09, 188.2)
        ColorRamp_001.width = 240.0

        Mix_002 = nt.nodes.new('ShaderNodeMix')
        Mix_002.location = (1557.95, -37.05)
        Mix_002.data_type = 'RGBA'
        Mix_002.factor_mode = 'UNIFORM'
        Mix_002.blend_type = 'MULTIPLY'
        Mix_002.clamp_factor = True
        Mix_002.clamp_result = False
        Mix_002.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_002.inputs[2].default_value = 0.0
        Mix_002.inputs[3].default_value = 0.0
        Mix_002.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1782.61, -42.82)
        Group_Output.is_active_output = True

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (-394.78, 364.64)

        Voronoi_Texture = nt.nodes.new('ShaderNodeTexVoronoi')
        Voronoi_Texture.location = (323.56, -326.64)
        Voronoi_Texture.voronoi_dimensions = '3D'
        Voronoi_Texture.distance = 'EUCLIDEAN'
        Voronoi_Texture.feature = 'DISTANCE_TO_EDGE'
        Voronoi_Texture.normalize = False
        Voronoi_Texture.inputs[1].default_value = 0.0
        Voronoi_Texture.inputs[2].default_value = 5.0
        Voronoi_Texture.inputs[3].default_value = 0.0
        Voronoi_Texture.inputs[4].default_value = 0.5
        Voronoi_Texture.inputs[5].default_value = 2.0
        Voronoi_Texture.inputs[6].default_value = 1.0
        Voronoi_Texture.inputs[7].default_value = 0.5
        Voronoi_Texture.inputs[8].default_value = 1.0

        ColorRamp = nt.nodes.new('ShaderNodeValToRGB')
        ColorRamp.location = (526.85, -304.55)
        ColorRamp.width = 240.0

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (907.99, 152.15)
        Mix.data_type = 'RGBA'
        Mix.factor_mode = 'UNIFORM'
        Mix.blend_type = 'MULTIPLY'
        Mix.clamp_factor = True
        Mix.clamp_result = False
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[7].default_value = (0.0, 0.0, 0.0, 1.0)
        Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (1314.53, 44.91)
        Math.operation = 'MULTIPLY'
        Math.use_clamp = False
        Math.inputs[2].default_value = 0.5

        Combine_XYZ = nt.nodes.new('ShaderNodeCombineXYZ')
        Combine_XYZ.location = (-849.48, -206.96)

        Group_Input_003 = nt.nodes.new('NodeGroupInput')
        Group_Input_003.location = (1089.94, -124.26)


        nt.links.new(Mapping.outputs['Vector'], Noise_Texture.inputs['Vector'])
        nt.links.new(Group_Input.outputs['UV'], Mapping.inputs['Vector'])
        nt.links.new(Combine_XYZ.outputs['Vector'], Mapping.inputs['Scale'])
        nt.links.new(Mapping.outputs['Vector'], Noise_Texture_001.inputs['Vector'])
        nt.links.new(Noise_Texture_002.outputs['Color'], ColorRamp_002.inputs['Factor'])
        nt.links.new(Mapping.outputs['Vector'], Noise_Texture_002.inputs['Vector'])
        nt.links.new(Group_Input_001.outputs['Mask Scale'], Noise_Texture_002.inputs['Scale'])
        nt.links.new(ColorRamp_002.outputs['Color'], Mix_001.inputs['Factor'])
        nt.links.new(ColorRamp_001.outputs['Color'], Mix_001.inputs['A'])
        nt.links.new(Noise_Texture_001.outputs['Color'], ColorRamp_001.inputs['Factor'])
        nt.links.new(Math.outputs['Value'], Mix_002.inputs['Factor'])
        nt.links.new(Group_Input_003.outputs['Builder'], Mix_002.inputs['A'])
        nt.links.new(Group_Input_003.outputs['Blue Color'], Mix_002.inputs['B'])
        nt.links.new(Mix_002.outputs['Result'], Group_Output.inputs['Builder'])
        nt.links.new(Group_Input.outputs['UV'], Group_Output.inputs['UV'])
        nt.links.new(Noise_Texture.outputs['Color'], Voronoi_Texture.inputs['Vector'])
        nt.links.new(Voronoi_Texture.outputs['Distance'], ColorRamp.inputs['Factor'])
        nt.links.new(Mix_001.outputs['Result'], Mix.inputs['Factor'])
        nt.links.new(ColorRamp.outputs['Color'], Mix.inputs['A'])
        nt.links.new(Mix.outputs['Result'], Math.inputs['Value'])
        nt.links.new(Group_Input_003.outputs['Strength'], Math.inputs['Value'])
        nt.links.new(Group_Input.outputs['Scale'], Combine_XYZ.inputs['X'])
        nt.links.new(Group_Input.outputs['Scale'], Combine_XYZ.inputs['Y'])
        nt.links.new(Group_Input.outputs['Scale'], Combine_XYZ.inputs['Z'])
