# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from .....node import ShaderNode


class ShaderNodeCompiled_XY_Wave_Texture(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_XY_Wave_Texture'
    bl_label = 'lscherry.utils.procedural.XY Wave Texture'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Scale'].default_value = 25.0
        self.inputs['Distortion'].default_value = 0.0
        self.inputs['Detail'].default_value = 2.0
        self.inputs['Detail Scale'].default_value = 1.0
        self.inputs['Detail Roughness'].default_value = 0.5
        self.inputs['Phase Offset'].default_value = 0.0

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'TEXTURE'

        _sock_out_Factor_X = nt.interface.new_socket(name='Factor X', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Factor_X.default_value = 0.0
        _sock_out_Factor_X.min_value = -3.4028234663852886e+38
        _sock_out_Factor_X.max_value = 3.4028234663852886e+38
        _sock_out_Factor_Y = nt.interface.new_socket(name='Factor Y', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Factor_Y.default_value = 0.0
        _sock_out_Factor_Y.min_value = -3.4028234663852886e+38
        _sock_out_Factor_Y.max_value = 3.4028234663852886e+38
        _sock_inp_Scale = nt.interface.new_socket(name='Scale', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Scale.default_value = 25.0
        _sock_inp_Scale.min_value = 0.0
        _sock_inp_Scale.max_value = 1.0000000150474662e+30
        _sock_inp_Distortion = nt.interface.new_socket(name='Distortion', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Distortion.default_value = 0.0
        _sock_inp_Distortion.min_value = -1000.0
        _sock_inp_Distortion.max_value = 1000.0
        _sock_inp_Detail = nt.interface.new_socket(name='Detail', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Detail.default_value = 2.0
        _sock_inp_Detail.min_value = 0.0
        _sock_inp_Detail.max_value = 15.0
        _sock_inp_Detail_Scale = nt.interface.new_socket(name='Detail Scale', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Detail_Scale.default_value = 1.0
        _sock_inp_Detail_Scale.min_value = -1000.0
        _sock_inp_Detail_Scale.max_value = 1000.0
        _sock_inp_Detail_Roughness = nt.interface.new_socket(name='Detail Roughness', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Detail_Roughness.default_value = 0.5
        _sock_inp_Detail_Roughness.min_value = 0.0
        _sock_inp_Detail_Roughness.max_value = 1.0
        _sock_inp_Detail_Roughness.subtype = 'FACTOR'
        _sock_inp_Phase_Offset = nt.interface.new_socket(name='Phase Offset', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Phase_Offset.default_value = 0.0
        _sock_inp_Phase_Offset.min_value = -1000.0
        _sock_inp_Phase_Offset.max_value = 1000.0

        Texture_Coordinate = nt.nodes.new('ShaderNodeTexCoord')
        Texture_Coordinate.location = (-506.17, 6.76)
        Texture_Coordinate.hide = True

        Wave_Texture = nt.nodes.new('ShaderNodeTexWave')
        Wave_Texture.location = (128.74, 231.59)
        Wave_Texture.width = 160.0
        Wave_Texture.wave_type = 'BANDS'
        Wave_Texture.bands_direction = 'X'
        Wave_Texture.rings_direction = 'X'
        Wave_Texture.wave_profile = 'SAW'

        Wave_Texture_001 = nt.nodes.new('ShaderNodeTexWave')
        Wave_Texture_001.location = (128.74, -82.73)
        Wave_Texture_001.width = 160.0
        Wave_Texture_001.wave_type = 'BANDS'
        Wave_Texture_001.bands_direction = 'Y'
        Wave_Texture_001.rings_direction = 'X'
        Wave_Texture_001.wave_profile = 'SAW'

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (-271.77, -248.88)
        Math.hide = True
        Math.operation = 'DIVIDE'
        Math.use_clamp = False
        Math.inputs[1].default_value = 4.0
        Math.inputs[2].default_value = 0.5

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (423.6, 65.52)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-478.14, -82.63)


        nt.links.new(Texture_Coordinate.outputs['Window'], Wave_Texture.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Scale'], Wave_Texture.inputs['Scale'])
        nt.links.new(Group_Input.outputs['Distortion'], Wave_Texture.inputs['Distortion'])
        nt.links.new(Group_Input.outputs['Detail'], Wave_Texture.inputs['Detail'])
        nt.links.new(Group_Input.outputs['Detail Scale'], Wave_Texture.inputs['Detail Scale'])
        nt.links.new(Group_Input.outputs['Detail Roughness'], Wave_Texture.inputs['Detail Roughness'])
        nt.links.new(Group_Input.outputs['Phase Offset'], Wave_Texture.inputs['Phase Offset'])
        nt.links.new(Texture_Coordinate.outputs['Window'], Wave_Texture_001.inputs['Vector'])
        nt.links.new(Math.outputs['Value'], Wave_Texture_001.inputs['Scale'])
        nt.links.new(Group_Input.outputs['Distortion'], Wave_Texture_001.inputs['Distortion'])
        nt.links.new(Group_Input.outputs['Detail'], Wave_Texture_001.inputs['Detail'])
        nt.links.new(Group_Input.outputs['Detail Scale'], Wave_Texture_001.inputs['Detail Scale'])
        nt.links.new(Group_Input.outputs['Detail Roughness'], Wave_Texture_001.inputs['Detail Roughness'])
        nt.links.new(Group_Input.outputs['Phase Offset'], Wave_Texture_001.inputs['Phase Offset'])
        nt.links.new(Group_Input.outputs['Scale'], Math.inputs['Value'])
        nt.links.new(Wave_Texture.outputs['Factor'], Group_Output.inputs['Factor X'])
        nt.links.new(Wave_Texture_001.outputs['Factor'], Group_Output.inputs['Factor Y'])
