# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ....node import ShaderNode


class ShaderNodeCompiled_Blueprint_Shader(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Blueprint_Shader'
    bl_label = 'lscherry.vfx.Blueprint Shader'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Blueprint Shader'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Outline/Grid'].default_value = True
        self.inputs['Outline Color'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Grid Line Color'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Triangular Detail Color'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Emission Strength'].default_value = 5.0
        self.inputs['Outline Opacity'].default_value = 0.5
        self.inputs['Outline Thickness'].default_value = 0.9300000071525574
        self.inputs['Grid Opacity'].default_value = 0.5
        self.inputs['Grid Density'].default_value = 5.0
        self.inputs['Grid Line Thickness'].default_value = 0.004999999888241291
        self.inputs['Triangular Detail Opacity'].default_value = 1.0
        self.inputs['Triangular Detail Scale'].default_value = 0.30000001192092896

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'SHADER'

        _sock_out_Shader = nt.interface.new_socket(name='Shader', in_out='OUTPUT', socket_type='NodeSocketShader')
        _sock_inp_Outline_Grid = nt.interface.new_socket(name='Outline/Grid', in_out='INPUT', socket_type='NodeSocketBool')
        _sock_inp_Outline_Grid.default_value = True
        _sock_inp_Outline_Color = nt.interface.new_socket(name='Outline Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Outline_Color.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Grid_Line_Color = nt.interface.new_socket(name='Grid Line Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Grid_Line_Color.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Triangular_Detail_Color = nt.interface.new_socket(name='Triangular Detail Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Triangular_Detail_Color.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Emission_Strength = nt.interface.new_socket(name='Emission Strength', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Emission_Strength.default_value = 5.0
        _sock_inp_Emission_Strength.min_value = 0.0
        _sock_inp_Emission_Strength.max_value = 1000.0
        _panel_Outline = nt.interface.new_panel(name='Outline', default_closed=True)
        _sock_inp_Outline_Opacity = nt.interface.new_socket(name='Outline Opacity', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Outline)
        _sock_inp_Outline_Opacity.default_value = 0.5
        _sock_inp_Outline_Opacity.min_value = 0.0
        _sock_inp_Outline_Opacity.max_value = 1.0
        _sock_inp_Outline_Opacity.subtype = 'FACTOR'
        _sock_inp_Outline_Thickness = nt.interface.new_socket(name='Outline Thickness', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Outline)
        _sock_inp_Outline_Thickness.default_value = 0.9300000071525574
        _sock_inp_Outline_Thickness.min_value = 0.9100000262260437
        _sock_inp_Outline_Thickness.max_value = 0.9800000190734863
        _panel_Grid = nt.interface.new_panel(name='Grid', default_closed=True)
        _sock_inp_Grid_Opacity = nt.interface.new_socket(name='Grid Opacity', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Grid)
        _sock_inp_Grid_Opacity.default_value = 0.5
        _sock_inp_Grid_Opacity.min_value = 0.0
        _sock_inp_Grid_Opacity.max_value = 1.0
        _sock_inp_Grid_Opacity.subtype = 'FACTOR'
        _sock_inp_Grid_Density = nt.interface.new_socket(name='Grid Density', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Grid)
        _sock_inp_Grid_Density.default_value = 5.0
        _sock_inp_Grid_Density.min_value = 5.0
        _sock_inp_Grid_Density.max_value = 50.0
        _sock_inp_Grid_Line_Thickness = nt.interface.new_socket(name='Grid Line Thickness', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Grid)
        _sock_inp_Grid_Line_Thickness.default_value = 0.004999999888241291
        _sock_inp_Grid_Line_Thickness.min_value = 0.004999999888241291
        _sock_inp_Grid_Line_Thickness.max_value = 0.15000000596046448
        _panel_Triangular = nt.interface.new_panel(name='Triangular', default_closed=True)
        _sock_inp_Triangular_Detail_Opacity = nt.interface.new_socket(name='Triangular Detail Opacity', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Triangular)
        _sock_inp_Triangular_Detail_Opacity.default_value = 1.0
        _sock_inp_Triangular_Detail_Opacity.min_value = 0.0
        _sock_inp_Triangular_Detail_Opacity.max_value = 1.0
        _sock_inp_Triangular_Detail_Opacity.subtype = 'FACTOR'
        _sock_inp_Triangular_Detail_Scale = nt.interface.new_socket(name='Triangular Detail Scale', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Triangular)
        _sock_inp_Triangular_Detail_Scale.default_value = 0.30000001192092896
        _sock_inp_Triangular_Detail_Scale.min_value = 0.009999999776482582
        _sock_inp_Triangular_Detail_Scale.max_value = 1.0

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (2719.83, -745.15)
        Group_Input.width = 147.89

        Mix_Shader_001 = nt.nodes.new('ShaderNodeMixShader')
        Mix_Shader_001.location = (310.19, -123.17)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1087.67, -92.64)
        Group_Output.is_active_output = True

        Emission = nt.nodes.new('ShaderNodeEmission')
        Emission.location = (30.08, -87.36)
        Emission.hide = True
        Emission.inputs[2].default_value = 0.0

        ColorRamp = nt.nodes.new('ShaderNodeValToRGB')
        ColorRamp.location = (367.03, -40.39)
        ColorRamp.width = 240.0
        ColorRamp.hide = True

        Layer_Weight = nt.nodes.new('ShaderNodeLayerWeight')
        Layer_Weight.location = (198.24, -44.27)
        Layer_Weight.hide = True
        Layer_Weight.inputs[1].default_value = (0.0, 0.0, 0.0)

        Emission_002 = nt.nodes.new('ShaderNodeEmission')
        Emission_002.location = (395.82, -106.51)
        Emission_002.inputs[2].default_value = 0.0

        Wireframe = nt.nodes.new('ShaderNodeWireframe')
        Wireframe.location = (33.15, -210.74)
        Wireframe.hide = True
        Wireframe.use_pixel_size = False

        Math_003 = nt.nodes.new('ShaderNodeMath')
        Math_003.location = (33.15, -178.32)
        Math_003.hide = True
        Math_003.operation = 'MULTIPLY'
        Math_003.use_clamp = False
        Math_003.inputs[1].default_value = 0.009999999776482582
        Math_003.inputs[2].default_value = 0.5

        Invert_005 = nt.nodes.new('ShaderNodeInvert')
        Invert_005.location = (864.28, -243.18)
        Invert_005.inputs[0].default_value = 1.0

        Invert_006 = nt.nodes.new('ShaderNodeInvert')
        Invert_006.location = (239.11, -353.96)
        Invert_006.inputs[0].default_value = 1.0

        Transparent_BSDF_002 = nt.nodes.new('ShaderNodeBsdfTransparent')
        Transparent_BSDF_002.location = (790.41, -283.74)
        Transparent_BSDF_002.hide = True
        Transparent_BSDF_002.inputs[0].default_value = (1.0, 1.0, 1.0, 1.0)
        Transparent_BSDF_002.inputs[1].default_value = 0.0

        Mix_Shader_007 = nt.nodes.new('ShaderNodeMixShader')
        Mix_Shader_007.location = (1244.17, -116.63)

        Transparent_BSDF_003 = nt.nodes.new('ShaderNodeBsdfTransparent')
        Transparent_BSDF_003.location = (1020.12, -240.76)
        Transparent_BSDF_003.hide = True
        Transparent_BSDF_003.inputs[0].default_value = (1.0, 1.0, 1.0, 1.0)
        Transparent_BSDF_003.inputs[1].default_value = 0.0

        Brick_Texture = nt.nodes.new('ShaderNodeTexBrick')
        Brick_Texture.location = (274.94, -36.07)
        Brick_Texture.width = 150.0
        Brick_Texture.offset_frequency = 2
        Brick_Texture.squash_frequency = 2
        Brick_Texture.offset = 0.0
        Brick_Texture.squash = 1.0
        Brick_Texture.inputs[1].default_value = (0.0, 0.0, 0.0, 1.0)
        Brick_Texture.inputs[2].default_value = (0.0, 0.0, 0.0, 1.0)
        Brick_Texture.inputs[3].default_value = (1.0, 1.0, 1.0, 1.0)
        Brick_Texture.inputs[6].default_value = 0.10000000149011612
        Brick_Texture.inputs[7].default_value = 0.0
        Brick_Texture.inputs[8].default_value = 1.0
        Brick_Texture.inputs[9].default_value = 1.0

        Emission_001 = nt.nodes.new('ShaderNodeEmission')
        Emission_001.location = (790.41, -323.72)
        Emission_001.hide = True
        Emission_001.inputs[2].default_value = 0.0

        Invert = nt.nodes.new('ShaderNodeInvert')
        Invert.location = (671.35, -174.79)
        Invert.hide = True
        Invert.inputs[0].default_value = 1.0

        Mix_Shader_004 = nt.nodes.new('ShaderNodeMixShader')
        Mix_Shader_004.location = (1021.02, -187.6)
        Mix_Shader_004.hide = True

        Mix_Shader_005 = nt.nodes.new('ShaderNodeMixShader')
        Mix_Shader_005.location = (30.36, -91.58)

        Mix_Shader = nt.nodes.new('ShaderNodeMixShader')
        Mix_Shader.location = (30.39, -36.31)

        Mix_Shader_008 = nt.nodes.new('ShaderNodeMixShader')
        Mix_Shader_008.location = (30.31, -35.75)

        Mix_003 = nt.nodes.new('ShaderNodeMix')
        Mix_003.location = (572.6, -314.08)
        Mix_003.hide = True
        Mix_003.data_type = 'RGBA'
        Mix_003.factor_mode = 'UNIFORM'
        Mix_003.blend_type = 'MULTIPLY'
        Mix_003.clamp_factor = True
        Mix_003.clamp_result = True
        Mix_003.inputs[0].default_value = 1.0
        Mix_003.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_003.inputs[2].default_value = 0.0
        Mix_003.inputs[3].default_value = 0.0
        Mix_003.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_003.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_003.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_003.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (506.43, -253.86)
        Mix.data_type = 'RGBA'
        Mix.factor_mode = 'UNIFORM'
        Mix.blend_type = 'MIX'
        Mix.clamp_factor = True
        Mix.clamp_result = False
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[6].default_value = (0.5, 0.5, 0.5, 1.0)
        Mix.inputs[7].default_value = (0.0, 0.0, 0.0, 1.0)
        Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (29.74, -247.86)
        Group_Input_001.width = 147.89

        Group_Input_002 = nt.nodes.new('NodeGroupInput')
        Group_Input_002.location = (30.36, -35.68)
        Group_Input_002.width = 147.89

        Group_Input_003 = nt.nodes.new('NodeGroupInput')
        Group_Input_003.location = (33.15, -93.07)
        Group_Input_003.width = 147.89

        Group_Input_004 = nt.nodes.new('NodeGroupInput')
        Group_Input_004.location = (310.19, -36.11)
        Group_Input_004.width = 147.89

        Group_Input_005 = nt.nodes.new('NodeGroupInput')
        Group_Input_005.location = (572.6, -248.52)
        Group_Input_005.width = 147.89

        Group_Input_006 = nt.nodes.new('NodeGroupInput')
        Group_Input_006.location = (1021.02, -109.46)
        Group_Input_006.width = 147.89
        Group_Input_006.hide = True

        Math_001 = nt.nodes.new('ShaderNodeMath')
        Math_001.location = (1021.02, -143.35)
        Math_001.hide = True
        Math_001.operation = 'SUBTRACT'
        Math_001.use_clamp = False
        Math_001.inputs[0].default_value = 1.0
        Math_001.inputs[2].default_value = 0.5

        Group_Input_007 = nt.nodes.new('NodeGroupInput')
        Group_Input_007.location = (782.26, -359.47)
        Group_Input_007.width = 147.89

        Group_Input_008 = nt.nodes.new('NodeGroupInput')
        Group_Input_008.location = (229.02, -295.66)
        Group_Input_008.width = 147.89

        Transparent_BSDF_004 = nt.nodes.new('ShaderNodeBsdfTransparent')
        Transparent_BSDF_004.location = (3403.27, -960.1)
        Transparent_BSDF_004.inputs[0].default_value = (1.0, 1.0, 1.0, 1.0)
        Transparent_BSDF_004.inputs[1].default_value = 0.0

        Texture_Coordinate = nt.nodes.new('ShaderNodeTexCoord')
        Texture_Coordinate.location = (41.84, -165.61)
        Texture_Coordinate.hide = True
        Texture_Coordinate.from_instancer = False

        Group_Input_009 = nt.nodes.new('NodeGroupInput')
        Group_Input_009.location = (29.96, -36.21)
        Group_Input_009.width = 147.89

        Math_004 = nt.nodes.new('ShaderNodeMath')
        Math_004.location = (213.0, -192.86)
        Math_004.hide = True
        Math_004.operation = 'MULTIPLY'
        Math_004.use_clamp = False
        Math_004.inputs[2].default_value = 0.5

        Group_Input_010 = nt.nodes.new('NodeGroupInput')
        Group_Input_010.location = (2721.25, -825.46)
        Group_Input_010.width = 147.89


        nt.links.new(Group_Input_004.outputs['Outline Opacity'], Mix_Shader_001.inputs['Factor'])
        nt.links.new(Transparent_BSDF_004.outputs['BSDF'], Mix_Shader_001.inputs['Shader'])
        nt.links.new(Mix_Shader.outputs['Shader'], Mix_Shader_001.inputs['Shader'])
        nt.links.new(Mix_Shader_008.outputs['Shader'], Group_Output.inputs['Shader'])
        nt.links.new(Group_Input.outputs['Outline Color'], Emission.inputs['Color'])
        nt.links.new(Group_Input_010.outputs['Emission Strength'], Emission.inputs['Strength'])
        nt.links.new(Layer_Weight.outputs['Fresnel'], ColorRamp.inputs['Factor'])
        nt.links.new(Group_Input.outputs['Outline Thickness'], Layer_Weight.inputs['Blend'])
        nt.links.new(Group_Input_003.outputs['Triangular Detail Color'], Emission_002.inputs['Color'])
        nt.links.new(Math_004.outputs['Value'], Emission_002.inputs['Strength'])
        nt.links.new(Math_003.outputs['Value'], Wireframe.inputs['Size'])
        nt.links.new(Group_Input_003.outputs['Triangular Detail Scale'], Math_003.inputs['Value'])
        nt.links.new(Mix.outputs['Result'], Invert_005.inputs['Color'])
        nt.links.new(Group_Input_008.outputs['Triangular Detail Opacity'], Invert_006.inputs['Color'])
        nt.links.new(Math_001.outputs['Value'], Mix_Shader_007.inputs['Factor'])
        nt.links.new(Mix_Shader_004.outputs['Shader'], Mix_Shader_007.inputs['Shader'])
        nt.links.new(Transparent_BSDF_003.outputs['BSDF'], Mix_Shader_007.inputs['Shader'])
        nt.links.new(Texture_Coordinate.outputs['Generated'], Brick_Texture.inputs['Vector'])
        nt.links.new(Group_Input_001.outputs['Grid Density'], Brick_Texture.inputs['Scale'])
        nt.links.new(Group_Input_001.outputs['Grid Line Thickness'], Brick_Texture.inputs['Mortar Size'])
        nt.links.new(Mix_003.outputs['Result'], Emission_001.inputs['Color'])
        nt.links.new(Group_Input_007.outputs['Emission Strength'], Emission_001.inputs['Strength'])
        nt.links.new(Brick_Texture.outputs['Color'], Invert.inputs['Color'])
        nt.links.new(Invert.outputs['Color'], Mix_Shader_004.inputs['Factor'])
        nt.links.new(Emission_001.outputs['Emission'], Mix_Shader_004.inputs['Shader'])
        nt.links.new(Transparent_BSDF_002.outputs['BSDF'], Mix_Shader_004.inputs['Shader'])
        nt.links.new(Group_Input_002.outputs['Outline/Grid'], Mix_Shader_005.inputs['Factor'])
        nt.links.new(Mix_Shader_001.outputs['Shader'], Mix_Shader_005.inputs['Shader'])
        nt.links.new(Mix_Shader_007.outputs['Shader'], Mix_Shader_005.inputs['Shader'])
        nt.links.new(ColorRamp.outputs['Color'], Mix_Shader.inputs['Factor'])
        nt.links.new(Emission.outputs['Emission'], Mix_Shader.inputs['Shader'])
        nt.links.new(Transparent_BSDF_004.outputs['BSDF'], Mix_Shader.inputs['Shader'])
        nt.links.new(Invert_005.outputs['Color'], Mix_Shader_008.inputs['Factor'])
        nt.links.new(Emission_002.outputs['Emission'], Mix_Shader_008.inputs['Shader'])
        nt.links.new(Mix_Shader_005.outputs['Shader'], Mix_Shader_008.inputs['Shader'])
        nt.links.new(Group_Input_005.outputs['Grid Line Color'], Mix_003.inputs['A'])
        nt.links.new(Brick_Texture.outputs['Color'], Mix_003.inputs['B'])
        nt.links.new(Invert_006.outputs['Color'], Mix.inputs['Factor'])
        nt.links.new(Group_Input_006.outputs['Grid Opacity'], Math_001.inputs['Value'])
        nt.links.new(Group_Input_009.outputs['Emission Strength'], Math_004.inputs['Value'])
        nt.links.new(Wireframe.outputs['Factor'], Math_004.inputs['Value'])
