# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from .....node import ShaderNode, ensure_node_group


class ShaderNodeCompiled_Strinova__Face_Starter(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Strinova__Face_Starter'
    bl_label = 'lscherry.starters.strinova.Strinova: Face Starter'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Strinova: Face Starter'

    image_face_d_texture: bpy.props.PointerProperty(
        name='Face_D Texture',
        type=bpy.types.Image,
        description='Face_D Texture texture',
        update=lambda self, ctx: self.valuesUpdate(ctx),
    )  # type: ignore
    image_sdf_texture: bpy.props.PointerProperty(
        name='SDF Texture',
        type=bpy.types.Image,
        description='SDF Texture texture',
        update=lambda self, ctx: self.valuesUpdate(ctx),
    )  # type: ignore

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Shadow Color'].default_value = (0.8468736410140991, 0.6938719749450684, 0.6104958653450012, 1.0)
        self.inputs['SSS Color'].default_value = (0.4735316038131714, 0.08650047332048416, 0.0, 1.0)
        self.inputs['Alpha'].default_value = 1.0
        self.inputs['Normal'].default_value = (0.0, 0.0, 0.0)

    def draw_buttons(self, context, layout):
        layout.label(text='Face_D Texture')
        layout.template_ID(self, 'image_face_d_texture', open="image.open")
        layout.label(text='SDF Texture')
        layout.template_ID(self, 'image_sdf_texture', open="image.open")

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'SHADER'
        nt.description = 'Quick build Strinova face material'

        _sock_out_Shader = nt.interface.new_socket(name='Shader', in_out='OUTPUT', socket_type='NodeSocketShader')
        _sock_out_Shader.hide_value = True
        _sock_out_To_AgrX = nt.interface.new_socket(name='To AgrX', in_out='OUTPUT', socket_type='NodeSocketShader')
        _sock_out_Combined = nt.interface.new_socket(name='Combined', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Combined.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_out_Combined.hide_value = True
        _sock_out_Diffuse_Mask = nt.interface.new_socket(name='Diffuse Mask', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Diffuse_Mask.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Shadow_Color = nt.interface.new_socket(name='Shadow Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Shadow_Color.default_value = (0.8468736410140991, 0.6938719749450684, 0.6104958653450012, 1.0)
        _sock_inp_SSS_Color = nt.interface.new_socket(name='SSS Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_SSS_Color.default_value = (0.4735316038131714, 0.08650047332048416, 0.0, 1.0)
        _sock_inp_Alpha = nt.interface.new_socket(name='Alpha', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Alpha.default_value = 1.0
        _sock_inp_Alpha.min_value = 0.0
        _sock_inp_Alpha.max_value = 1.0
        _sock_inp_Alpha.subtype = 'FACTOR'
        _sock_inp_Normal = nt.interface.new_socket(name='Normal', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Normal.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Normal.min_value = -3.4028234663852886e+38
        _sock_inp_Normal.max_value = 3.4028234663852886e+38
        _sock_inp_Normal.hide_value = True
        _sock_inp_Normal.dimensions = 3

        Texture_Coordinate = nt.nodes.new('ShaderNodeTexCoord')
        Texture_Coordinate.location = (-460.62, -23.99)
        Texture_Coordinate.hide = True
        Texture_Coordinate.from_instancer = False

        Mapping = nt.nodes.new('ShaderNodeMapping')
        Mapping.location = (-268.11, 53.82)
        Mapping.vector_type = 'POINT'
        Mapping.inputs[1].default_value = (0.0, 0.0, 0.0)
        Mapping.inputs[2].default_value = (0.0, 0.0, 0.0)
        Mapping.inputs[3].default_value = (1.0, 1.0, 1.0)

        Image_Texture = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture.location = (92.35, 148.34)
        Image_Texture.width = 240.0
        Image_Texture.label = 'Face_D Texture'
        Image_Texture.projection = 'FLAT'
        Image_Texture.interpolation = 'Linear'
        Image_Texture.projection_blend = 0.0
        Image_Texture.extension = 'REPEAT'

        Image_Texture_001 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_001.location = (92.35, -148.34)
        Image_Texture_001.width = 240.0
        Image_Texture_001.label = 'SDF Texture'
        Image_Texture_001.projection = 'FLAT'
        Image_Texture_001.interpolation = 'Linear'
        Image_Texture_001.projection_blend = 0.0
        Image_Texture_001.extension = 'REPEAT'

        lscherry_utils_procedural_Build_Face_Ramp = nt.nodes.new('ShaderNodeCompiled_Build_Face_Ramp')
        lscherry_utils_procedural_Build_Face_Ramp.location = (432.54, -65.13)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (984.27, 171.07)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (441.75, 154.02)

        Face_Ramp_Builder__Vector_Math = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Vector_Math.location = (-436.76, 303.86)
        Face_Ramp_Builder__Vector_Math.operation = 'NORMALIZE'
        Face_Ramp_Builder__Vector_Math.inputs[1].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Vector_Math.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Vector_Math.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Vector_Math_004 = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Vector_Math_004.location = (29.82, -36.16)
        Face_Ramp_Builder__Vector_Math_004.operation = 'DOT_PRODUCT'
        Face_Ramp_Builder__Vector_Math_004.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Vector_Math_004.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Mapping = nt.nodes.new('ShaderNodeMapping')
        Face_Ramp_Builder__Mapping.location = (789.56, 166.19)
        Face_Ramp_Builder__Mapping.hide = True
        Face_Ramp_Builder__Mapping.vector_type = 'POINT'
        Face_Ramp_Builder__Mapping.inputs[1].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Mapping.inputs[2].default_value = (0.0, 0.0, 0.0)

        Face_Ramp_Builder__Mix = nt.nodes.new('ShaderNodeMix')
        Face_Ramp_Builder__Mix.location = (600.53, -64.78)
        Face_Ramp_Builder__Mix.hide = True
        Face_Ramp_Builder__Mix.data_type = 'VECTOR'
        Face_Ramp_Builder__Mix.factor_mode = 'UNIFORM'
        Face_Ramp_Builder__Mix.blend_type = 'MIX'
        Face_Ramp_Builder__Mix.clamp_factor = False
        Face_Ramp_Builder__Mix.clamp_result = False
        Face_Ramp_Builder__Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Face_Ramp_Builder__Mix.inputs[2].default_value = 0.0
        Face_Ramp_Builder__Mix.inputs[3].default_value = 0.0
        Face_Ramp_Builder__Mix.inputs[6].default_value = (0.5, 0.5, 0.5, 1.0)
        Face_Ramp_Builder__Mix.inputs[7].default_value = (0.5, 0.5, 0.5, 1.0)
        Face_Ramp_Builder__Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Face_Ramp_Builder__Group_002 = nt.nodes.new('ShaderNodeGroup')
        Face_Ramp_Builder__Group_002.location = (-614.21, 303.86)
        Face_Ramp_Builder__Group_002.node_tree = ensure_node_group('.lscherry.utils.separator.To Oxy')

        Face_Ramp_Builder__Combine_XYZ_001 = nt.nodes.new('ShaderNodeCombineXYZ')
        Face_Ramp_Builder__Combine_XYZ_001.location = (337.3, -131.72)
        Face_Ramp_Builder__Combine_XYZ_001.hide = True
        Face_Ramp_Builder__Combine_XYZ_001.inputs[1].default_value = 1.0
        Face_Ramp_Builder__Combine_XYZ_001.inputs[2].default_value = 1.0
        Face_Ramp_Builder__Combine_XYZ_001.inputs[0].default_value = 1.0

        Face_Ramp_Builder__Combine_XYZ = nt.nodes.new('ShaderNodeCombineXYZ')
        Face_Ramp_Builder__Combine_XYZ.location = (337.3, -96.75)
        Face_Ramp_Builder__Combine_XYZ.hide = True
        Face_Ramp_Builder__Combine_XYZ.inputs[1].default_value = 1.0
        Face_Ramp_Builder__Combine_XYZ.inputs[2].default_value = 1.0
        Face_Ramp_Builder__Combine_XYZ.inputs[0].default_value = -1.0

        Face_Ramp_Builder__Map_Range = nt.nodes.new('ShaderNodeMapRange')
        Face_Ramp_Builder__Map_Range.location = (273.43, -35.88)
        Face_Ramp_Builder__Map_Range.clamp = True
        Face_Ramp_Builder__Map_Range.interpolation_type = 'LINEAR'
        Face_Ramp_Builder__Map_Range.data_type = 'FLOAT'
        Face_Ramp_Builder__Map_Range.inputs[3].default_value = 0.0
        Face_Ramp_Builder__Map_Range.inputs[4].default_value = 1.0
        Face_Ramp_Builder__Map_Range.inputs[5].default_value = 4.0
        Face_Ramp_Builder__Map_Range.inputs[6].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Map_Range.inputs[7].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Map_Range.inputs[8].default_value = (1.0, 1.0, 1.0)
        Face_Ramp_Builder__Map_Range.inputs[9].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Map_Range.inputs[10].default_value = (1.0, 1.0, 1.0)
        Face_Ramp_Builder__Map_Range.inputs[11].default_value = (4.0, 4.0, 4.0)
        Face_Ramp_Builder__Map_Range.inputs[1].default_value = -0.5
        Face_Ramp_Builder__Map_Range.inputs[2].default_value = 0.5

        Face_Ramp_Builder__Vector_Math_003 = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Vector_Math_003.location = (34.96, -213.99)
        Face_Ramp_Builder__Vector_Math_003.operation = 'DOT_PRODUCT'
        Face_Ramp_Builder__Vector_Math_003.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Vector_Math_003.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Math = nt.nodes.new('ShaderNodeMath')
        Face_Ramp_Builder__Math.location = (213.76, -53.5)
        Face_Ramp_Builder__Math.hide = True
        Face_Ramp_Builder__Math.operation = 'GREATER_THAN'
        Face_Ramp_Builder__Math.use_clamp = False
        Face_Ramp_Builder__Math.inputs[1].default_value = 0.0
        Face_Ramp_Builder__Math.inputs[2].default_value = 0.5

        Face_Ramp_Builder__Group_001 = nt.nodes.new('ShaderNodeGroup')
        Face_Ramp_Builder__Group_001.location = (-793.53, 329.85)
        Face_Ramp_Builder__Group_001.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Face_Ramp_Builder__Group_001.inputs[0].default_value = False
        Face_Ramp_Builder__Group_001.inputs[2].default_value = 0.0

        Face_Ramp_Builder__Attribute_002 = nt.nodes.new('ShaderNodeAttribute')
        Face_Ramp_Builder__Attribute_002.location = (-1074.02, 238.62)
        Face_Ramp_Builder__Attribute_002.attribute_type = 'GEOMETRY'
        Face_Ramp_Builder__Attribute_002.attribute_name = 'm'

        Face_Ramp_Builder__Geometry = nt.nodes.new('ShaderNodeNewGeometry')
        Face_Ramp_Builder__Geometry.location = (-1073.03, 100.35)

        Face_Ramp_Builder__Math_003 = nt.nodes.new('ShaderNodeMath')
        Face_Ramp_Builder__Math_003.location = (273.92, -288.96)
        Face_Ramp_Builder__Math_003.hide = True
        Face_Ramp_Builder__Math_003.operation = 'GREATER_THAN'
        Face_Ramp_Builder__Math_003.use_clamp = False
        Face_Ramp_Builder__Math_003.inputs[1].default_value = 0.0
        Face_Ramp_Builder__Math_003.inputs[2].default_value = 0.5

        Make_Toon__Group_004 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group_004.location = (114.48, 173.71)
        Make_Toon__Group_004.node_tree = ensure_node_group('.lscherry.utils.separator.Combined To Shader')

        Face_Ramp_Builder__Group__Group_004 = nt.nodes.new('ShaderNodeGroup')
        Face_Ramp_Builder__Group__Group_004.location = (275.03, 266.26)
        Face_Ramp_Builder__Group__Group_004.hide = True
        Face_Ramp_Builder__Group__Group_004.node_tree = ensure_node_group('.lscherry.utils.separator.To Oxy')

        Face_Ramp_Builder__Group__Group_003 = nt.nodes.new('ShaderNodeGroup')
        Face_Ramp_Builder__Group__Group_003.location = (278.46, 34.25)
        Face_Ramp_Builder__Group__Group_003.hide = True
        Face_Ramp_Builder__Group__Group_003.node_tree = ensure_node_group('.lscherry.utils.separator.To Oxy')

        Face_Ramp_Builder__Group__Vector_Math_002 = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Group__Vector_Math_002.location = (275.03, 231.08)
        Face_Ramp_Builder__Group__Vector_Math_002.hide = True
        Face_Ramp_Builder__Group__Vector_Math_002.operation = 'NORMALIZE'
        Face_Ramp_Builder__Group__Vector_Math_002.inputs[1].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Group__Vector_Math_002.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Group__Vector_Math_002.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Group__Vector_Math_001 = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Group__Vector_Math_001.location = (278.46, -3.05)
        Face_Ramp_Builder__Group__Vector_Math_001.hide = True
        Face_Ramp_Builder__Group__Vector_Math_001.operation = 'NORMALIZE'
        Face_Ramp_Builder__Group__Vector_Math_001.inputs[1].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Group__Vector_Math_001.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Group__Vector_Math_001.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Group__Attribute_001 = nt.nodes.new('ShaderNodeAttribute')
        Face_Ramp_Builder__Group__Attribute_001.location = (275.03, 382.69)
        Face_Ramp_Builder__Group__Attribute_001.attribute_type = 'GEOMETRY'
        Face_Ramp_Builder__Group__Attribute_001.attribute_name = 'fx'

        Face_Ramp_Builder__Group__Attribute = nt.nodes.new('ShaderNodeAttribute')
        Face_Ramp_Builder__Group__Attribute.location = (278.46, 153.46)
        Face_Ramp_Builder__Group__Attribute.attribute_type = 'GEOMETRY'
        Face_Ramp_Builder__Group__Attribute.attribute_name = 'fy'

        Face_Ramp_Builder__Group__Combine_XYZ_002 = nt.nodes.new('ShaderNodeCombineXYZ')
        Face_Ramp_Builder__Group__Combine_XYZ_002.location = (275.65, -242.83)
        Face_Ramp_Builder__Group__Combine_XYZ_002.inputs[0].default_value = 1.0
        Face_Ramp_Builder__Group__Combine_XYZ_002.inputs[1].default_value = 0.0
        Face_Ramp_Builder__Group__Combine_XYZ_002.inputs[2].default_value = 0.0

        Face_Ramp_Builder__Group__Combine_XYZ_003 = nt.nodes.new('ShaderNodeCombineXYZ')
        Face_Ramp_Builder__Group__Combine_XYZ_003.location = (275.65, -108.7)
        Face_Ramp_Builder__Group__Combine_XYZ_003.inputs[0].default_value = -1.0
        Face_Ramp_Builder__Group__Combine_XYZ_003.inputs[1].default_value = 0.0
        Face_Ramp_Builder__Group__Combine_XYZ_003.inputs[2].default_value = 0.0

        Make_Toon__Group__Group_004 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_004.location = (252.78, -692.63)
        Make_Toon__Group__Group_004.hide = True
        Make_Toon__Group__Group_004.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Make_Toon__Group__Group_004.inputs[0].default_value = False
        Make_Toon__Group__Group_004.inputs[2].default_value = 0.0

        Make_Toon__Group__Group_002 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_002.location = (253.6, -376.4)
        Make_Toon__Group__Group_002.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Make_Toon__Group__Group_002.inputs[0].default_value = False
        Make_Toon__Group__Group_002.inputs[2].default_value = 0.0

        Make_Toon__Group__Group_001 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_001.location = (253.93, -218.27)
        Make_Toon__Group__Group_001.node_tree = ensure_node_group('.lscherry.core.Toon Core')
        Make_Toon__Group__Group_001.inputs[0].default_value = 1.0
        Make_Toon__Group__Group_001.inputs[1].default_value = 0.0

        Make_Toon__Group__Group_027 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_027.location = (151.12, -84.71)
        Make_Toon__Group__Group_027.node_tree = ensure_node_group('.lscherry.utils.bnodes.Limit Color Value')
        Make_Toon__Group__Group_027.inputs[2].default_value = 0.44999998807907104
        Make_Toon__Group__Group_027.inputs[0].default_value = (0.0, 0.04392065852880478, 0.42326757311820984, 1.0)

        Make_Toon__Group__Mix_008 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_008.location = (319.16, -66.56)
        Make_Toon__Group__Mix_008.hide = True
        Make_Toon__Group__Mix_008.data_type = 'RGBA'
        Make_Toon__Group__Mix_008.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_008.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_008.clamp_factor = True
        Make_Toon__Group__Mix_008.clamp_result = False
        Make_Toon__Group__Mix_008.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_008.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_008.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_008.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_008.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_008.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_008.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_008.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_006 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_006.location = (313.69, -94.45)
        Make_Toon__Group__Mix_006.hide = True
        Make_Toon__Group__Mix_006.data_type = 'RGBA'
        Make_Toon__Group__Mix_006.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_006.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_006.clamp_factor = True
        Make_Toon__Group__Mix_006.clamp_result = False
        Make_Toon__Group__Mix_006.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_006.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_006.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_006.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_006.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_006.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_006.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_006.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Group_026 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_026.location = (144.42, -153.49)
        Make_Toon__Group__Group_026.node_tree = ensure_node_group('.lscherry.utils.bnodes.Limit Color Value')
        Make_Toon__Group__Group_026.inputs[2].default_value = 0.8999999761581421

        Make_Toon__Group__Mix_001 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_001.location = (730.55, -253.21)
        Make_Toon__Group__Mix_001.data_type = 'RGBA'
        Make_Toon__Group__Mix_001.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_001.blend_type = 'MIX'
        Make_Toon__Group__Mix_001.clamp_factor = True
        Make_Toon__Group__Mix_001.clamp_result = False
        Make_Toon__Group__Mix_001.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_001.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_001.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_001.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_001.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_001.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_001.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_004 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_004.location = (249.06, -340.08)
        Make_Toon__Group__Mix_004.label = 'Add Base Color'
        Make_Toon__Group__Mix_004.data_type = 'RGBA'
        Make_Toon__Group__Mix_004.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_004.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_004.clamp_factor = True
        Make_Toon__Group__Mix_004.clamp_result = False
        Make_Toon__Group__Mix_004.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_004.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_004.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_004.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_004.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_004.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_004.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_004.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Invert_Color = nt.nodes.new('ShaderNodeInvert')
        Make_Toon__Group__Invert_Color.location = (253.01, -165.24)
        Make_Toon__Group__Invert_Color.inputs[0].default_value = 1.0

        Make_Toon__Group__Mix_005 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_005.location = (168.67, -36.37)
        Make_Toon__Group__Mix_005.label = 'Add Rim Color'
        Make_Toon__Group__Mix_005.data_type = 'RGBA'
        Make_Toon__Group__Mix_005.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_005.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_005.clamp_factor = True
        Make_Toon__Group__Mix_005.clamp_result = False
        Make_Toon__Group__Mix_005.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_005.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_005.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_005.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_005.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_005.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_005.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_005.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_005.inputs[7].default_value = (0.0, 0.0, 0.0, 1.0)

        Make_Toon__Group__Mix_002 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_002.location = (491.8, -104.28)
        Make_Toon__Group__Mix_002.label = 'Add Shadow Color'
        Make_Toon__Group__Mix_002.data_type = 'RGBA'
        Make_Toon__Group__Mix_002.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_002.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_002.clamp_factor = True
        Make_Toon__Group__Mix_002.clamp_result = False
        Make_Toon__Group__Mix_002.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_002.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_002.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_002.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_002.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_002.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_002.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_015 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_015.location = (37.37, -36.0)
        Make_Toon__Group__Mix_015.data_type = 'RGBA'
        Make_Toon__Group__Mix_015.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_015.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_015.clamp_factor = True
        Make_Toon__Group__Mix_015.clamp_result = False
        Make_Toon__Group__Mix_015.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_015.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_015.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_015.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_015.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_015.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_015.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_012 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_012.location = (30.14, -445.01)
        Make_Toon__Group__Mix_012.data_type = 'RGBA'
        Make_Toon__Group__Mix_012.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_012.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_012.clamp_factor = True
        Make_Toon__Group__Mix_012.clamp_result = False
        Make_Toon__Group__Mix_012.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_012.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_012.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_012.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_012.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_012.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_012.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_013 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_013.location = (37.37, -813.76)
        Make_Toon__Group__Mix_013.data_type = 'RGBA'
        Make_Toon__Group__Mix_013.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_013.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_013.clamp_factor = True
        Make_Toon__Group__Mix_013.clamp_result = False
        Make_Toon__Group__Mix_013.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_013.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_013.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_013.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_013.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_013.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_013.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Math = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Math.location = (5210.95, -39.98)
        Make_Toon__Group__Math.label = 'x 2'
        Make_Toon__Group__Math.hide = True
        Make_Toon__Group__Math.operation = 'MULTIPLY'
        Make_Toon__Group__Math.use_clamp = False
        Make_Toon__Group__Math.inputs[1].default_value = 2.0
        Make_Toon__Group__Math.inputs[2].default_value = 0.5

        Make_Toon__Group__Math_001 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Math_001.location = (5208.92, -1.98)
        Make_Toon__Group__Math_001.label = 'Invert'
        Make_Toon__Group__Math_001.hide = True
        Make_Toon__Group__Math_001.operation = 'SUBTRACT'
        Make_Toon__Group__Math_001.use_clamp = False
        Make_Toon__Group__Math_001.inputs[0].default_value = 1.0
        Make_Toon__Group__Math_001.inputs[2].default_value = 0.5
        Make_Toon__Group__Math_001.inputs[1].default_value = True

        Make_Toon__Group__Math_003 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Math_003.location = (5425.33, 92.49)
        Make_Toon__Group__Math_003.operation = 'MULTIPLY'
        Make_Toon__Group__Math_003.use_clamp = False
        Make_Toon__Group__Math_003.inputs[2].default_value = 0.5

        Make_Toon__Group__Mix_014 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_014.location = (37.37, -1131.65)
        Make_Toon__Group__Mix_014.data_type = 'RGBA'
        Make_Toon__Group__Mix_014.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_014.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_014.clamp_factor = True
        Make_Toon__Group__Mix_014.clamp_result = False
        Make_Toon__Group__Mix_014.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_014.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_014.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_014.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_014.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_014.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_014.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_009 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_009.location = (30.08, -35.62)
        Make_Toon__Group__Mix_009.data_type = 'RGBA'
        Make_Toon__Group__Mix_009.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_009.blend_type = 'ADD'
        Make_Toon__Group__Mix_009.clamp_factor = True
        Make_Toon__Group__Mix_009.clamp_result = False
        Make_Toon__Group__Mix_009.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_009.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_009.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_009.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_009.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_009.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_009.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_011 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_011.location = (30.18, -35.62)
        Make_Toon__Group__Mix_011.data_type = 'RGBA'
        Make_Toon__Group__Mix_011.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_011.blend_type = 'ADD'
        Make_Toon__Group__Mix_011.clamp_factor = True
        Make_Toon__Group__Mix_011.clamp_result = False
        Make_Toon__Group__Mix_011.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_011.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_011.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_011.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_011.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_011.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_011.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_017 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_017.location = (6924.16, 15.01)
        Make_Toon__Group__Mix_017.hide = True
        Make_Toon__Group__Mix_017.data_type = 'RGBA'
        Make_Toon__Group__Mix_017.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_017.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_017.clamp_factor = True
        Make_Toon__Group__Mix_017.clamp_result = False
        Make_Toon__Group__Mix_017.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_017.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_017.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_017.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_017.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_017.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_017.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_017.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_017.inputs[6].default_value = (0.0, 0.0, 0.0, 1.0)
        Make_Toon__Group__Mix_017.inputs[7].default_value = 1.0

        Make_Toon__Group__Mix_016 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_016.location = (30.49, -35.62)
        Make_Toon__Group__Mix_016.label = 'Combine Emission'
        Make_Toon__Group__Mix_016.data_type = 'RGBA'
        Make_Toon__Group__Mix_016.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_016.blend_type = 'ADD'
        Make_Toon__Group__Mix_016.clamp_factor = True
        Make_Toon__Group__Mix_016.clamp_result = False
        Make_Toon__Group__Mix_016.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_016.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_016.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_016.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_016.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_016.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_016.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_016.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_010 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_010.location = (30.21, -35.62)
        Make_Toon__Group__Mix_010.data_type = 'RGBA'
        Make_Toon__Group__Mix_010.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_010.blend_type = 'ADD'
        Make_Toon__Group__Mix_010.clamp_factor = True
        Make_Toon__Group__Mix_010.clamp_result = False
        Make_Toon__Group__Mix_010.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_010.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_010.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_010.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_010.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_010.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_010.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_010.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Group_009 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_009.location = (29.5, -35.91)
        Make_Toon__Group__Group_009.node_tree = ensure_node_group('.lscherry.utils.ramp_style.Back Style')
        Make_Toon__Group__Group_009.inputs[4].default_value = 0.8999999761581421
        Make_Toon__Group__Group_009.inputs[5].default_value = 1.0
        Make_Toon__Group__Group_009.inputs[6].default_value = 0.75
        Make_Toon__Group__Group_009.inputs[7].default_value = 0.800000011920929
        Make_Toon__Group__Group_009.inputs[0].default_value = False
        Make_Toon__Group__Group_009.inputs[3].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_021 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_021.location = (649.76, 144.87)
        Make_Toon__Group__Mix_021.label = 'Pattern'
        Make_Toon__Group__Mix_021.hide = True
        Make_Toon__Group__Mix_021.data_type = 'RGBA'
        Make_Toon__Group__Mix_021.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_021.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_021.clamp_factor = True
        Make_Toon__Group__Mix_021.clamp_result = False
        Make_Toon__Group__Mix_021.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_021.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_021.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_021.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_021.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_021.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_021.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_021.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_021.inputs[7].default_value = (1.0, 1.0, 1.0, 1.0)

        Make_Toon__Group__Mix_023 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_023.location = (649.76, -136.39)
        Make_Toon__Group__Mix_023.label = 'Pattern'
        Make_Toon__Group__Mix_023.hide = True
        Make_Toon__Group__Mix_023.data_type = 'RGBA'
        Make_Toon__Group__Mix_023.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_023.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_023.clamp_factor = True
        Make_Toon__Group__Mix_023.clamp_result = False
        Make_Toon__Group__Mix_023.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_023.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_023.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_023.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_023.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_023.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_023.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_023.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_023.inputs[7].default_value = (1.0, 1.0, 1.0, 1.0)

        Make_Toon__Group__Mix_020 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_020.location = (374.91, -272.82)
        Make_Toon__Group__Mix_020.width = 100.0
        Make_Toon__Group__Mix_020.hide = True
        Make_Toon__Group__Mix_020.data_type = 'RGBA'
        Make_Toon__Group__Mix_020.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_020.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_020.clamp_factor = True
        Make_Toon__Group__Mix_020.clamp_result = False
        Make_Toon__Group__Mix_020.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_020.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_020.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_020.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_020.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_020.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_020.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Invert_Color_001 = nt.nodes.new('ShaderNodeInvert')
        Make_Toon__Group__Invert_Color_001.location = (374.91, -234.23)
        Make_Toon__Group__Invert_Color_001.width = 100.0
        Make_Toon__Group__Invert_Color_001.hide = True
        Make_Toon__Group__Invert_Color_001.inputs[0].default_value = 1.0

        Make_Toon__Group__Group_003 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_003.location = (570.2, -100.17)
        Make_Toon__Group__Group_003.width = 86.99
        Make_Toon__Group__Group_003.hide = True
        Make_Toon__Group__Group_003.node_tree = ensure_node_group('.lscherry.utils.bnodes.Blend It')
        Make_Toon__Group__Group_003.inputs[0].default_value = 1.0

        Make_Toon__Group__Group_019 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_019.location = (531.92, -814.68)
        Make_Toon__Group__Group_019.hide = True
        Make_Toon__Group__Group_019.node_tree = ensure_node_group('.lscherry.utils.bnodes.Value Enhance')

        Make_Toon__Group__Mix_018 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_018.location = (933.95, -203.87)
        Make_Toon__Group__Mix_018.data_type = 'RGBA'
        Make_Toon__Group__Mix_018.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_018.blend_type = 'MIX'
        Make_Toon__Group__Mix_018.clamp_factor = True
        Make_Toon__Group__Mix_018.clamp_result = False
        Make_Toon__Group__Mix_018.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_018.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_018.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_018.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_018.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_018.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_018.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Group_013 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_013.location = (243.53, -65.35)
        Make_Toon__Group__Group_013.node_tree = ensure_node_group('.lscherry.utils.ramp_style.Toon Style')
        Make_Toon__Group__Group_013.inputs[4].default_value = 0.8999999761581421
        Make_Toon__Group__Group_013.inputs[5].default_value = 0.10000000149011612
        Make_Toon__Group__Group_013.inputs[6].default_value = 0.0
        Make_Toon__Group__Group_013.inputs[7].default_value = 0.0
        Make_Toon__Group__Group_013.inputs[0].default_value = False
        Make_Toon__Group__Group_013.inputs[3].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Group_017 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_017.location = (30.2, -36.01)
        Make_Toon__Group__Group_017.node_tree = ensure_node_group('.lscherry.utils.ramp_style.SSS Style')
        Make_Toon__Group__Group_017.inputs[4].default_value = 0.15000000596046448
        Make_Toon__Group__Group_017.inputs[5].default_value = 5.0
        Make_Toon__Group__Group_017.inputs[0].default_value = False
        Make_Toon__Group__Group_017.inputs[3].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_007 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_007.location = (567.67, -411.49)
        Make_Toon__Group__Mix_007.label = 'Mix Custom And Dot'
        Make_Toon__Group__Mix_007.hide = True
        Make_Toon__Group__Mix_007.data_type = 'RGBA'
        Make_Toon__Group__Mix_007.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_007.blend_type = 'MIX'
        Make_Toon__Group__Mix_007.clamp_factor = True
        Make_Toon__Group__Mix_007.clamp_result = False
        Make_Toon__Group__Mix_007.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_007.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_007.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_007.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_007.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_007.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_007.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_007.inputs[0].default_value = True

        Make_Toon__Group__Vector_Math = nt.nodes.new('ShaderNodeVectorMath')
        Make_Toon__Group__Vector_Math.location = (252.78, -656.32)
        Make_Toon__Group__Vector_Math.hide = True
        Make_Toon__Group__Vector_Math.operation = 'LENGTH'
        Make_Toon__Group__Vector_Math.inputs[1].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Vector_Math.inputs[2].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Vector_Math.inputs[3].default_value = 1.0

        Make_Toon__Group__Mix_019 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_019.location = (548.13, -690.65)
        Make_Toon__Group__Mix_019.hide = True
        Make_Toon__Group__Mix_019.data_type = 'RGBA'
        Make_Toon__Group__Mix_019.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_019.blend_type = 'MIX'
        Make_Toon__Group__Mix_019.clamp_factor = True
        Make_Toon__Group__Mix_019.clamp_result = False
        Make_Toon__Group__Mix_019.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_019.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_019.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_019.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_019.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_019.inputs[6].default_value = (0.0, 0.0, 0.0, 1.0)
        Make_Toon__Group__Mix_019.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_019.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Group_012 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_012.location = (35.25, -271.43)
        Make_Toon__Group__Group_012.hide = True
        Make_Toon__Group__Group_012.node_tree = ensure_node_group('.lscherry.utils.normal.Use Default Normal')

        Make_Toon__Group__Group_008 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_008.location = (226.16, -363.65)
        Make_Toon__Group__Group_008.hide = True
        Make_Toon__Group__Group_008.node_tree = ensure_node_group('.lscherry.utils.procedural.Stylized Fresnel')
        Make_Toon__Group__Group_008.inputs[1].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_008.inputs[0].default_value = 0.10000000149011612

        Make_Toon__Group__Mix_024 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_024.location = (137.42, -44.62)
        Make_Toon__Group__Mix_024.hide = True
        Make_Toon__Group__Mix_024.data_type = 'RGBA'
        Make_Toon__Group__Mix_024.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_024.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_024.clamp_factor = True
        Make_Toon__Group__Mix_024.clamp_result = False
        Make_Toon__Group__Mix_024.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_024.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_024.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_024.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_024.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_024.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_024.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_024.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix.location = (197.14, -100.82)
        Make_Toon__Group__Mix.hide = True
        Make_Toon__Group__Mix.data_type = 'FLOAT'
        Make_Toon__Group__Mix.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix.blend_type = 'MIX'
        Make_Toon__Group__Mix.clamp_factor = True
        Make_Toon__Group__Mix.clamp_result = False
        Make_Toon__Group__Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix.inputs[3].default_value = 1.0
        Make_Toon__Group__Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix.inputs[6].default_value = (0.5, 0.5, 0.5, 1.0)
        Make_Toon__Group__Mix.inputs[7].default_value = (0.5, 0.5, 0.5, 1.0)
        Make_Toon__Group__Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Separate_Color = nt.nodes.new('ShaderNodeSeparateColor')
        Make_Toon__Group__Separate_Color.location = (197.14, -67.13)
        Make_Toon__Group__Separate_Color.hide = True
        Make_Toon__Group__Separate_Color.mode = 'HSV'

        Make_Toon__Group__Mix_025 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_025.location = (137.86, -45.07)
        Make_Toon__Group__Mix_025.hide = True
        Make_Toon__Group__Mix_025.data_type = 'RGBA'
        Make_Toon__Group__Mix_025.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_025.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_025.clamp_factor = True
        Make_Toon__Group__Mix_025.clamp_result = False
        Make_Toon__Group__Mix_025.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_025.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_025.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_025.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_025.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_025.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_025.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_025.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Separate_Color_001 = nt.nodes.new('ShaderNodeSeparateColor')
        Make_Toon__Group__Separate_Color_001.location = (39.12, -56.09)
        Make_Toon__Group__Separate_Color_001.hide = True
        Make_Toon__Group__Separate_Color_001.mode = 'HSV'

        Make_Toon__Group__Combine_Color = nt.nodes.new('ShaderNodeCombineColor')
        Make_Toon__Group__Combine_Color.location = (419.16, -59.56)
        Make_Toon__Group__Combine_Color.width = 100.0
        Make_Toon__Group__Combine_Color.hide = True
        Make_Toon__Group__Combine_Color.mode = 'HSV'

        Make_Toon__Group__Separate_Color_002 = nt.nodes.new('ShaderNodeSeparateColor')
        Make_Toon__Group__Separate_Color_002.location = (4456.6, -16.76)
        Make_Toon__Group__Separate_Color_002.hide = True
        Make_Toon__Group__Separate_Color_002.mode = 'HSV'

        Make_Toon__Group__Math_002 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Math_002.location = (198.16, -68.18)
        Make_Toon__Group__Math_002.width = 151.08
        Make_Toon__Group__Math_002.label = 'x1.2 (Up value 4toon)'
        Make_Toon__Group__Math_002.hide = True
        Make_Toon__Group__Math_002.operation = 'MULTIPLY'
        Make_Toon__Group__Math_002.use_clamp = False
        Make_Toon__Group__Math_002.inputs[1].default_value = 1.2000000476837158
        Make_Toon__Group__Math_002.inputs[2].default_value = 0.5

        Make_Toon__Group__Map_Range_001 = nt.nodes.new('ShaderNodeMapRange')
        Make_Toon__Group__Map_Range_001.location = (4456.6, -57.53)
        Make_Toon__Group__Map_Range_001.hide = True
        Make_Toon__Group__Map_Range_001.clamp = True
        Make_Toon__Group__Map_Range_001.interpolation_type = 'LINEAR'
        Make_Toon__Group__Map_Range_001.data_type = 'FLOAT'
        Make_Toon__Group__Map_Range_001.inputs[1].default_value = 0.0
        Make_Toon__Group__Map_Range_001.inputs[2].default_value = 1.0
        Make_Toon__Group__Map_Range_001.inputs[4].default_value = 1.0
        Make_Toon__Group__Map_Range_001.inputs[5].default_value = 4.0
        Make_Toon__Group__Map_Range_001.inputs[6].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range_001.inputs[7].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range_001.inputs[8].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Map_Range_001.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range_001.inputs[10].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Map_Range_001.inputs[11].default_value = (4.0, 4.0, 4.0)

        Make_Toon__Group__Value = nt.nodes.new('ShaderNodeValue')
        Make_Toon__Group__Value.location = (4287.1, -93.24)
        Make_Toon__Group__Value.label = 'Threshhold'
        Make_Toon__Group__Value.outputs[0].default_value = 0.75

        Make_Toon__Group__Math_004 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Math_004.location = (198.16, -102.71)
        Make_Toon__Group__Math_004.width = 100.0
        Make_Toon__Group__Math_004.hide = True
        Make_Toon__Group__Math_004.operation = 'MULTIPLY'
        Make_Toon__Group__Math_004.use_clamp = False
        Make_Toon__Group__Math_004.inputs[2].default_value = 0.5

        Make_Toon__Group__Mix_026 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_026.location = (933.95, -431.25)
        Make_Toon__Group__Mix_026.data_type = 'RGBA'
        Make_Toon__Group__Mix_026.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_026.blend_type = 'MIX'
        Make_Toon__Group__Mix_026.clamp_factor = True
        Make_Toon__Group__Mix_026.clamp_result = False
        Make_Toon__Group__Mix_026.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_026.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_026.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_026.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_026.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_026.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_026.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Math_005 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Math_005.location = (6137.7, -100.01)
        Make_Toon__Group__Math_005.hide = True
        Make_Toon__Group__Math_005.operation = 'MULTIPLY'
        Make_Toon__Group__Math_005.use_clamp = False
        Make_Toon__Group__Math_005.inputs[2].default_value = 0.5
        Make_Toon__Group__Math_005.inputs[0].default_value = 0.0

        Make_Toon__Group__Group_028 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_028.location = (249.09, -48.45)
        Make_Toon__Group__Group_028.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Make_Toon__Group__Group_028.inputs[0].default_value = True
        Make_Toon__Group__Group_028.inputs[2].default_value = 0.0

        Make_Toon__Group__Fresnel_003 = nt.nodes.new('ShaderNodeFresnel')
        Make_Toon__Group__Fresnel_003.location = (32.49, -245.44)
        Make_Toon__Group__Fresnel_003.inputs[1].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Mix_028 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Mix_028.location = (205.21, -151.69)
        Make_Toon__Group__Mix_028.data_type = 'RGBA'
        Make_Toon__Group__Mix_028.factor_mode = 'UNIFORM'
        Make_Toon__Group__Mix_028.blend_type = 'MULTIPLY'
        Make_Toon__Group__Mix_028.clamp_factor = True
        Make_Toon__Group__Mix_028.clamp_result = False
        Make_Toon__Group__Mix_028.inputs[0].default_value = 1.0
        Make_Toon__Group__Mix_028.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Mix_028.inputs[2].default_value = 0.0
        Make_Toon__Group__Mix_028.inputs[3].default_value = 0.0
        Make_Toon__Group__Mix_028.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_028.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_028.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Mix_028.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Map_Range_006 = nt.nodes.new('ShaderNodeMapRange')
        Make_Toon__Group__Map_Range_006.location = (30.47, -350.56)
        Make_Toon__Group__Map_Range_006.clamp = True
        Make_Toon__Group__Map_Range_006.interpolation_type = 'LINEAR'
        Make_Toon__Group__Map_Range_006.data_type = 'FLOAT'
        Make_Toon__Group__Map_Range_006.inputs[2].default_value = 1.0
        Make_Toon__Group__Map_Range_006.inputs[3].default_value = 0.0
        Make_Toon__Group__Map_Range_006.inputs[4].default_value = 1.0
        Make_Toon__Group__Map_Range_006.inputs[5].default_value = 4.0
        Make_Toon__Group__Map_Range_006.inputs[6].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range_006.inputs[7].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range_006.inputs[8].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Map_Range_006.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range_006.inputs[10].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Map_Range_006.inputs[11].default_value = (4.0, 4.0, 4.0)

        Make_Toon__Group__Map_Range_007 = nt.nodes.new('ShaderNodeMapRange')
        Make_Toon__Group__Map_Range_007.location = (372.73, -173.99)
        Make_Toon__Group__Map_Range_007.clamp = True
        Make_Toon__Group__Map_Range_007.interpolation_type = 'LINEAR'
        Make_Toon__Group__Map_Range_007.data_type = 'FLOAT'
        Make_Toon__Group__Map_Range_007.inputs[2].default_value = 0.10000000149011612
        Make_Toon__Group__Map_Range_007.inputs[3].default_value = 0.0
        Make_Toon__Group__Map_Range_007.inputs[5].default_value = 4.0
        Make_Toon__Group__Map_Range_007.inputs[6].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range_007.inputs[7].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range_007.inputs[8].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Map_Range_007.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range_007.inputs[10].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Map_Range_007.inputs[11].default_value = (4.0, 4.0, 4.0)
        Make_Toon__Group__Map_Range_007.inputs[4].default_value = 0.5

        Make_Toon__Group__Math_006 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Math_006.location = (36.22, -209.12)
        Make_Toon__Group__Math_006.hide = True
        Make_Toon__Group__Math_006.operation = 'MULTIPLY'
        Make_Toon__Group__Math_006.use_clamp = False
        Make_Toon__Group__Math_006.inputs[1].default_value = -1.0
        Make_Toon__Group__Math_006.inputs[2].default_value = 0.5
        Make_Toon__Group__Math_006.inputs[0].default_value = 0.30000001192092896

        Make_Toon__Group__Math_007 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Math_007.location = (366.6, -136.97)
        Make_Toon__Group__Math_007.hide = True
        Make_Toon__Group__Math_007.operation = 'DIVIDE'
        Make_Toon__Group__Math_007.use_clamp = False
        Make_Toon__Group__Math_007.inputs[1].default_value = 10.0
        Make_Toon__Group__Math_007.inputs[2].default_value = 0.5
        Make_Toon__Group__Math_007.inputs[0].default_value = 0.5

        Make_Toon__Group__Map_Range = nt.nodes.new('ShaderNodeMapRange')
        Make_Toon__Group__Map_Range.location = (35.77, -158.36)
        Make_Toon__Group__Map_Range.hide = True
        Make_Toon__Group__Map_Range.clamp = True
        Make_Toon__Group__Map_Range.interpolation_type = 'LINEAR'
        Make_Toon__Group__Map_Range.data_type = 'FLOAT'
        Make_Toon__Group__Map_Range.inputs[1].default_value = 0.0
        Make_Toon__Group__Map_Range.inputs[2].default_value = 1.0
        Make_Toon__Group__Map_Range.inputs[3].default_value = 1.0010000467300415
        Make_Toon__Group__Map_Range.inputs[4].default_value = 1.5
        Make_Toon__Group__Map_Range.inputs[5].default_value = 4.0
        Make_Toon__Group__Map_Range.inputs[6].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range.inputs[7].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range.inputs[8].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Map_Range.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Map_Range.inputs[10].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Map_Range.inputs[11].default_value = (4.0, 4.0, 4.0)
        Make_Toon__Group__Map_Range.inputs[0].default_value = 0.30000001192092896

        Make_Toon__Group__Group_023__Attribute_004 = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_023__Attribute_004.location = (23.57, -151.28)
        Make_Toon__Group__Group_023__Attribute_004.label = 'Value Enhance'
        Make_Toon__Group__Group_023__Attribute_004.hide = True
        Make_Toon__Group__Group_023__Attribute_004.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_023__Attribute_004.attribute_name = 'valEnh'

        Make_Toon__Group__Group_023__Attribute_005 = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_023__Attribute_005.location = (-258.41, -292.87)
        Make_Toon__Group__Group_023__Attribute_005.label = 'World Color'
        Make_Toon__Group__Group_023__Attribute_005.hide = True
        Make_Toon__Group__Group_023__Attribute_005.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_023__Attribute_005.attribute_name = 'wCol'

        Make_Toon__Group__Group_023__Group = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_023__Group.location = (-427.83, -276.72)
        Make_Toon__Group__Group_023__Group.hide = True
        Make_Toon__Group__Group_023__Group.node_tree = ensure_node_group('.lscherry.utils.bnodes.Background Color')

        Make_Toon__Group__Group_023__Mix_003 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Group_023__Mix_003.location = (-253.24, -253.39)
        Make_Toon__Group__Group_023__Mix_003.hide = True
        Make_Toon__Group__Group_023__Mix_003.data_type = 'RGBA'
        Make_Toon__Group__Group_023__Mix_003.factor_mode = 'UNIFORM'
        Make_Toon__Group__Group_023__Mix_003.blend_type = 'ADD'
        Make_Toon__Group__Group_023__Mix_003.clamp_factor = True
        Make_Toon__Group__Group_023__Mix_003.clamp_result = False
        Make_Toon__Group__Group_023__Mix_003.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Group_023__Mix_003.inputs[2].default_value = 0.0
        Make_Toon__Group__Group_023__Mix_003.inputs[3].default_value = 0.0
        Make_Toon__Group__Group_023__Mix_003.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_023__Mix_003.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_023__Mix_003.inputs[7].default_value = (1.0, 1.0, 1.0, 1.0)
        Make_Toon__Group__Group_023__Mix_003.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_023__Mix_003.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Group_023__Attribute_006 = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_023__Attribute_006.location = (-430.35, -239.75)
        Make_Toon__Group__Group_023__Attribute_006.label = 'World Value Enhance'
        Make_Toon__Group__Group_023__Attribute_006.hide = True
        Make_Toon__Group__Group_023__Attribute_006.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_023__Attribute_006.attribute_name = 'wValEnh'

        Make_Toon__Group__Group_023__Mix_007 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Group_023__Mix_007.location = (24.55, -244.4)
        Make_Toon__Group__Group_023__Mix_007.hide = True
        Make_Toon__Group__Group_023__Mix_007.data_type = 'RGBA'
        Make_Toon__Group__Group_023__Mix_007.factor_mode = 'UNIFORM'
        Make_Toon__Group__Group_023__Mix_007.blend_type = 'MIX'
        Make_Toon__Group__Group_023__Mix_007.clamp_factor = True
        Make_Toon__Group__Group_023__Mix_007.clamp_result = False
        Make_Toon__Group__Group_023__Mix_007.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Group_023__Mix_007.inputs[2].default_value = 0.0
        Make_Toon__Group__Group_023__Mix_007.inputs[3].default_value = 0.0
        Make_Toon__Group__Group_023__Mix_007.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_023__Mix_007.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_023__Mix_007.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_023__Mix_007.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Group_023__Attribute_008 = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_023__Attribute_008.location = (-844.8, -123.71)
        Make_Toon__Group__Group_023__Attribute_008.label = 'Blend Mode'
        Make_Toon__Group__Group_023__Attribute_008.hide = True
        Make_Toon__Group__Group_023__Attribute_008.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_023__Attribute_008.attribute_name = 'blendM'

        Make_Toon__Group__Group_023__Math = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Group_023__Math.location = (-608.11, -168.08)
        Make_Toon__Group__Group_023__Math.label = 'Light Sources'
        Make_Toon__Group__Group_023__Math.hide = True
        Make_Toon__Group__Group_023__Math.operation = 'COMPARE'
        Make_Toon__Group__Group_023__Math.use_clamp = False
        Make_Toon__Group__Group_023__Math.inputs[1].default_value = 1.0
        Make_Toon__Group__Group_023__Math.inputs[2].default_value = 0.0

        Make_Toon__Group__Group_023__Math_001 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Group_023__Math_001.location = (-608.32, -129.77)
        Make_Toon__Group__Group_023__Math_001.label = 'Background'
        Make_Toon__Group__Group_023__Math_001.hide = True
        Make_Toon__Group__Group_023__Math_001.operation = 'COMPARE'
        Make_Toon__Group__Group_023__Math_001.use_clamp = False
        Make_Toon__Group__Group_023__Math_001.inputs[1].default_value = 2.0
        Make_Toon__Group__Group_023__Math_001.inputs[2].default_value = 0.0

        Make_Toon__Group__Group_023__Math_002 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Group_023__Math_002.location = (-608.11, -92.43)
        Make_Toon__Group__Group_023__Math_002.label = 'None'
        Make_Toon__Group__Group_023__Math_002.hide = True
        Make_Toon__Group__Group_023__Math_002.operation = 'COMPARE'
        Make_Toon__Group__Group_023__Math_002.use_clamp = False
        Make_Toon__Group__Group_023__Math_002.inputs[1].default_value = 3.0
        Make_Toon__Group__Group_023__Math_002.inputs[2].default_value = 0.0

        Make_Toon__Group__Group_023__Math_003 = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Group_023__Math_003.location = (-268.37, -94.07)
        Make_Toon__Group__Group_023__Math_003.hide = True
        Make_Toon__Group__Group_023__Math_003.operation = 'SUBTRACT'
        Make_Toon__Group__Group_023__Math_003.use_clamp = False
        Make_Toon__Group__Group_023__Math_003.inputs[0].default_value = 1.0
        Make_Toon__Group__Group_023__Math_003.inputs[2].default_value = 0.5

        Make_Toon__Group__Group_018__Mix_004 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Group_018__Mix_004.location = (695.77, 207.06)
        Make_Toon__Group__Group_018__Mix_004.data_type = 'RGBA'
        Make_Toon__Group__Group_018__Mix_004.factor_mode = 'UNIFORM'
        Make_Toon__Group__Group_018__Mix_004.blend_type = 'ADD'
        Make_Toon__Group__Group_018__Mix_004.clamp_factor = True
        Make_Toon__Group__Group_018__Mix_004.clamp_result = False
        Make_Toon__Group__Group_018__Mix_004.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Group_018__Mix_004.inputs[2].default_value = 0.0
        Make_Toon__Group__Group_018__Mix_004.inputs[3].default_value = 0.0
        Make_Toon__Group__Group_018__Mix_004.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Mix_004.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Mix_004.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Mix_004.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Mix_004.inputs[7].default_value = (1.0, 1.0, 1.0, 1.0)

        Make_Toon__Group__Group_018__Mix_005 = nt.nodes.new('ShaderNodeMix')
        Make_Toon__Group__Group_018__Mix_005.location = (870.91, 404.94)
        Make_Toon__Group__Group_018__Mix_005.data_type = 'RGBA'
        Make_Toon__Group__Group_018__Mix_005.factor_mode = 'UNIFORM'
        Make_Toon__Group__Group_018__Mix_005.blend_type = 'MIX'
        Make_Toon__Group__Group_018__Mix_005.clamp_factor = True
        Make_Toon__Group__Group_018__Mix_005.clamp_result = False
        Make_Toon__Group__Group_018__Mix_005.inputs[1].default_value = (0.5, 0.5, 0.5)
        Make_Toon__Group__Group_018__Mix_005.inputs[2].default_value = 0.0
        Make_Toon__Group__Group_018__Mix_005.inputs[3].default_value = 0.0
        Make_Toon__Group__Group_018__Mix_005.inputs[4].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Mix_005.inputs[5].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Mix_005.inputs[8].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Mix_005.inputs[9].default_value = (0.0, 0.0, 0.0)

        Make_Toon__Group__Group_018__Group = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_018__Group.location = (15.26, -33.57)
        Make_Toon__Group__Group_018__Group.node_tree = ensure_node_group('.lscherry.utils.normal.Use Default Normal')

        Make_Toon__Group__Group_018__Group_004 = nt.nodes.new('ShaderNodeGroup')
        Make_Toon__Group__Group_018__Group_004.location = (207.59, 95.91)
        Make_Toon__Group__Group_018__Group_004.node_tree = ensure_node_group('.lscherry.core.Specular Dot')

        Make_Toon__Group__Group_018__Attribute = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_018__Attribute.location = (15.26, 89.44)
        Make_Toon__Group__Group_018__Attribute.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_018__Attribute.attribute_name = 'm'

        Make_Toon__Group__Group_018__Map_Range_001 = nt.nodes.new('ShaderNodeMapRange')
        Make_Toon__Group__Group_018__Map_Range_001.location = (394.48, 119.25)
        Make_Toon__Group__Group_018__Map_Range_001.clamp = True
        Make_Toon__Group__Group_018__Map_Range_001.interpolation_type = 'LINEAR'
        Make_Toon__Group__Group_018__Map_Range_001.data_type = 'FLOAT'
        Make_Toon__Group__Group_018__Map_Range_001.inputs[2].default_value = 1.0
        Make_Toon__Group__Group_018__Map_Range_001.inputs[3].default_value = 0.0
        Make_Toon__Group__Group_018__Map_Range_001.inputs[4].default_value = 1.0
        Make_Toon__Group__Group_018__Map_Range_001.inputs[5].default_value = 4.0
        Make_Toon__Group__Group_018__Map_Range_001.inputs[6].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Map_Range_001.inputs[7].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Map_Range_001.inputs[8].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Group_018__Map_Range_001.inputs[9].default_value = (0.0, 0.0, 0.0)
        Make_Toon__Group__Group_018__Map_Range_001.inputs[10].default_value = (1.0, 1.0, 1.0)
        Make_Toon__Group__Group_018__Map_Range_001.inputs[11].default_value = (4.0, 4.0, 4.0)

        Make_Toon__Group__Group_018__Math = nt.nodes.new('ShaderNodeMath')
        Make_Toon__Group__Group_018__Math.location = (207.23, -30.13)
        Make_Toon__Group__Group_018__Math.operation = 'SUBTRACT'
        Make_Toon__Group__Group_018__Math.use_clamp = False
        Make_Toon__Group__Group_018__Math.inputs[0].default_value = 1.0
        Make_Toon__Group__Group_018__Math.inputs[2].default_value = 0.5
        Make_Toon__Group__Group_018__Math.inputs[1].default_value = 0.10000000149011612

        Make_Toon__Group__Group_025__Attribute_001 = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_025__Attribute_001.location = (0.0, -123.16)
        Make_Toon__Group__Group_025__Attribute_001.hide = True
        Make_Toon__Group__Group_025__Attribute_001.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_025__Attribute_001.attribute_name = 'tn'

        Make_Toon__Group__Group_025__Attribute_002 = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_025__Attribute_002.location = (0.0, 22.36)
        Make_Toon__Group__Group_025__Attribute_002.hide = True
        Make_Toon__Group__Group_025__Attribute_002.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_025__Attribute_002.attribute_name = 'm'

        Make_Toon__Group__Group_025__Attribute_003 = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_025__Attribute_003.location = (0.0, -13.01)
        Make_Toon__Group__Group_025__Attribute_003.hide = True
        Make_Toon__Group__Group_025__Attribute_003.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_025__Attribute_003.attribute_name = 'b'

        Make_Toon__Group__Group_025__Attribute_004 = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_025__Attribute_004.location = (0.0, -49.85)
        Make_Toon__Group__Group_025__Attribute_004.hide = True
        Make_Toon__Group__Group_025__Attribute_004.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_025__Attribute_004.attribute_name = 'fx'

        Make_Toon__Group__Group_025__Attribute_005 = nt.nodes.new('ShaderNodeAttribute')
        Make_Toon__Group__Group_025__Attribute_005.location = (0.0, -85.91)
        Make_Toon__Group__Group_025__Attribute_005.hide = True
        Make_Toon__Group__Group_025__Attribute_005.attribute_type = 'GEOMETRY'
        Make_Toon__Group__Group_025__Attribute_005.attribute_name = 'fy'


        nt.links.new(Texture_Coordinate.outputs['UV'], Mapping.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture.inputs['Vector'])
        nt.links.new(Image_Texture_001.outputs['Color'], lscherry_utils_procedural_Build_Face_Ramp.inputs['Face Map'])
        nt.links.new(Face_Ramp_Builder__Map_Range.outputs['Result'], lscherry_utils_procedural_Build_Face_Ramp.inputs['Face Value'])
        nt.links.new(Face_Ramp_Builder__Mapping.outputs['Vector'], Image_Texture_001.inputs['Vector'])
        nt.links.new(Face_Ramp_Builder__Group_002.outputs['Oxy'], Face_Ramp_Builder__Vector_Math.inputs[0])
        nt.links.new(Face_Ramp_Builder__Vector_Math.outputs['Vector'], Face_Ramp_Builder__Vector_Math_004.inputs[0])
        nt.links.new(Mapping.outputs['Vector'], Face_Ramp_Builder__Mapping.inputs['Vector'])
        nt.links.new(Face_Ramp_Builder__Mix.outputs[1], Face_Ramp_Builder__Mapping.inputs['Scale'])
        nt.links.new(Face_Ramp_Builder__Math.outputs['Value'], Face_Ramp_Builder__Mix.inputs[0])
        nt.links.new(Face_Ramp_Builder__Combine_XYZ.outputs['Vector'], Face_Ramp_Builder__Mix.inputs[4])
        nt.links.new(Face_Ramp_Builder__Combine_XYZ_001.outputs['Vector'], Face_Ramp_Builder__Mix.inputs[5])
        nt.links.new(Face_Ramp_Builder__Group_001.outputs['Main Light Vector'], Face_Ramp_Builder__Group_002.inputs['Oxyz'])
        nt.links.new(Face_Ramp_Builder__Vector_Math_003.outputs['Value'], Face_Ramp_Builder__Map_Range.inputs['Value'])
        nt.links.new(Face_Ramp_Builder__Vector_Math.outputs['Vector'], Face_Ramp_Builder__Vector_Math_003.inputs[0])
        nt.links.new(Face_Ramp_Builder__Vector_Math_004.outputs['Value'], Face_Ramp_Builder__Math.inputs[0])
        nt.links.new(Face_Ramp_Builder__Attribute_002.outputs['Vector'], Face_Ramp_Builder__Group_001.inputs['Light Dir'])
        nt.links.new(Face_Ramp_Builder__Geometry.outputs['Normal'], Face_Ramp_Builder__Group_001.inputs['Normal'])
        nt.links.new(Face_Ramp_Builder__Map_Range.outputs['Result'], Face_Ramp_Builder__Math_003.inputs[0])
        nt.links.new(Group_Input.outputs['Alpha'], Make_Toon__Group_004.inputs['Alpha'])
        nt.links.new(Make_Toon__Group_004.outputs['Shader'], Group_Output.inputs['Shader'])
        nt.links.new(Make_Toon__Group_004.outputs['To AgX'], Group_Output.inputs['To AgrX'])
        nt.links.new(Face_Ramp_Builder__Group__Vector_Math_002.outputs['Vector'], Face_Ramp_Builder__Vector_Math_004.inputs[1])
        nt.links.new(Face_Ramp_Builder__Group__Vector_Math_001.outputs['Vector'], Face_Ramp_Builder__Vector_Math_003.inputs[1])
        nt.links.new(Face_Ramp_Builder__Group__Attribute_001.outputs['Vector'], Face_Ramp_Builder__Group__Group_004.inputs['Oxyz'])
        nt.links.new(Face_Ramp_Builder__Group__Attribute.outputs['Vector'], Face_Ramp_Builder__Group__Group_003.inputs['Oxyz'])
        nt.links.new(Face_Ramp_Builder__Group__Group_004.outputs['Oxy'], Face_Ramp_Builder__Group__Vector_Math_002.inputs[0])
        nt.links.new(Face_Ramp_Builder__Group__Group_003.outputs['Oxy'], Face_Ramp_Builder__Group__Vector_Math_001.inputs[0])
        nt.links.new(Make_Toon__Group__Group_012.outputs['Normal'], Make_Toon__Group__Group_004.inputs['Normal'])
        nt.links.new(Make_Toon__Group__Group_012.outputs['Normal'], Make_Toon__Group__Group_002.inputs['Normal'])
        nt.links.new(Make_Toon__Group__Group_012.outputs['Normal'], Make_Toon__Group__Group_001.inputs['Normal'])
        nt.links.new(Make_Toon__Group__Mix_016.outputs[2], Make_Toon__Group_004.inputs['Combined'])
        nt.links.new(Make_Toon__Group__Mix_016.outputs[2], Group_Output.inputs['Combined'])
        nt.links.new(Make_Toon__Group__Group_002.outputs['NdotL'], Group_Output.inputs['Diffuse Mask'])
        nt.links.new(Image_Texture.outputs['Color'], Make_Toon__Group__Group_027.inputs['Limit Color'])
        nt.links.new(Make_Toon__Group__Mix_025.outputs[2], Make_Toon__Group__Mix_008.inputs[6])
        nt.links.new(Make_Toon__Group__Group_027.outputs['Limited Color'], Make_Toon__Group__Mix_008.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_024.outputs[2], Make_Toon__Group__Mix_006.inputs[6])
        nt.links.new(Make_Toon__Group__Group_026.outputs['Limited Color'], Make_Toon__Group__Mix_006.inputs[7])
        nt.links.new(Group_Input.outputs['SSS Color'], Make_Toon__Group__Group_026.inputs['Target Color'])
        nt.links.new(Image_Texture.outputs['Color'], Make_Toon__Group__Group_026.inputs['Limit Color'])
        nt.links.new(Make_Toon__Group__Group_019.outputs['Enhanced Shading'], Make_Toon__Group__Mix_001.inputs[0])
        nt.links.new(Make_Toon__Group__Mix_002.outputs[2], Make_Toon__Group__Mix_001.inputs[6])
        nt.links.new(Make_Toon__Group__Mix_004.outputs[2], Make_Toon__Group__Mix_001.inputs[7])
        nt.links.new(Make_Toon__Group__Group_019.outputs['Enhanced Shading'], Make_Toon__Group__Mix_004.inputs[6])
        nt.links.new(Image_Texture.outputs['Color'], Make_Toon__Group__Mix_004.inputs[7])
        nt.links.new(Make_Toon__Group__Group_019.outputs['Enhanced Shading'], Make_Toon__Group__Invert_Color.inputs['Color'])
        nt.links.new(Make_Toon__Group__Map_Range_007.outputs['Result'], Make_Toon__Group__Mix_005.inputs[6])
        nt.links.new(Make_Toon__Group__Invert_Color.outputs['Color'], Make_Toon__Group__Mix_002.inputs[0])
        nt.links.new(Image_Texture.outputs['Color'], Make_Toon__Group__Mix_002.inputs[6])
        nt.links.new(Group_Input.outputs['Shadow Color'], Make_Toon__Group__Mix_002.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_005.outputs[2], Make_Toon__Group__Mix_015.inputs[6])
        nt.links.new(Make_Toon__Group__Map_Range_001.outputs['Result'], Make_Toon__Group__Mix_015.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_018.outputs[2], Make_Toon__Group__Mix_012.inputs[6])
        nt.links.new(Make_Toon__Group__Map_Range_001.outputs['Result'], Make_Toon__Group__Mix_012.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_006.outputs[2], Make_Toon__Group__Mix_013.inputs[6])
        nt.links.new(Make_Toon__Group__Map_Range_001.outputs['Result'], Make_Toon__Group__Mix_013.inputs[7])
        nt.links.new(Make_Toon__Group__Group_017.outputs['Shading'], Make_Toon__Group__Math.inputs[0])
        nt.links.new(Make_Toon__Group__Math_001.outputs['Value'], Make_Toon__Group__Math_003.inputs[0])
        nt.links.new(Make_Toon__Group__Math.outputs['Value'], Make_Toon__Group__Math_003.inputs[1])
        nt.links.new(Make_Toon__Group__Map_Range_001.outputs['Result'], Make_Toon__Group__Mix_014.inputs[6])
        nt.links.new(Make_Toon__Group__Mix_008.outputs[2], Make_Toon__Group__Mix_014.inputs[7])
        nt.links.new(Make_Toon__Group__Math_003.outputs['Value'], Make_Toon__Group__Mix_009.inputs[0])
        nt.links.new(Make_Toon__Group__Mix_012.outputs[2], Make_Toon__Group__Mix_009.inputs[6])
        nt.links.new(Make_Toon__Group__Mix_013.outputs[2], Make_Toon__Group__Mix_009.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_009.outputs[2], Make_Toon__Group__Mix_011.inputs[6])
        nt.links.new(Make_Toon__Group__Mix_014.outputs[2], Make_Toon__Group__Mix_011.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_010.outputs[2], Make_Toon__Group__Mix_016.inputs[6])
        nt.links.new(Make_Toon__Group__Mix_017.outputs[2], Make_Toon__Group__Mix_016.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_015.outputs[2], Make_Toon__Group__Mix_010.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_023.outputs[2], Make_Toon__Group__Group_009.inputs['Shading'])
        nt.links.new(Make_Toon__Group__Group_008.outputs['Fresnel'], Make_Toon__Group__Group_009.inputs['Fresnel (Required)'])
        nt.links.new(Make_Toon__Group__Mix_007.outputs[2], Make_Toon__Group__Mix_021.inputs[6])
        nt.links.new(Make_Toon__Group__Mix_019.outputs[2], Make_Toon__Group__Mix_023.inputs[6])
        nt.links.new(Make_Toon__Group__Invert_Color_001.outputs['Color'], Make_Toon__Group__Mix_020.inputs[0])
        nt.links.new(Image_Texture.outputs['Color'], Make_Toon__Group__Mix_020.inputs[6])
        nt.links.new(Group_Input.outputs['Shadow Color'], Make_Toon__Group__Mix_020.inputs[7])
        nt.links.new(Make_Toon__Group__Group_019.outputs['Enhanced Shading'], Make_Toon__Group__Invert_Color_001.inputs['Color'])
        nt.links.new(Make_Toon__Group__Mix_020.outputs[2], Make_Toon__Group__Group_003.inputs['Color A'])
        nt.links.new(Make_Toon__Group__Combine_Color.outputs['Color'], Make_Toon__Group__Group_003.inputs['Color B'])
        nt.links.new(Make_Toon__Group__Group_013.outputs['Shading'], Make_Toon__Group__Group_019.inputs['Shading'])
        nt.links.new(Make_Toon__Group__Group_003.outputs['Color'], Make_Toon__Group__Mix_018.inputs[6])
        nt.links.new(Make_Toon__Group__Mix_001.outputs[2], Make_Toon__Group__Mix_018.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_021.outputs[2], Make_Toon__Group__Group_013.inputs['Shading'])
        nt.links.new(Make_Toon__Group__Group_008.outputs['Fresnel'], Make_Toon__Group__Group_013.inputs['Fresnel (Required)'])
        nt.links.new(Make_Toon__Group__Mix_021.outputs[2], Make_Toon__Group__Group_017.inputs['Shading'])
        nt.links.new(Make_Toon__Group__Group_013.outputs['Toon Style'], Make_Toon__Group__Group_017.inputs['Toon Style (If only using Toon Style)'])
        nt.links.new(Make_Toon__Group__Group_002.outputs['NdotL'], Make_Toon__Group__Mix_007.inputs[6])
        nt.links.new(lscherry_utils_procedural_Build_Face_Ramp.outputs['Custom Ramp'], Make_Toon__Group__Mix_007.inputs[7])
        nt.links.new(Make_Toon__Group__Vector_Math.outputs['Value'], Make_Toon__Group__Mix_019.inputs[0])
        nt.links.new(Make_Toon__Group__Group_004.outputs['NdotL'], Make_Toon__Group__Mix_019.inputs[7])
        nt.links.new(Group_Input.outputs['Normal'], Make_Toon__Group__Group_012.inputs['Normal'])
        nt.links.new(Make_Toon__Group__Group_017.outputs['Shading'], Make_Toon__Group__Mix_024.inputs[6])
        nt.links.new(Make_Toon__Group__Mix.outputs[0], Make_Toon__Group__Mix_024.inputs[7])
        nt.links.new(Make_Toon__Group__Separate_Color.outputs['Blue'], Make_Toon__Group__Mix.inputs[2])
        nt.links.new(Make_Toon__Group__Group_001.outputs['Toon'], Make_Toon__Group__Separate_Color.inputs['Color'])
        nt.links.new(Make_Toon__Group__Group_009.outputs['Shading'], Make_Toon__Group__Mix_025.inputs[6])
        nt.links.new(Make_Toon__Group__Mix.outputs[0], Make_Toon__Group__Mix_025.inputs[7])
        nt.links.new(Make_Toon__Group__Group_001.outputs['Toon'], Make_Toon__Group__Separate_Color_001.inputs['Color'])
        nt.links.new(Make_Toon__Group__Separate_Color_001.outputs['Red'], Make_Toon__Group__Combine_Color.inputs['Red'])
        nt.links.new(Make_Toon__Group__Math_002.outputs['Value'], Make_Toon__Group__Combine_Color.inputs['Green'])
        nt.links.new(Make_Toon__Group__Math_004.outputs['Value'], Make_Toon__Group__Combine_Color.inputs['Blue'])
        nt.links.new(Make_Toon__Group__Separate_Color_001.outputs['Green'], Make_Toon__Group__Math_002.inputs[0])
        nt.links.new(Make_Toon__Group__Separate_Color_002.outputs['Blue'], Make_Toon__Group__Map_Range_001.inputs['Value'])
        nt.links.new(Make_Toon__Group__Value.outputs['Value'], Make_Toon__Group__Map_Range_001.inputs[3])
        nt.links.new(Make_Toon__Group__Separate_Color_001.outputs['Blue'], Make_Toon__Group__Math_004.inputs[0])
        nt.links.new(Make_Toon__Group__Group_019.outputs['Enhanced Shading'], Make_Toon__Group__Math_004.inputs[1])
        nt.links.new(Make_Toon__Group__Math_004.outputs['Value'], Make_Toon__Group__Mix_026.inputs[6])
        nt.links.new(Make_Toon__Group__Group_019.outputs['Enhanced Shading'], Make_Toon__Group__Mix_026.inputs[7])
        nt.links.new(Make_Toon__Group__Mix_026.outputs[2], Make_Toon__Group__Math_005.inputs[1])
        nt.links.new(Make_Toon__Group__Group_012.outputs['Normal'], Make_Toon__Group__Group_028.inputs['Normal'])
        nt.links.new(Make_Toon__Group__Map_Range.outputs['Result'], Make_Toon__Group__Fresnel_003.inputs['IOR'])
        nt.links.new(Make_Toon__Group__Fresnel_003.outputs['Factor'], Make_Toon__Group__Mix_028.inputs[6])
        nt.links.new(Make_Toon__Group__Map_Range_006.outputs['Result'], Make_Toon__Group__Mix_028.inputs[7])
        nt.links.new(Make_Toon__Group__Group_028.outputs['NdotL'], Make_Toon__Group__Map_Range_006.inputs['Value'])
        nt.links.new(Make_Toon__Group__Math_006.outputs['Value'], Make_Toon__Group__Map_Range_006.inputs[1])
        nt.links.new(Make_Toon__Group__Mix_028.outputs[2], Make_Toon__Group__Map_Range_007.inputs['Value'])
        nt.links.new(Make_Toon__Group__Math_007.outputs['Value'], Make_Toon__Group__Map_Range_007.inputs[1])
        nt.links.new(Make_Toon__Group__Group_023__Math_003.outputs['Value'], Make_Toon__Group__Mix_011.inputs[0])
        nt.links.new(Make_Toon__Group__Group_023__Math_003.outputs['Value'], Make_Toon__Group__Mix_018.inputs[0])
        nt.links.new(Make_Toon__Group__Group_023__Math_003.outputs['Value'], Make_Toon__Group__Mix.inputs[0])
        nt.links.new(Make_Toon__Group__Group_023__Math_003.outputs['Value'], Make_Toon__Group__Mix_026.inputs[0])
        nt.links.new(Make_Toon__Group__Group_023__Attribute_004.outputs['Factor'], Make_Toon__Group__Group_019.inputs['Value Enhance'])
        nt.links.new(Make_Toon__Group__Group_023__Mix_007.outputs[2], Make_Toon__Group__Separate_Color_002.inputs['Color'])
        nt.links.new(Make_Toon__Group__Group_023__Attribute_006.outputs['Factor'], Make_Toon__Group__Group_023__Mix_003.inputs[0])
        nt.links.new(Make_Toon__Group__Group_023__Group.outputs['Stylized'], Make_Toon__Group__Group_023__Mix_003.inputs[6])
        nt.links.new(Make_Toon__Group__Group_023__Math_002.outputs['Value'], Make_Toon__Group__Group_023__Mix_007.inputs[0])
        nt.links.new(Make_Toon__Group__Group_023__Mix_003.outputs[2], Make_Toon__Group__Group_023__Mix_007.inputs[6])
        nt.links.new(Make_Toon__Group__Group_023__Attribute_005.outputs['Color'], Make_Toon__Group__Group_023__Mix_007.inputs[7])
        nt.links.new(Make_Toon__Group__Group_023__Attribute_008.outputs['Factor'], Make_Toon__Group__Group_023__Math.inputs[0])
        nt.links.new(Make_Toon__Group__Group_023__Attribute_008.outputs['Factor'], Make_Toon__Group__Group_023__Math_001.inputs[0])
        nt.links.new(Make_Toon__Group__Group_023__Attribute_008.outputs['Factor'], Make_Toon__Group__Group_023__Math_002.inputs[0])
        nt.links.new(Make_Toon__Group__Group_023__Math.outputs['Value'], Make_Toon__Group__Group_023__Math_003.inputs[1])
        nt.links.new(Make_Toon__Group__Group_018__Mix_005.outputs[2], Make_Toon__Group__Mix_010.inputs[6])
        nt.links.new(Make_Toon__Group__Group_018__Map_Range_001.outputs['Result'], Make_Toon__Group__Group_018__Mix_004.inputs[0])
        nt.links.new(Make_Toon__Group__Mix_011.outputs[2], Make_Toon__Group__Group_018__Mix_004.inputs[6])
        nt.links.new(Make_Toon__Group__Math_005.outputs['Value'], Make_Toon__Group__Group_018__Mix_005.inputs[0])
        nt.links.new(Make_Toon__Group__Mix_011.outputs[2], Make_Toon__Group__Group_018__Mix_005.inputs[6])
        nt.links.new(Make_Toon__Group__Group_018__Mix_004.outputs[2], Make_Toon__Group__Group_018__Mix_005.inputs[7])
        nt.links.new(Group_Input.outputs['Normal'], Make_Toon__Group__Group_018__Group.inputs['Normal'])
        nt.links.new(Make_Toon__Group__Group_018__Attribute.outputs['Vector'], Make_Toon__Group__Group_018__Group_004.inputs['Light Dir'])
        nt.links.new(Make_Toon__Group__Group_018__Group.outputs['Normal'], Make_Toon__Group__Group_018__Group_004.inputs['Normal'])
        nt.links.new(Make_Toon__Group__Group_018__Group_004.outputs['Specular'], Make_Toon__Group__Group_018__Map_Range_001.inputs['Value'])
        nt.links.new(Make_Toon__Group__Group_018__Math.outputs['Value'], Make_Toon__Group__Group_018__Map_Range_001.inputs[1])
        nt.links.new(Make_Toon__Group__Group_025__Attribute_002.outputs['Vector'], Make_Toon__Group__Group_002.inputs['Light Dir'])
        nt.links.new(Make_Toon__Group__Group_025__Attribute_002.outputs['Vector'], Make_Toon__Group__Group_028.inputs['Light Dir'])
        nt.links.new(Make_Toon__Group__Group_025__Attribute_003.outputs['Vector'], Make_Toon__Group__Group_004.inputs['Light Dir'])
        nt.links.new(Make_Toon__Group__Group_025__Attribute_003.outputs['Vector'], Make_Toon__Group__Vector_Math.inputs[0])
        self.valuesUpdate(None)

    def valuesUpdate(self, context):
        if context is not None and self.node_tree.users > 1:
            self.node_tree = self.node_tree.copy()
        _placeholder_images = {'Image Texture': 'image_face_d_texture', 'Image Texture.001': 'image_sdf_texture'}
        for node in self.node_tree.nodes:
            if node.type == "TEX_IMAGE" and node.name in _placeholder_images:
                node.image = getattr(self, _placeholder_images[node.name])
