# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ....node import ShaderNode


class ShaderNodeCompiled_Rim_Core(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Rim_Core'
    bl_label = 'lscherry.core.Rim Core'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Rim Core'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Rim Strength'].default_value = 0.0
        self.inputs['Roughness'].default_value = 0.0
        self.inputs['Normal'].default_value = (0.0, 0.0, 0.0)

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'SHADER'

        _sock_out_Rim = nt.interface.new_socket(name='Rim', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Rim.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_inp_Rim_Strength = nt.interface.new_socket(name='Rim Strength', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Rim_Strength.default_value = 0.0
        _sock_inp_Rim_Strength.min_value = 0.0
        _sock_inp_Rim_Strength.max_value = 10.0
        _sock_inp_Roughness = nt.interface.new_socket(name='Roughness', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Roughness.default_value = 0.0
        _sock_inp_Roughness.min_value = 0.0
        _sock_inp_Roughness.max_value = 1.0
        _sock_inp_Normal = nt.interface.new_socket(name='Normal', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Normal.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Normal.min_value = -3.4028234663852886e+38
        _sock_inp_Normal.max_value = 3.4028234663852886e+38
        _sock_inp_Normal.hide_value = True
        _sock_inp_Normal.dimensions = 3

        Glossy_BSDF = nt.nodes.new('ShaderNodeBsdfAnisotropic')
        Glossy_BSDF.location = (-2.4, 12.54)
        Glossy_BSDF.width = 150.0
        Glossy_BSDF.distribution = 'GGX'
        Glossy_BSDF.inputs[0].default_value = (1.0, 1.0, 1.0, 1.0)
        Glossy_BSDF.inputs[2].default_value = 0.0
        Glossy_BSDF.inputs[3].default_value = 0.0
        Glossy_BSDF.inputs[5].default_value = (0.0, 0.0, 0.0)
        Glossy_BSDF.inputs[6].default_value = 0.0

        Math_001 = nt.nodes.new('ShaderNodeMath')
        Math_001.location = (-192.84, 46.87)
        Math_001.label = 'Scale Ramp up'
        Math_001.operation = 'ADD'
        Math_001.use_clamp = False
        Math_001.inputs[1].default_value = 0.5
        Math_001.inputs[2].default_value = 0.5

        Shader_to_RGB = nt.nodes.new('ShaderNodeShaderToRGB')
        Shader_to_RGB.location = (196.92, -12.54)

        Bright_Contrast = nt.nodes.new('ShaderNodeBrightContrast')
        Bright_Contrast.location = (417.0, 1.77)
        Bright_Contrast.inputs[2].default_value = 0.0

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (636.95, 5.52)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-576.7, -171.7)


        nt.links.new(Math_001.outputs['Value'], Glossy_BSDF.inputs['Roughness'])
        nt.links.new(Group_Input.outputs['Normal'], Glossy_BSDF.inputs['Normal'])
        nt.links.new(Group_Input.outputs['Roughness'], Math_001.inputs[0])
        nt.links.new(Glossy_BSDF.outputs['BSDF'], Shader_to_RGB.inputs['Shader'])
        nt.links.new(Shader_to_RGB.outputs['Color'], Bright_Contrast.inputs['Color'])
        nt.links.new(Group_Input.outputs['Rim Strength'], Bright_Contrast.inputs['Brightness'])
        nt.links.new(Bright_Contrast.outputs['Color'], Group_Output.inputs['Rim'])
