# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ....node import ShaderNode, ensure_node_group


class ShaderNodeCompiled_Simple_Back_Toon_Dot(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Simple_Back_Toon_Dot'
    bl_label = 'lscherry.core.Simple Back Toon Dot'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Simple Back Toon Dot'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Normal'].default_value = (0.0, 0.0, 0.0)

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'SHADER'

        _sock_out_NdotL = nt.interface.new_socket(name='NdotL', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_NdotL.default_value = 0.0
        _sock_out_NdotL.min_value = -3.4028234663852886e+38
        _sock_out_NdotL.max_value = 3.4028234663852886e+38
        _sock_inp_Normal = nt.interface.new_socket(name='Normal', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Normal.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Normal.min_value = -3.4028234663852886e+38
        _sock_inp_Normal.max_value = 3.4028234663852886e+38
        _sock_inp_Normal.hide_value = True
        _sock_inp_Normal.dimensions = 3

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (496.36, 239.01)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-489.36, 0.0)

        Group_003 = nt.nodes.new('ShaderNodeGroup')
        Group_003.location = (262.82, 262.01)
        Group_003.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Group_003.inputs[0].default_value = False
        Group_003.inputs[2].default_value = 0.0

        Use_Default_Normal = nt.nodes.new('ShaderNodeGroup')
        Use_Default_Normal.location = (-112.33, -9.24)
        Use_Default_Normal.node_tree = ensure_node_group('.lscherry.utils.normal.Use Default Normal')

        Group_009__Attribute_001 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_001.location = (0.0, -123.16)
        Group_009__Attribute_001.hide = True
        Group_009__Attribute_001.attribute_type = 'GEOMETRY'
        Group_009__Attribute_001.attribute_name = 'tn'

        Group_009__Attribute_002 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_002.location = (0.0, 22.36)
        Group_009__Attribute_002.hide = True
        Group_009__Attribute_002.attribute_type = 'GEOMETRY'
        Group_009__Attribute_002.attribute_name = 'm'

        Group_009__Attribute_003 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_003.location = (0.0, -13.01)
        Group_009__Attribute_003.hide = True
        Group_009__Attribute_003.attribute_type = 'GEOMETRY'
        Group_009__Attribute_003.attribute_name = 'b'

        Group_009__Attribute_004 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_004.location = (0.0, -49.85)
        Group_009__Attribute_004.hide = True
        Group_009__Attribute_004.attribute_type = 'GEOMETRY'
        Group_009__Attribute_004.attribute_name = 'fx'

        Group_009__Attribute_005 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_005.location = (0.0, -85.91)
        Group_009__Attribute_005.hide = True
        Group_009__Attribute_005.attribute_type = 'GEOMETRY'
        Group_009__Attribute_005.attribute_name = 'fy'


        nt.links.new(Group_003.outputs['NdotL'], Group_Output.inputs['NdotL'])
        nt.links.new(Use_Default_Normal.outputs['Normal'], Group_003.inputs['Normal'])
        nt.links.new(Group_Input.outputs['Normal'], Use_Default_Normal.inputs['Normal'])
        nt.links.new(Group_009__Attribute_003.outputs['Vector'], Group_003.inputs['Light Dir'])
