# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ....node import ShaderNode


class ShaderNodeCompiled_Specular_Dot(ShaderNode):
    bl_label = 'lscherry.core.Specular Dot'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Light Dir'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Normal'].default_value = (0.0, 0.0, 0.0)

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'INPUT'

        _sock_out_Specular = nt.interface.new_socket(name='Specular', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Specular.default_value = 0.0
        _sock_out_Specular.min_value = -3.4028234663852886e+38
        _sock_out_Specular.max_value = 3.4028234663852886e+38
        _sock_inp_Light_Dir = nt.interface.new_socket(name='Light Dir', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Light_Dir.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Light_Dir.min_value = -10000.0
        _sock_inp_Light_Dir.max_value = 10000.0
        _sock_inp_Light_Dir.hide_value = True
        _sock_inp_Light_Dir.dimensions = 3
        _sock_inp_Normal = nt.interface.new_socket(name='Normal', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Normal.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Normal.min_value = -3.4028234663852886e+38
        _sock_inp_Normal.max_value = 3.4028234663852886e+38
        _sock_inp_Normal.hide_value = True
        _sock_inp_Normal.dimensions = 3

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (586.19, 51.96)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-1177.84, -14.92)

        Geometry = nt.nodes.new('ShaderNodeNewGeometry')
        Geometry.location = (-774.67, -102.42)

        Vector_Math_004 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_004.location = (-594.38, -64.68)
        Vector_Math_004.operation = 'NORMALIZE'
        Vector_Math_004.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math_004.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_004.inputs[3].default_value = 1.0

        Vector_Math_005 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_005.location = (-362.02, 51.21)
        Vector_Math_005.operation = 'DOT_PRODUCT'
        Vector_Math_005.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_005.inputs[3].default_value = 1.0

        Vector_Rotate = nt.nodes.new('ShaderNodeVectorRotate')
        Vector_Rotate.location = (-955.69, 116.64)
        Vector_Rotate.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Rotate.inputs[2].default_value = (0.0, 0.0, 1.0)
        Vector_Rotate.inputs[3].default_value = 0.0

        Combine_XYZ = nt.nodes.new('ShaderNodeCombineXYZ')
        Combine_XYZ.location = (-1316.39, 135.51)
        Combine_XYZ.width = 266.55
        Combine_XYZ.label = 'If your light is Sun, do not make change this'
        Combine_XYZ.inputs[0].default_value = 0.0
        Combine_XYZ.inputs[1].default_value = 0.0
        Combine_XYZ.inputs[2].default_value = -1.0

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (401.16, 34.98)
        Math.operation = 'POWER'
        Math.use_clamp = False
        Math.inputs[1].default_value = 0.5
        Math.inputs[2].default_value = 0.5

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (166.82, -90.21)

        Vector_Math_006 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_006.location = (-568.52, 57.11)
        Vector_Math_006.operation = 'NORMALIZE'
        Vector_Math_006.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math_006.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_006.inputs[3].default_value = 1.0

        Vector_Math_010 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_010.location = (-761.45, 77.21)
        Vector_Math_010.operation = 'REFLECT'
        Vector_Math_010.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_010.inputs[3].default_value = 1.0

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (-1.67, 237.71)
        Mix.data_type = 'FLOAT'
        Mix.blend_type = 'MIX'
        Mix.clamp_result = False
        Mix.clamp_factor = True
        Mix.factor_mode = 'UNIFORM'
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[6].default_value = (0.5, 0.5, 0.5, 1.0)
        Mix.inputs[7].default_value = (0.5, 0.5, 0.5, 1.0)
        Mix.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Vector_Math_012 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_012.location = (-465.17, 312.09)
        Vector_Math_012.operation = 'DOT_PRODUCT'
        Vector_Math_012.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_012.inputs[3].default_value = 1.0

        Vector_Math_007 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_007.location = (-285.43, 276.36)
        Vector_Math_007.operation = 'NORMALIZE'
        Vector_Math_007.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math_007.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_007.inputs[3].default_value = 1.0

        Group_Input_002 = nt.nodes.new('NodeGroupInput')
        Group_Input_002.location = (-1065.78, 334.26)

        Vector_Rotate_001 = nt.nodes.new('ShaderNodeVectorRotate')
        Vector_Rotate_001.location = (-843.63, 465.82)
        Vector_Rotate_001.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Rotate_001.inputs[2].default_value = (0.0, 0.0, 1.0)
        Vector_Rotate_001.inputs[3].default_value = 0.0

        Combine_XYZ_001 = nt.nodes.new('ShaderNodeCombineXYZ')
        Combine_XYZ_001.location = (-1204.33, 484.69)
        Combine_XYZ_001.width = 266.55
        Combine_XYZ_001.label = 'If your light is Sun, do not make change this'
        Combine_XYZ_001.inputs[0].default_value = 0.0
        Combine_XYZ_001.inputs[1].default_value = 0.0
        Combine_XYZ_001.inputs[2].default_value = 1.0


        nt.links.new(Math.outputs['Value'], Group_Output.inputs['Specular'])
        nt.links.new(Geometry.outputs['Incoming'], Vector_Math_004.inputs['Vector'])
        nt.links.new(Vector_Math_006.outputs['Vector'], Vector_Math_005.inputs['Vector'])
        nt.links.new(Vector_Math_004.outputs['Vector'], Vector_Math_005.inputs['Vector'])
        nt.links.new(Combine_XYZ.outputs['Vector'], Vector_Rotate.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Light Dir'], Vector_Rotate.inputs['Rotation'])
        nt.links.new(Mix.outputs['Result'], Math.inputs['Value'])
        nt.links.new(Vector_Math_010.outputs['Vector'], Vector_Math_006.inputs['Vector'])
        nt.links.new(Vector_Rotate.outputs['Vector'], Vector_Math_010.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Normal'], Vector_Math_010.inputs['Vector'])
        nt.links.new(Vector_Math_007.outputs['Vector'], Mix.inputs['Factor'])
        nt.links.new(Vector_Math_012.outputs['Value'], Mix.inputs['A'])
        nt.links.new(Vector_Math_005.outputs['Value'], Mix.inputs['B'])
        nt.links.new(Group_Input.outputs['Normal'], Mix.inputs['A'])
        nt.links.new(Vector_Math_004.outputs['Vector'], Mix.inputs['B'])
        nt.links.new(Vector_Rotate_001.outputs['Vector'], Vector_Math_012.inputs['Vector'])
        nt.links.new(Group_Input_002.outputs['Normal'], Vector_Math_012.inputs['Vector'])
        nt.links.new(Vector_Math_012.outputs['Value'], Vector_Math_007.inputs['Vector'])
        nt.links.new(Combine_XYZ_001.outputs['Vector'], Vector_Rotate_001.inputs['Vector'])
        nt.links.new(Group_Input_002.outputs['Light Dir'], Vector_Rotate_001.inputs['Rotation'])
