# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ..node import ShaderNode


class ShaderNodeCompiled_Experimental(ShaderNode):
    bl_label = 'lscherry.Experimental'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'OUTPUT'

        _sock_out_Unstable = nt.interface.new_socket(name='Unstable', in_out='OUTPUT', socket_type='NodeSocketShader')
        _sock_out_Unstable.hide_value = True
        _sock_out_DO_NOT_USE_FOR_PRODUCTION = nt.interface.new_socket(name='DO NOT USE FOR PRODUCTION', in_out='OUTPUT', socket_type='NodeSocketShader')
        _sock_out_DO_NOT_USE_FOR_PRODUCTION.hide_value = True
        _sock_inp_Unstable = nt.interface.new_socket(name='Unstable', in_out='INPUT', socket_type='NodeSocketShader')
        _sock_inp_Unstable.hide_value = True
        _sock_inp_DO_NOT_USE_FOR_PRODUCTION = nt.interface.new_socket(name='DO NOT USE FOR PRODUCTION', in_out='INPUT', socket_type='NodeSocketShader')
        _sock_inp_DO_NOT_USE_FOR_PRODUCTION.hide_value = True

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (209.28, 92.1)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-190.72, 92.1)


        nt.links.new(Group_Input.outputs['Unstable'], Group_Output.inputs['Unstable'])
        nt.links.new(Group_Input.outputs['DO NOT USE FOR PRODUCTION'], Group_Output.inputs['DO NOT USE FOR PRODUCTION'])
