# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ...node import GeometryNode


class GeometryNodeCompiled_Get_Object_Info(GeometryNode):
    bl_idname = 'GeometryNodeCompiled_Get_Object_Info'
    bl_label = 'lscherry.Get Object Info'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Get Object Info'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'GeometryNodeTree'
        )
        nt.color_tag = 'NONE'

        _sock_out_Geometry = nt.interface.new_socket(name='Geometry', in_out='OUTPUT', socket_type='NodeSocketGeometry')
        _sock_out_Global_Location = nt.interface.new_socket(name='Global Location', in_out='OUTPUT', socket_type='NodeSocketVector')
        _sock_out_Global_Location.default_value = (0.0, 0.0, 0.0)
        _sock_out_Global_Location.min_value = -3.4028234663852886e+38
        _sock_out_Global_Location.max_value = 3.4028234663852886e+38
        _sock_out_Global_Location.dimensions = 3
        _sock_out_Local_Location = nt.interface.new_socket(name='Local Location', in_out='OUTPUT', socket_type='NodeSocketVector')
        _sock_out_Local_Location.default_value = (0.0, 0.0, 0.0)
        _sock_out_Local_Location.min_value = -3.4028234663852886e+38
        _sock_out_Local_Location.max_value = 3.4028234663852886e+38
        _sock_out_Local_Location.dimensions = 3
        _sock_inp_Geometry = nt.interface.new_socket(name='Geometry', in_out='INPUT', socket_type='NodeSocketGeometry')
        _sock_inp_Object = nt.interface.new_socket(name='Object', in_out='INPUT', socket_type='NodeSocketObject')

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-340.0, 0.0)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (200.0, 0.0)

        Object_Info = nt.nodes.new('GeometryNodeObjectInfo')
        Object_Info.location = (-84.75, -40.82)
        Object_Info.transform_space = 'ORIGINAL'
        Object_Info.inputs[1].default_value = False

        Object_Info_001 = nt.nodes.new('GeometryNodeObjectInfo')
        Object_Info_001.location = (-84.75, -156.39)
        Object_Info_001.transform_space = 'RELATIVE'
        Object_Info_001.inputs[1].default_value = False


        nt.links.new(Group_Input.outputs['Geometry'], Group_Output.inputs['Geometry'])
        nt.links.new(Object_Info.outputs['Location'], Group_Output.inputs['Global Location'])
        nt.links.new(Object_Info_001.outputs['Location'], Group_Output.inputs['Local Location'])
        nt.links.new(Group_Input.outputs['Object'], Object_Info.inputs['Object'])
        nt.links.new(Group_Input.outputs['Object'], Object_Info_001.inputs['Object'])
