# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ..node import ShaderNode


class ShaderNodeCompiled_HI3__Build_Body_Package(ShaderNode):
    bl_label = 'lscherry.HI3: Build Body Package'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Body Texture'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Body Alpha'].default_value = 0.0
        self.inputs['Lightmap Texture'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Lighmap  Alpha Texture'].default_value = 0.0
        self.inputs['Map 1'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 2'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 3'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 4'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 5'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Range 1'].default_value = 0.10000000149011612
        self.inputs['Range 2'].default_value = 0.30000001192092896
        self.inputs['Range 3'].default_value = 0.44999998807907104
        self.inputs['Range 4'].default_value = 0.6200000047683716
        self.inputs['Map 1'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 2'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 3'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 4'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 5'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Range 1'].default_value = 0.10000000149011612
        self.inputs['Range 2'].default_value = 0.30000001192092896
        self.inputs['Range 3'].default_value = 0.44999998807907104
        self.inputs['Range 4'].default_value = 0.6200000047683716

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'COLOR'

        _sock_out_Base_Color = nt.interface.new_socket(name='Base Color', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Base_Color.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_out_Shadow_Color = nt.interface.new_socket(name='Shadow Color', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Shadow_Color.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_out_SSS_Color = nt.interface.new_socket(name='SSS Color', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_SSS_Color.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_out_Body_Alpha = nt.interface.new_socket(name='Body Alpha', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Body_Alpha.default_value = 0.0
        _sock_out_Body_Alpha.min_value = -3.4028234663852886e+38
        _sock_out_Body_Alpha.max_value = 3.4028234663852886e+38
        _sock_out_Body_Alpha.hide_value = True
        _sock_out_Enable_Custom_Ramp = nt.interface.new_socket(name='Enable Custom Ramp', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Enable_Custom_Ramp.default_value = 0.0
        _sock_out_Enable_Custom_Ramp.min_value = -3.4028234663852886e+38
        _sock_out_Enable_Custom_Ramp.max_value = 3.4028234663852886e+38
        _sock_out_Custom_Ramp = nt.interface.new_socket(name='Custom Ramp', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Custom_Ramp.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_out_Metal_Mask = nt.interface.new_socket(name='Metal Mask', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Metal_Mask.default_value = 0.0
        _sock_out_Metal_Mask.min_value = -3.4028234663852886e+38
        _sock_out_Metal_Mask.max_value = 3.4028234663852886e+38
        _sock_out_Shadow_Mask = nt.interface.new_socket(name='Shadow Mask', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Shadow_Mask.default_value = 0.0
        _sock_out_Shadow_Mask.min_value = -3.4028234663852886e+38
        _sock_out_Shadow_Mask.max_value = 3.4028234663852886e+38
        _sock_inp_Body_Texture = nt.interface.new_socket(name='Body Texture', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Body_Texture.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Body_Texture.hide_value = True
        _sock_inp_Body_Alpha = nt.interface.new_socket(name='Body Alpha', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Body_Alpha.default_value = 0.0
        _sock_inp_Body_Alpha.min_value = -3.4028234663852886e+38
        _sock_inp_Body_Alpha.max_value = 3.4028234663852886e+38
        _sock_inp_Body_Alpha.hide_value = True
        _sock_inp_Lightmap_Texture = nt.interface.new_socket(name='Lightmap Texture', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Lightmap_Texture.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Lightmap_Texture.hide_value = True
        _sock_inp_Lighmap__Alpha_Texture = nt.interface.new_socket(name='Lighmap  Alpha Texture', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Lighmap__Alpha_Texture.default_value = 0.0
        _sock_inp_Lighmap__Alpha_Texture.min_value = 0.0
        _sock_inp_Lighmap__Alpha_Texture.max_value = 1.0
        _sock_inp_Lighmap__Alpha_Texture.hide_value = True
        _sock_inp_Shadow = nt.interface.new_socket(name='--- Shadow ---', in_out='INPUT', socket_type='NodeSocketShader')
        _sock_inp_Map_1 = nt.interface.new_socket(name='Map 1', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_1.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_2 = nt.interface.new_socket(name='Map 2', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_2.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_3 = nt.interface.new_socket(name='Map 3', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_3.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_4 = nt.interface.new_socket(name='Map 4', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_4.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_5 = nt.interface.new_socket(name='Map 5', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_5.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Range_1 = nt.interface.new_socket(name='Range 1', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_1.default_value = 0.10000000149011612
        _sock_inp_Range_1.min_value = 0.0
        _sock_inp_Range_1.max_value = 1.0
        _sock_inp_Range_1.subtype = 'FACTOR'
        _sock_inp_Range_2 = nt.interface.new_socket(name='Range 2', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_2.default_value = 0.30000001192092896
        _sock_inp_Range_2.min_value = 0.0
        _sock_inp_Range_2.max_value = 1.0
        _sock_inp_Range_2.subtype = 'FACTOR'
        _sock_inp_Range_3 = nt.interface.new_socket(name='Range 3', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_3.default_value = 0.44999998807907104
        _sock_inp_Range_3.min_value = 0.0
        _sock_inp_Range_3.max_value = 1.0
        _sock_inp_Range_3.subtype = 'FACTOR'
        _sock_inp_Range_4 = nt.interface.new_socket(name='Range 4', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_4.default_value = 0.6200000047683716
        _sock_inp_Range_4.min_value = 0.0
        _sock_inp_Range_4.max_value = 1.0
        _sock_inp_Range_4.subtype = 'FACTOR'
        _sock_inp_SSS = nt.interface.new_socket(name='--- SSS ---', in_out='INPUT', socket_type='NodeSocketShader')
        _sock_inp_Map_1 = nt.interface.new_socket(name='Map 1', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_1.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_2 = nt.interface.new_socket(name='Map 2', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_2.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_3 = nt.interface.new_socket(name='Map 3', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_3.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_4 = nt.interface.new_socket(name='Map 4', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_4.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_5 = nt.interface.new_socket(name='Map 5', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_5.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Range_1 = nt.interface.new_socket(name='Range 1', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_1.default_value = 0.10000000149011612
        _sock_inp_Range_1.min_value = 0.0
        _sock_inp_Range_1.max_value = 1.0
        _sock_inp_Range_1.subtype = 'FACTOR'
        _sock_inp_Range_2 = nt.interface.new_socket(name='Range 2', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_2.default_value = 0.30000001192092896
        _sock_inp_Range_2.min_value = 0.0
        _sock_inp_Range_2.max_value = 1.0
        _sock_inp_Range_2.subtype = 'FACTOR'
        _sock_inp_Range_3 = nt.interface.new_socket(name='Range 3', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_3.default_value = 0.44999998807907104
        _sock_inp_Range_3.min_value = 0.0
        _sock_inp_Range_3.max_value = 1.0
        _sock_inp_Range_3.subtype = 'FACTOR'
        _sock_inp_Range_4 = nt.interface.new_socket(name='Range 4', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_4.default_value = 0.6200000047683716
        _sock_inp_Range_4.min_value = 0.0
        _sock_inp_Range_4.max_value = 1.0
        _sock_inp_Range_4.subtype = 'FACTOR'

        Group_009 = nt.nodes.new('ShaderNodeGroup')
        Group_009.location = (469.67, 286.64)
        Group_009.width = 190.21
        Group_009.node_tree = bpy.data.node_groups['HI3: Body Color From Lightmap']
        Group_009.inputs[1].default_value = (0.0, 0.0, 0.0, 1.0)

        Group_012 = nt.nodes.new('ShaderNodeGroup')
        Group_012.location = (-163.25, 176.68)
        Group_012.width = 190.21
        Group_012.node_tree = bpy.data.node_groups['HI3: Body Color From Lightmap']
        Group_012.inputs[0].default_value = 0.0
        Group_012.inputs[1].default_value = (0.0, 0.0, 0.0, 1.0)
        Group_012.inputs[2].default_value = (0.0, 0.0, 0.0, 1.0)
        Group_012.inputs[3].default_value = (0.0, 0.0, 0.0, 1.0)
        Group_012.inputs[4].default_value = (0.0, 0.0, 0.0, 1.0)
        Group_012.inputs[5].default_value = (0.0, 0.0, 0.0, 1.0)
        Group_012.inputs[6].default_value = (0.0, 0.0, 0.0, 1.0)
        Group_012.inputs[7].default_value = 0.10000000149011612
        Group_012.inputs[8].default_value = 0.30000001192092896
        Group_012.inputs[9].default_value = 0.44999998807907104
        Group_012.inputs[10].default_value = 0.6200000047683716

        Group_014 = nt.nodes.new('ShaderNodeGroup')
        Group_014.location = (243.68, -346.1)
        Group_014.node_tree = bpy.data.node_groups['Build Metal Ramp']
        Group_014.inputs[1].default_value = 0.5800000429153442
        Group_014.inputs[2].default_value = 0.800000011920929
        Group_014.inputs[3].default_value = 0.949999988079071
        Group_014.inputs[4].default_value = (0.0, 0.0, 0.0, 1.0)
        Group_014.inputs[5].default_value = (0.024790925905108452, 0.024790925905108452, 0.024790925905108452, 1.0)
        Group_014.inputs[6].default_value = (0.12354078888893127, 0.12354078888893127, 0.12354078888893127, 1.0)
        Group_014.inputs[7].default_value = (1.0, 1.0, 1.0, 1.0)

        Group_013 = nt.nodes.new('ShaderNodeGroup')
        Group_013.location = (-183.89, -274.16)
        Group_013.width = 208.28
        Group_013.node_tree = bpy.data.node_groups['HI3: Seperate Body Lightmap']

        Group_008 = nt.nodes.new('ShaderNodeGroup')
        Group_008.location = (509.59, 494.68)
        Group_008.node_tree = bpy.data.node_groups['Add Fake Shadow Color']
        Group_008.inputs[1].default_value = 0.0

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-543.97, 442.44)

        Group_011 = nt.nodes.new('ShaderNodeGroup')
        Group_011.location = (469.67, -33.64)
        Group_011.width = 190.21
        Group_011.node_tree = bpy.data.node_groups['HI3: Body Color From Lightmap']
        Group_011.inputs[1].default_value = (0.0, 0.0, 0.0, 1.0)

        Group_Input_004 = nt.nodes.new('NodeGroupInput')
        Group_Input_004.location = (215.0, -96.81)

        Group_Input_002 = nt.nodes.new('NodeGroupInput')
        Group_Input_002.location = (-584.18, 116.87)

        Group_Input_005 = nt.nodes.new('NodeGroupInput')
        Group_Input_005.location = (493.31, 586.29)

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (232.54, 504.84)

        Group_Input_003 = nt.nodes.new('NodeGroupInput')
        Group_Input_003.location = (207.03, 191.73)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1019.32, 3.59)


        nt.links.new(Group_Input.outputs['Lighmap  Alpha Texture'], Group_009.inputs['Lighmap Alpha'])
        nt.links.new(Group_Input_003.outputs['Map 1'], Group_009.inputs['Map 1'])
        nt.links.new(Group_Input_003.outputs['Map 2'], Group_009.inputs['Map 2'])
        nt.links.new(Group_Input_003.outputs['Map 3'], Group_009.inputs['Map 3'])
        nt.links.new(Group_Input_003.outputs['Map 4'], Group_009.inputs['Map 4'])
        nt.links.new(Group_Input_003.outputs['Map 5'], Group_009.inputs['Map 5'])
        nt.links.new(Group_Input_003.outputs['Range 1'], Group_009.inputs['Range 1'])
        nt.links.new(Group_Input_003.outputs['Range 2'], Group_009.inputs['Range 2'])
        nt.links.new(Group_Input_003.outputs['Range 3'], Group_009.inputs['Range 3'])
        nt.links.new(Group_Input_003.outputs['Range 4'], Group_009.inputs['Range 4'])
        nt.links.new(Group_Input.outputs['Lightmap Texture'], Group_013.inputs['Lightmap'])
        nt.links.new(Group_Input.outputs['Body Texture'], Group_008.inputs['Original Color'])
        nt.links.new(Group_013.outputs['Shadow'], Group_008.inputs['Shadow Mask'])
        nt.links.new(Group_012.outputs['Color Map'], Group_008.inputs['Shadow Color'])
        nt.links.new(Group_Input.outputs['Lighmap  Alpha Texture'], Group_011.inputs['Lighmap Alpha'])
        nt.links.new(Group_Input_004.outputs['Map 1'], Group_011.inputs['Map 1'])
        nt.links.new(Group_Input_004.outputs['Map 2'], Group_011.inputs['Map 2'])
        nt.links.new(Group_Input_004.outputs['Map 3'], Group_011.inputs['Map 3'])
        nt.links.new(Group_Input_004.outputs['Map 4'], Group_011.inputs['Map 4'])
        nt.links.new(Group_Input_004.outputs['Map 5'], Group_011.inputs['Map 5'])
        nt.links.new(Group_Input_004.outputs['Range 1'], Group_011.inputs['Range 1'])
        nt.links.new(Group_Input_004.outputs['Range 2'], Group_011.inputs['Range 2'])
        nt.links.new(Group_Input_004.outputs['Range 3'], Group_011.inputs['Range 3'])
        nt.links.new(Group_Input_004.outputs['Range 4'], Group_011.inputs['Range 4'])
        nt.links.new(Group_008.outputs['Color'], Group_Output.inputs['Base Color'])
        nt.links.new(Group_009.outputs['Color Map'], Group_Output.inputs['Shadow Color'])
        nt.links.new(Group_011.outputs['Color Map'], Group_Output.inputs['SSS Color'])
        nt.links.new(Group_Input_005.outputs['Body Alpha'], Group_Output.inputs['Body Alpha'])
        nt.links.new(Group_013.outputs['Metal'], Group_Output.inputs['Enable Custom Ramp'])
        nt.links.new(Group_014.outputs['Custom Ramp'], Group_Output.inputs['Custom Ramp'])
        nt.links.new(Group_013.outputs['Metal'], Group_Output.inputs['Metal Mask'])
        nt.links.new(Group_013.outputs['Shadow'], Group_Output.inputs['Shadow Mask'])
