# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ...node import ShaderNode, ensure_node_group


class ShaderNodeCompiled_LS_Cherry_Main_Controller(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_LS_Cherry_Main_Controller'
    bl_label = 'lscherry.LS Cherry Main Controller'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'LS Cherry Main Controller'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Base Color'].default_value = (1.0, 0.0, 0.0, 1.0)
        self.inputs['Shadow Color'].default_value = (0.7428570985794067, 0.6048978567123413, 0.6048978567123413, 1.0)
        self.inputs['SSS Color'].default_value = (1.0, 0.08650019019842148, 0.0, 1.0)
        self.inputs['Rim Color'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Normal'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Back Color'].default_value = (0.04373471811413765, 0.08650025725364685, 0.42326751351356506, 1.0)
        self.inputs['Rim Strength'].default_value = 0.5
        self.inputs['Rim Size'].default_value = 0.5
        self.inputs['Rim Smooth'].default_value = 0.5
        self.inputs['Specular Color'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Specular Tint'].default_value = 0.0
        self.inputs['Roughness'].default_value = 0.10000000149011612
        self.inputs['Pattern'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Emission'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Emission Strength'].default_value = 1.0
        self.inputs['Disable Toon Style'].default_value = False
        self.inputs['Toon Style'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Disable SSS Style'].default_value = False
        self.inputs['SSS Style'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Disable Back Style'].default_value = False
        self.inputs['Back Style'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Enable Custom Ramp'].default_value = False
        self.inputs['Custom Ramp'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Blend With Custom Ramp'].default_value = 1.0

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'SHADER'

        _sock_out_Combined = nt.interface.new_socket(name='Combined', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Combined.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_out_Diffuse_Mask = nt.interface.new_socket(name='Diffuse Mask', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Diffuse_Mask.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_out_Post_Diffuse_Mask = nt.interface.new_socket(name='Post Diffuse Mask', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Post_Diffuse_Mask.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_out_Post_Diffuse_Mask.hide_value = True
        _sock_out_SSS_Mask = nt.interface.new_socket(name='SSS Mask', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_SSS_Mask.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_out_SSS_Mask.hide_value = True
        _sock_out_Rim_Mask = nt.interface.new_socket(name='Rim Mask', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Rim_Mask.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_out_Back_Mask = nt.interface.new_socket(name='Back Mask', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Back_Mask.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_out_Light_Sources_Mask = nt.interface.new_socket(name='Light Sources Mask', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Light_Sources_Mask.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Base_Color = nt.interface.new_socket(name='Base Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Base_Color.default_value = (1.0, 0.0, 0.0, 1.0)
        _sock_inp_Shadow_Color = nt.interface.new_socket(name='Shadow Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Shadow_Color.default_value = (0.7428570985794067, 0.6048978567123413, 0.6048978567123413, 1.0)
        _sock_inp_SSS_Color = nt.interface.new_socket(name='SSS Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_SSS_Color.default_value = (1.0, 0.08650019019842148, 0.0, 1.0)
        _sock_inp_Rim_Color = nt.interface.new_socket(name='Rim Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Rim_Color.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Normal = nt.interface.new_socket(name='Normal', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Normal.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Normal.min_value = -3.4028234663852886e+38
        _sock_inp_Normal.max_value = 3.4028234663852886e+38
        _sock_inp_Normal.hide_value = True
        _sock_inp_Normal.dimensions = 3
        _panel_Dot = nt.interface.new_panel(name='Dot', default_closed=True)
        _panel_Dot.description = 'Panel of Dot product uses only'
        _sock_inp_Back_Color = nt.interface.new_socket(name='Back Color', in_out='INPUT', socket_type='NodeSocketColor', parent=_panel_Dot)
        _sock_inp_Back_Color.default_value = (0.04373471811413765, 0.08650025725364685, 0.42326751351356506, 1.0)
        _panel_Rim = nt.interface.new_panel(name='Rim')
        _sock_inp_Rim_Strength = nt.interface.new_socket(name='Rim Strength', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Rim)
        _sock_inp_Rim_Strength.default_value = 0.5
        _sock_inp_Rim_Strength.min_value = 0.0
        _sock_inp_Rim_Strength.max_value = 10.0
        _sock_inp_Rim_Strength.subtype = 'FACTOR'
        _sock_inp_Rim_Size = nt.interface.new_socket(name='Rim Size', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Rim)
        _sock_inp_Rim_Size.default_value = 0.5
        _sock_inp_Rim_Size.min_value = 0.0
        _sock_inp_Rim_Size.max_value = 1.0
        _sock_inp_Rim_Smooth = nt.interface.new_socket(name='Rim Smooth', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Rim)
        _sock_inp_Rim_Smooth.default_value = 0.5
        _sock_inp_Rim_Smooth.min_value = 0.0
        _sock_inp_Rim_Smooth.max_value = 1.0
        _panel_Specular = nt.interface.new_panel(name='Specular', default_closed=True)
        _panel_Specular.description = 'Specular Panel'
        _sock_inp_Specular_Color = nt.interface.new_socket(name='Specular Color', in_out='INPUT', socket_type='NodeSocketColor', parent=_panel_Specular)
        _sock_inp_Specular_Color.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Specular_Tint = nt.interface.new_socket(name='Specular Tint', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Specular)
        _sock_inp_Specular_Tint.default_value = 0.0
        _sock_inp_Specular_Tint.min_value = 0.0
        _sock_inp_Specular_Tint.max_value = 1.0
        _sock_inp_Specular_Tint.subtype = 'FACTOR'
        _panel_General = nt.interface.new_panel(name='General', default_closed=True)
        _panel_General.description = 'Genereal Things that can be used from any purposes'
        _sock_inp_Roughness = nt.interface.new_socket(name='Roughness', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_General)
        _sock_inp_Roughness.default_value = 0.10000000149011612
        _sock_inp_Roughness.min_value = 0.0
        _sock_inp_Roughness.max_value = 1.0
        _sock_inp_Roughness.subtype = 'FACTOR'
        _sock_inp_Pattern = nt.interface.new_socket(name='Pattern', in_out='INPUT', socket_type='NodeSocketColor', parent=_panel_General)
        _sock_inp_Pattern.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Emission = nt.interface.new_socket(name='Emission', in_out='INPUT', socket_type='NodeSocketColor', parent=_panel_General)
        _sock_inp_Emission.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Emission_Strength = nt.interface.new_socket(name='Emission Strength', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_General)
        _sock_inp_Emission_Strength.default_value = 1.0
        _sock_inp_Emission_Strength.min_value = 0.0
        _sock_inp_Emission_Strength.max_value = 100.0
        _panel_Stylized_Ramp = nt.interface.new_panel(name='Stylized Ramp', default_closed=True)
        _panel_Stylized_Ramp.description = 'Custom Ramp'
        _sock_inp_Disable_Toon_Style = nt.interface.new_socket(name='Disable Toon Style', in_out='INPUT', socket_type='NodeSocketBool', parent=_panel_Stylized_Ramp)
        _sock_inp_Disable_Toon_Style.default_value = False
        _sock_inp_Toon_Style = nt.interface.new_socket(name='Toon Style', in_out='INPUT', socket_type='NodeSocketVector', parent=_panel_Stylized_Ramp)
        _sock_inp_Toon_Style.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Toon_Style.min_value = -3.4028234663852886e+38
        _sock_inp_Toon_Style.max_value = 3.4028234663852886e+38
        _sock_inp_Toon_Style.subtype = 'XYZ'
        _sock_inp_Toon_Style.hide_value = True
        _sock_inp_Toon_Style.dimensions = 3
        _sock_inp_Disable_SSS_Style = nt.interface.new_socket(name='Disable SSS Style', in_out='INPUT', socket_type='NodeSocketBool', parent=_panel_Stylized_Ramp)
        _sock_inp_Disable_SSS_Style.default_value = False
        _sock_inp_SSS_Style = nt.interface.new_socket(name='SSS Style', in_out='INPUT', socket_type='NodeSocketVector', parent=_panel_Stylized_Ramp)
        _sock_inp_SSS_Style.default_value = (0.0, 0.0, 0.0)
        _sock_inp_SSS_Style.min_value = -3.4028234663852886e+38
        _sock_inp_SSS_Style.max_value = 3.4028234663852886e+38
        _sock_inp_SSS_Style.subtype = 'XYZ'
        _sock_inp_SSS_Style.hide_value = True
        _sock_inp_SSS_Style.dimensions = 3
        _sock_inp_Disable_Back_Style = nt.interface.new_socket(name='Disable Back Style', in_out='INPUT', socket_type='NodeSocketBool', parent=_panel_Stylized_Ramp)
        _sock_inp_Disable_Back_Style.default_value = False
        _sock_inp_Back_Style = nt.interface.new_socket(name='Back Style', in_out='INPUT', socket_type='NodeSocketVector', parent=_panel_Stylized_Ramp)
        _sock_inp_Back_Style.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Back_Style.min_value = -3.4028234663852886e+38
        _sock_inp_Back_Style.max_value = 3.4028234663852886e+38
        _sock_inp_Back_Style.subtype = 'XYZ'
        _sock_inp_Back_Style.hide_value = True
        _sock_inp_Back_Style.dimensions = 3
        _panel_Ramp = nt.interface.new_panel(name='Ramp', default_closed=True)
        _panel_Ramp.description = 'Section of customize Ramps'
        _sock_inp_Enable_Custom_Ramp = nt.interface.new_socket(name='Enable Custom Ramp', in_out='INPUT', socket_type='NodeSocketBool', parent=_panel_Ramp)
        _sock_inp_Enable_Custom_Ramp.default_value = False
        _sock_inp_Custom_Ramp = nt.interface.new_socket(name='Custom Ramp', in_out='INPUT', socket_type='NodeSocketColor', parent=_panel_Ramp)
        _sock_inp_Custom_Ramp.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Blend_With_Custom_Ramp = nt.interface.new_socket(name='Blend With Custom Ramp', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Ramp)
        _sock_inp_Blend_With_Custom_Ramp.default_value = 1.0
        _sock_inp_Blend_With_Custom_Ramp.min_value = 0.0
        _sock_inp_Blend_With_Custom_Ramp.max_value = 1.0
        _sock_inp_Blend_With_Custom_Ramp.subtype = 'FACTOR'

        Group_004 = nt.nodes.new('ShaderNodeGroup')
        Group_004.location = (252.78, -692.63)
        Group_004.hide = True
        Group_004.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Group_004.inputs[0].default_value = False
        Group_004.inputs[2].default_value = 0.0

        Group_002 = nt.nodes.new('ShaderNodeGroup')
        Group_002.location = (253.6, -376.4)
        Group_002.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Group_002.inputs[0].default_value = False
        Group_002.inputs[2].default_value = 0.0

        Group_001 = nt.nodes.new('ShaderNodeGroup')
        Group_001.location = (253.93, -218.27)
        Group_001.node_tree = ensure_node_group('.lscherry.core.Toon Core')
        Group_001.inputs[0].default_value = 1.0
        Group_001.inputs[1].default_value = 0.0

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (7848.03, 335.88)
        Group_Output.is_active_output = True

        Group_027 = nt.nodes.new('ShaderNodeGroup')
        Group_027.location = (151.12, -84.71)
        Group_027.node_tree = ensure_node_group('.lscherry.utils.bnodes.Limit Color Value')
        Group_027.inputs[2].default_value = 0.44999998807907104

        Mix_008 = nt.nodes.new('ShaderNodeMix')
        Mix_008.location = (319.16, -66.56)
        Mix_008.hide = True
        Mix_008.data_type = 'RGBA'
        Mix_008.factor_mode = 'UNIFORM'
        Mix_008.blend_type = 'MULTIPLY'
        Mix_008.clamp_factor = True
        Mix_008.clamp_result = False
        Mix_008.inputs[0].default_value = 1.0
        Mix_008.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_008.inputs[2].default_value = 0.0
        Mix_008.inputs[3].default_value = 0.0
        Mix_008.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_008.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_008.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_008.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_006 = nt.nodes.new('ShaderNodeMix')
        Mix_006.location = (313.69, -94.45)
        Mix_006.hide = True
        Mix_006.data_type = 'RGBA'
        Mix_006.factor_mode = 'UNIFORM'
        Mix_006.blend_type = 'MULTIPLY'
        Mix_006.clamp_factor = True
        Mix_006.clamp_result = False
        Mix_006.inputs[0].default_value = 1.0
        Mix_006.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_006.inputs[2].default_value = 0.0
        Mix_006.inputs[3].default_value = 0.0
        Mix_006.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_006.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_006.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_006.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_026 = nt.nodes.new('ShaderNodeGroup')
        Group_026.location = (144.42, -153.49)
        Group_026.node_tree = ensure_node_group('.lscherry.utils.bnodes.Limit Color Value')
        Group_026.inputs[2].default_value = 0.8999999761581421

        Mix_001 = nt.nodes.new('ShaderNodeMix')
        Mix_001.location = (730.55, -253.21)
        Mix_001.data_type = 'RGBA'
        Mix_001.factor_mode = 'UNIFORM'
        Mix_001.blend_type = 'MIX'
        Mix_001.clamp_factor = True
        Mix_001.clamp_result = False
        Mix_001.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_001.inputs[2].default_value = 0.0
        Mix_001.inputs[3].default_value = 0.0
        Mix_001.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_004 = nt.nodes.new('ShaderNodeMix')
        Mix_004.location = (249.06, -340.08)
        Mix_004.label = 'Add Base Color'
        Mix_004.data_type = 'RGBA'
        Mix_004.factor_mode = 'UNIFORM'
        Mix_004.blend_type = 'MULTIPLY'
        Mix_004.clamp_factor = True
        Mix_004.clamp_result = False
        Mix_004.inputs[0].default_value = 1.0
        Mix_004.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_004.inputs[2].default_value = 0.0
        Mix_004.inputs[3].default_value = 0.0
        Mix_004.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_004.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_004.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_004.inputs[9].default_value = (0.0, 0.0, 0.0)

        Invert_Color = nt.nodes.new('ShaderNodeInvert')
        Invert_Color.location = (253.01, -165.24)
        Invert_Color.inputs[0].default_value = 1.0

        Mix_005 = nt.nodes.new('ShaderNodeMix')
        Mix_005.location = (168.67, -36.37)
        Mix_005.label = 'Add Rim Color'
        Mix_005.data_type = 'RGBA'
        Mix_005.factor_mode = 'UNIFORM'
        Mix_005.blend_type = 'MULTIPLY'
        Mix_005.clamp_factor = True
        Mix_005.clamp_result = False
        Mix_005.inputs[0].default_value = 1.0
        Mix_005.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_005.inputs[2].default_value = 0.0
        Mix_005.inputs[3].default_value = 0.0
        Mix_005.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_005.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_005.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_005.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_002 = nt.nodes.new('ShaderNodeMix')
        Mix_002.location = (491.8, -104.28)
        Mix_002.label = 'Add Shadow Color'
        Mix_002.data_type = 'RGBA'
        Mix_002.factor_mode = 'UNIFORM'
        Mix_002.blend_type = 'MULTIPLY'
        Mix_002.clamp_factor = True
        Mix_002.clamp_result = False
        Mix_002.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_002.inputs[2].default_value = 0.0
        Mix_002.inputs[3].default_value = 0.0
        Mix_002.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_015 = nt.nodes.new('ShaderNodeMix')
        Mix_015.location = (37.37, -36.0)
        Mix_015.data_type = 'RGBA'
        Mix_015.factor_mode = 'UNIFORM'
        Mix_015.blend_type = 'MULTIPLY'
        Mix_015.clamp_factor = True
        Mix_015.clamp_result = False
        Mix_015.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_015.inputs[2].default_value = 0.0
        Mix_015.inputs[3].default_value = 0.0
        Mix_015.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_015.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_015.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_015.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_012 = nt.nodes.new('ShaderNodeMix')
        Mix_012.location = (30.14, -445.01)
        Mix_012.data_type = 'RGBA'
        Mix_012.factor_mode = 'UNIFORM'
        Mix_012.blend_type = 'MULTIPLY'
        Mix_012.clamp_factor = True
        Mix_012.clamp_result = False
        Mix_012.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_012.inputs[2].default_value = 0.0
        Mix_012.inputs[3].default_value = 0.0
        Mix_012.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_012.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_012.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_012.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_013 = nt.nodes.new('ShaderNodeMix')
        Mix_013.location = (37.37, -813.76)
        Mix_013.data_type = 'RGBA'
        Mix_013.factor_mode = 'UNIFORM'
        Mix_013.blend_type = 'MULTIPLY'
        Mix_013.clamp_factor = True
        Mix_013.clamp_result = False
        Mix_013.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_013.inputs[2].default_value = 0.0
        Mix_013.inputs[3].default_value = 0.0
        Mix_013.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_013.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_013.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_013.inputs[9].default_value = (0.0, 0.0, 0.0)

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (5210.95, -39.98)
        Math.label = 'x 2'
        Math.hide = True
        Math.operation = 'MULTIPLY'
        Math.use_clamp = False
        Math.inputs[1].default_value = 2.0
        Math.inputs[2].default_value = 0.5

        Math_001 = nt.nodes.new('ShaderNodeMath')
        Math_001.location = (5208.92, -1.98)
        Math_001.label = 'Invert'
        Math_001.hide = True
        Math_001.operation = 'SUBTRACT'
        Math_001.use_clamp = False
        Math_001.inputs[0].default_value = 1.0
        Math_001.inputs[2].default_value = 0.5

        Math_003 = nt.nodes.new('ShaderNodeMath')
        Math_003.location = (5425.33, 92.49)
        Math_003.operation = 'MULTIPLY'
        Math_003.use_clamp = False
        Math_003.inputs[2].default_value = 0.5

        Group_Input_008 = nt.nodes.new('NodeGroupInput')
        Group_Input_008.location = (251.7, -279.45)

        Mix_014 = nt.nodes.new('ShaderNodeMix')
        Mix_014.location = (37.37, -1131.65)
        Mix_014.data_type = 'RGBA'
        Mix_014.factor_mode = 'UNIFORM'
        Mix_014.blend_type = 'MULTIPLY'
        Mix_014.clamp_factor = True
        Mix_014.clamp_result = False
        Mix_014.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_014.inputs[2].default_value = 0.0
        Mix_014.inputs[3].default_value = 0.0
        Mix_014.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_014.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_014.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_014.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_Input_006 = nt.nodes.new('NodeGroupInput')
        Group_Input_006.location = (29.73, -214.77)
        Group_Input_006.width = 80.0

        Mix_009 = nt.nodes.new('ShaderNodeMix')
        Mix_009.location = (30.08, -35.62)
        Mix_009.data_type = 'RGBA'
        Mix_009.factor_mode = 'UNIFORM'
        Mix_009.blend_type = 'ADD'
        Mix_009.clamp_factor = True
        Mix_009.clamp_result = False
        Mix_009.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_009.inputs[2].default_value = 0.0
        Mix_009.inputs[3].default_value = 0.0
        Mix_009.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_009.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_009.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_009.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_011 = nt.nodes.new('ShaderNodeMix')
        Mix_011.location = (30.18, -35.62)
        Mix_011.data_type = 'RGBA'
        Mix_011.factor_mode = 'UNIFORM'
        Mix_011.blend_type = 'ADD'
        Mix_011.clamp_factor = True
        Mix_011.clamp_result = False
        Mix_011.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_011.inputs[2].default_value = 0.0
        Mix_011.inputs[3].default_value = 0.0
        Mix_011.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_011.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_011.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_011.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_017 = nt.nodes.new('ShaderNodeMix')
        Mix_017.location = (6924.16, 15.01)
        Mix_017.hide = True
        Mix_017.data_type = 'RGBA'
        Mix_017.factor_mode = 'UNIFORM'
        Mix_017.blend_type = 'MULTIPLY'
        Mix_017.clamp_factor = True
        Mix_017.clamp_result = False
        Mix_017.inputs[0].default_value = 1.0
        Mix_017.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_017.inputs[2].default_value = 0.0
        Mix_017.inputs[3].default_value = 0.0
        Mix_017.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_017.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_017.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_017.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_016 = nt.nodes.new('ShaderNodeMix')
        Mix_016.location = (30.49, -35.62)
        Mix_016.label = 'Combine Emission'
        Mix_016.data_type = 'RGBA'
        Mix_016.factor_mode = 'UNIFORM'
        Mix_016.blend_type = 'ADD'
        Mix_016.clamp_factor = True
        Mix_016.clamp_result = False
        Mix_016.inputs[0].default_value = 1.0
        Mix_016.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_016.inputs[2].default_value = 0.0
        Mix_016.inputs[3].default_value = 0.0
        Mix_016.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_016.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_016.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_016.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_010 = nt.nodes.new('ShaderNodeMix')
        Mix_010.location = (30.21, -35.62)
        Mix_010.data_type = 'RGBA'
        Mix_010.factor_mode = 'UNIFORM'
        Mix_010.blend_type = 'ADD'
        Mix_010.clamp_factor = True
        Mix_010.clamp_result = False
        Mix_010.inputs[0].default_value = 1.0
        Mix_010.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_010.inputs[2].default_value = 0.0
        Mix_010.inputs[3].default_value = 0.0
        Mix_010.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_010.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_010.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_010.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_009 = nt.nodes.new('ShaderNodeGroup')
        Group_009.location = (29.5, -35.91)
        Group_009.node_tree = ensure_node_group('.lscherry.utils.ramp_style.Back Style')
        Group_009.inputs[4].default_value = 0.8999999761581421
        Group_009.inputs[5].default_value = 1.0
        Group_009.inputs[6].default_value = 0.75
        Group_009.inputs[7].default_value = 0.800000011920929

        Mix_021 = nt.nodes.new('ShaderNodeMix')
        Mix_021.location = (649.76, 144.87)
        Mix_021.label = 'Pattern'
        Mix_021.hide = True
        Mix_021.data_type = 'RGBA'
        Mix_021.factor_mode = 'UNIFORM'
        Mix_021.blend_type = 'MULTIPLY'
        Mix_021.clamp_factor = True
        Mix_021.clamp_result = False
        Mix_021.inputs[0].default_value = 1.0
        Mix_021.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_021.inputs[2].default_value = 0.0
        Mix_021.inputs[3].default_value = 0.0
        Mix_021.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_021.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_021.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_021.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_023 = nt.nodes.new('ShaderNodeMix')
        Mix_023.location = (649.76, -136.39)
        Mix_023.label = 'Pattern'
        Mix_023.hide = True
        Mix_023.data_type = 'RGBA'
        Mix_023.factor_mode = 'UNIFORM'
        Mix_023.blend_type = 'MULTIPLY'
        Mix_023.clamp_factor = True
        Mix_023.clamp_result = False
        Mix_023.inputs[0].default_value = 1.0
        Mix_023.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_023.inputs[2].default_value = 0.0
        Mix_023.inputs[3].default_value = 0.0
        Mix_023.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_023.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_023.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_023.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_Input_021 = nt.nodes.new('NodeGroupInput')
        Group_Input_021.location = (451.24, 51.08)

        Group_Input_002 = nt.nodes.new('NodeGroupInput')
        Group_Input_002.location = (34.03, -36.02)

        Group_Input_010 = nt.nodes.new('NodeGroupInput')
        Group_Input_010.location = (29.8, -176.7)
        Group_Input_010.width = 80.0

        Group_Input_013 = nt.nodes.new('NodeGroupInput')
        Group_Input_013.location = (29.8, -233.8)
        Group_Input_013.width = 80.0

        Group_Input_007 = nt.nodes.new('NodeGroupInput')
        Group_Input_007.location = (29.74, -512.9)

        Group_Input_011 = nt.nodes.new('NodeGroupInput')
        Group_Input_011.location = (31.13, -106.16)
        Group_Input_011.width = 80.0

        Group_Input_014 = nt.nodes.new('NodeGroupInput')
        Group_Input_014.location = (30.46, -164.61)
        Group_Input_014.width = 80.0

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (5203.87, 62.09)

        Group_Input_016 = nt.nodes.new('NodeGroupInput')
        Group_Input_016.location = (6924.16, -13.93)

        Group_Input_020 = nt.nodes.new('NodeGroupInput')
        Group_Input_020.location = (241.86, -275.16)
        Group_Input_020.width = 116.8
        Group_Input_020.hide = True

        Mix_020 = nt.nodes.new('ShaderNodeMix')
        Mix_020.location = (374.91, -272.82)
        Mix_020.width = 100.0
        Mix_020.hide = True
        Mix_020.data_type = 'RGBA'
        Mix_020.factor_mode = 'UNIFORM'
        Mix_020.blend_type = 'MULTIPLY'
        Mix_020.clamp_factor = True
        Mix_020.clamp_result = False
        Mix_020.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_020.inputs[2].default_value = 0.0
        Mix_020.inputs[3].default_value = 0.0
        Mix_020.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_020.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_020.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_020.inputs[9].default_value = (0.0, 0.0, 0.0)

        Invert_Color_001 = nt.nodes.new('ShaderNodeInvert')
        Invert_Color_001.location = (374.91, -234.23)
        Invert_Color_001.width = 100.0
        Invert_Color_001.hide = True
        Invert_Color_001.inputs[0].default_value = 1.0

        Group_003 = nt.nodes.new('ShaderNodeGroup')
        Group_003.location = (570.2, -100.17)
        Group_003.width = 86.99
        Group_003.hide = True
        Group_003.node_tree = ensure_node_group('.lscherry.utils.bnodes.Blend It')

        Group_019 = nt.nodes.new('ShaderNodeGroup')
        Group_019.location = (531.92, -814.68)
        Group_019.hide = True
        Group_019.node_tree = ensure_node_group('.lscherry.utils.bnodes.Value Enhance')

        Mix_018 = nt.nodes.new('ShaderNodeMix')
        Mix_018.location = (933.95, -203.87)
        Mix_018.data_type = 'RGBA'
        Mix_018.factor_mode = 'UNIFORM'
        Mix_018.blend_type = 'MIX'
        Mix_018.clamp_factor = True
        Mix_018.clamp_result = False
        Mix_018.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_018.inputs[2].default_value = 0.0
        Mix_018.inputs[3].default_value = 0.0
        Mix_018.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_018.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_018.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_018.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_013 = nt.nodes.new('ShaderNodeGroup')
        Group_013.location = (243.53, -65.35)
        Group_013.node_tree = ensure_node_group('.lscherry.utils.ramp_style.Toon Style')
        Group_013.inputs[4].default_value = 0.8999999761581421
        Group_013.inputs[5].default_value = 0.10000000149011612
        Group_013.inputs[6].default_value = 0.0
        Group_013.inputs[7].default_value = 0.0

        Group_017 = nt.nodes.new('ShaderNodeGroup')
        Group_017.location = (30.2, -36.01)
        Group_017.node_tree = ensure_node_group('.lscherry.utils.ramp_style.SSS Style')
        Group_017.inputs[4].default_value = 0.15000000596046448
        Group_017.inputs[5].default_value = 5.0

        Group_Input_027 = nt.nodes.new('NodeGroupInput')
        Group_Input_027.location = (567.67, -322.67)

        Mix_007 = nt.nodes.new('ShaderNodeMix')
        Mix_007.location = (567.67, -411.49)
        Mix_007.label = 'Mix Custom And Dot'
        Mix_007.hide = True
        Mix_007.data_type = 'RGBA'
        Mix_007.factor_mode = 'UNIFORM'
        Mix_007.blend_type = 'MIX'
        Mix_007.clamp_factor = True
        Mix_007.clamp_result = False
        Mix_007.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_007.inputs[2].default_value = 0.0
        Mix_007.inputs[3].default_value = 0.0
        Mix_007.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_007.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_007.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_007.inputs[9].default_value = (0.0, 0.0, 0.0)

        Vector_Math = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math.location = (252.78, -656.32)
        Vector_Math.hide = True
        Vector_Math.operation = 'LENGTH'
        Vector_Math.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math.inputs[3].default_value = 1.0

        Mix_019 = nt.nodes.new('ShaderNodeMix')
        Mix_019.location = (548.13, -690.65)
        Mix_019.hide = True
        Mix_019.data_type = 'RGBA'
        Mix_019.factor_mode = 'UNIFORM'
        Mix_019.blend_type = 'MIX'
        Mix_019.clamp_factor = True
        Mix_019.clamp_result = False
        Mix_019.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_019.inputs[2].default_value = 0.0
        Mix_019.inputs[3].default_value = 0.0
        Mix_019.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_019.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_019.inputs[6].default_value = (0.0, 0.0, 0.0, 1.0)
        Mix_019.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_019.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_Input_017 = nt.nodes.new('NodeGroupInput')
        Group_Input_017.location = (6138.37, 29.28)

        Group_Input_009 = nt.nodes.new('NodeGroupInput')
        Group_Input_009.location = (34.45, -207.2)

        Group_012 = nt.nodes.new('ShaderNodeGroup')
        Group_012.location = (35.25, -271.43)
        Group_012.hide = True
        Group_012.node_tree = ensure_node_group('.lscherry.utils.normal.Use Default Normal')

        Group_008 = nt.nodes.new('ShaderNodeGroup')
        Group_008.location = (226.16, -363.65)
        Group_008.hide = True
        Group_008.node_tree = ensure_node_group('.lscherry.utils.procedural.Stylized Fresnel')
        Group_008.inputs[1].default_value = (0.0, 0.0, 0.0)

        Group_Input_015 = nt.nodes.new('NodeGroupInput')
        Group_Input_015.location = (30.41, -331.03)

        Group_Input_022 = nt.nodes.new('NodeGroupInput')
        Group_Input_022.location = (565.87, -35.56)
        Group_Input_022.width = 80.0

        Group_Input_003 = nt.nodes.new('NodeGroupInput')
        Group_Input_003.location = (30.33, -1244.19)
        Group_Input_003.width = 132.28

        Mix_024 = nt.nodes.new('ShaderNodeMix')
        Mix_024.location = (137.42, -44.62)
        Mix_024.hide = True
        Mix_024.data_type = 'RGBA'
        Mix_024.factor_mode = 'UNIFORM'
        Mix_024.blend_type = 'MULTIPLY'
        Mix_024.clamp_factor = True
        Mix_024.clamp_result = False
        Mix_024.inputs[0].default_value = 1.0
        Mix_024.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_024.inputs[2].default_value = 0.0
        Mix_024.inputs[3].default_value = 0.0
        Mix_024.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_024.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_024.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_024.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (197.14, -100.82)
        Mix.hide = True
        Mix.data_type = 'FLOAT'
        Mix.factor_mode = 'UNIFORM'
        Mix.blend_type = 'MIX'
        Mix.clamp_factor = True
        Mix.clamp_result = False
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[3].default_value = 1.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[6].default_value = (0.5, 0.5, 0.5, 1.0)
        Mix.inputs[7].default_value = (0.5, 0.5, 0.5, 1.0)
        Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Separate_Color = nt.nodes.new('ShaderNodeSeparateColor')
        Separate_Color.location = (197.14, -67.13)
        Separate_Color.hide = True
        Separate_Color.mode = 'HSV'

        Mix_025 = nt.nodes.new('ShaderNodeMix')
        Mix_025.location = (137.86, -45.07)
        Mix_025.hide = True
        Mix_025.data_type = 'RGBA'
        Mix_025.factor_mode = 'UNIFORM'
        Mix_025.blend_type = 'MULTIPLY'
        Mix_025.clamp_factor = True
        Mix_025.clamp_result = False
        Mix_025.inputs[0].default_value = 1.0
        Mix_025.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_025.inputs[2].default_value = 0.0
        Mix_025.inputs[3].default_value = 0.0
        Mix_025.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_025.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_025.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_025.inputs[9].default_value = (0.0, 0.0, 0.0)

        Separate_Color_001 = nt.nodes.new('ShaderNodeSeparateColor')
        Separate_Color_001.location = (39.12, -56.09)
        Separate_Color_001.hide = True
        Separate_Color_001.mode = 'HSV'

        Combine_Color = nt.nodes.new('ShaderNodeCombineColor')
        Combine_Color.location = (419.16, -59.56)
        Combine_Color.width = 100.0
        Combine_Color.hide = True
        Combine_Color.mode = 'HSV'

        Separate_Color_002 = nt.nodes.new('ShaderNodeSeparateColor')
        Separate_Color_002.location = (4456.6, -16.76)
        Separate_Color_002.hide = True
        Separate_Color_002.mode = 'HSV'

        Math_002 = nt.nodes.new('ShaderNodeMath')
        Math_002.location = (198.16, -68.18)
        Math_002.width = 151.08
        Math_002.label = 'x1.2 (Up value 4toon)'
        Math_002.hide = True
        Math_002.operation = 'MULTIPLY'
        Math_002.use_clamp = False
        Math_002.inputs[1].default_value = 1.2000000476837158
        Math_002.inputs[2].default_value = 0.5

        Map_Range_001 = nt.nodes.new('ShaderNodeMapRange')
        Map_Range_001.location = (4456.6, -57.53)
        Map_Range_001.hide = True
        Map_Range_001.clamp = True
        Map_Range_001.interpolation_type = 'LINEAR'
        Map_Range_001.data_type = 'FLOAT'
        Map_Range_001.inputs[1].default_value = 0.0
        Map_Range_001.inputs[2].default_value = 1.0
        Map_Range_001.inputs[4].default_value = 1.0
        Map_Range_001.inputs[5].default_value = 4.0
        Map_Range_001.inputs[6].default_value = (0.0, 0.0, 0.0)
        Map_Range_001.inputs[7].default_value = (0.0, 0.0, 0.0)
        Map_Range_001.inputs[8].default_value = (1.0, 1.0, 1.0)
        Map_Range_001.inputs[9].default_value = (0.0, 0.0, 0.0)
        Map_Range_001.inputs[10].default_value = (1.0, 1.0, 1.0)
        Map_Range_001.inputs[11].default_value = (4.0, 4.0, 4.0)

        Value = nt.nodes.new('ShaderNodeValue')
        Value.location = (4287.1, -93.24)
        Value.label = 'Threshhold'

        Math_004 = nt.nodes.new('ShaderNodeMath')
        Math_004.location = (198.16, -102.71)
        Math_004.width = 100.0
        Math_004.hide = True
        Math_004.operation = 'MULTIPLY'
        Math_004.use_clamp = False
        Math_004.inputs[2].default_value = 0.5

        Mix_026 = nt.nodes.new('ShaderNodeMix')
        Mix_026.location = (933.95, -431.25)
        Mix_026.data_type = 'RGBA'
        Mix_026.factor_mode = 'UNIFORM'
        Mix_026.blend_type = 'MIX'
        Mix_026.clamp_factor = True
        Mix_026.clamp_result = False
        Mix_026.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_026.inputs[2].default_value = 0.0
        Mix_026.inputs[3].default_value = 0.0
        Mix_026.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_026.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_026.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_026.inputs[9].default_value = (0.0, 0.0, 0.0)

        Math_005 = nt.nodes.new('ShaderNodeMath')
        Math_005.location = (6137.7, -100.01)
        Math_005.hide = True
        Math_005.operation = 'MULTIPLY'
        Math_005.use_clamp = False
        Math_005.inputs[2].default_value = 0.5

        Group_028 = nt.nodes.new('ShaderNodeGroup')
        Group_028.location = (249.09, -48.45)
        Group_028.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Group_028.inputs[0].default_value = True
        Group_028.inputs[2].default_value = 0.0

        Fresnel_003 = nt.nodes.new('ShaderNodeFresnel')
        Fresnel_003.location = (32.49, -245.44)
        Fresnel_003.inputs[1].default_value = (0.0, 0.0, 0.0)

        Mix_028 = nt.nodes.new('ShaderNodeMix')
        Mix_028.location = (205.21, -151.69)
        Mix_028.data_type = 'RGBA'
        Mix_028.factor_mode = 'UNIFORM'
        Mix_028.blend_type = 'MULTIPLY'
        Mix_028.clamp_factor = True
        Mix_028.clamp_result = False
        Mix_028.inputs[0].default_value = 1.0
        Mix_028.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_028.inputs[2].default_value = 0.0
        Mix_028.inputs[3].default_value = 0.0
        Mix_028.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_028.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_028.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_028.inputs[9].default_value = (0.0, 0.0, 0.0)

        Map_Range_006 = nt.nodes.new('ShaderNodeMapRange')
        Map_Range_006.location = (30.47, -350.56)
        Map_Range_006.clamp = True
        Map_Range_006.interpolation_type = 'LINEAR'
        Map_Range_006.data_type = 'FLOAT'
        Map_Range_006.inputs[2].default_value = 1.0
        Map_Range_006.inputs[3].default_value = 0.0
        Map_Range_006.inputs[4].default_value = 1.0
        Map_Range_006.inputs[5].default_value = 4.0
        Map_Range_006.inputs[6].default_value = (0.0, 0.0, 0.0)
        Map_Range_006.inputs[7].default_value = (0.0, 0.0, 0.0)
        Map_Range_006.inputs[8].default_value = (1.0, 1.0, 1.0)
        Map_Range_006.inputs[9].default_value = (0.0, 0.0, 0.0)
        Map_Range_006.inputs[10].default_value = (1.0, 1.0, 1.0)
        Map_Range_006.inputs[11].default_value = (4.0, 4.0, 4.0)

        Map_Range_007 = nt.nodes.new('ShaderNodeMapRange')
        Map_Range_007.location = (372.73, -173.99)
        Map_Range_007.clamp = True
        Map_Range_007.interpolation_type = 'LINEAR'
        Map_Range_007.data_type = 'FLOAT'
        Map_Range_007.inputs[2].default_value = 0.10000000149011612
        Map_Range_007.inputs[3].default_value = 0.0
        Map_Range_007.inputs[5].default_value = 4.0
        Map_Range_007.inputs[6].default_value = (0.0, 0.0, 0.0)
        Map_Range_007.inputs[7].default_value = (0.0, 0.0, 0.0)
        Map_Range_007.inputs[8].default_value = (1.0, 1.0, 1.0)
        Map_Range_007.inputs[9].default_value = (0.0, 0.0, 0.0)
        Map_Range_007.inputs[10].default_value = (1.0, 1.0, 1.0)
        Map_Range_007.inputs[11].default_value = (4.0, 4.0, 4.0)

        Math_006 = nt.nodes.new('ShaderNodeMath')
        Math_006.location = (36.22, -209.12)
        Math_006.hide = True
        Math_006.operation = 'MULTIPLY'
        Math_006.use_clamp = False
        Math_006.inputs[1].default_value = -1.0
        Math_006.inputs[2].default_value = 0.5

        Math_007 = nt.nodes.new('ShaderNodeMath')
        Math_007.location = (366.6, -136.97)
        Math_007.hide = True
        Math_007.operation = 'DIVIDE'
        Math_007.use_clamp = False
        Math_007.inputs[1].default_value = 10.0
        Math_007.inputs[2].default_value = 0.5

        Map_Range = nt.nodes.new('ShaderNodeMapRange')
        Map_Range.location = (35.77, -158.36)
        Map_Range.hide = True
        Map_Range.clamp = True
        Map_Range.interpolation_type = 'LINEAR'
        Map_Range.data_type = 'FLOAT'
        Map_Range.inputs[1].default_value = 0.0
        Map_Range.inputs[2].default_value = 1.0
        Map_Range.inputs[3].default_value = 1.0010000467300415
        Map_Range.inputs[4].default_value = 1.5
        Map_Range.inputs[5].default_value = 4.0
        Map_Range.inputs[6].default_value = (0.0, 0.0, 0.0)
        Map_Range.inputs[7].default_value = (0.0, 0.0, 0.0)
        Map_Range.inputs[8].default_value = (1.0, 1.0, 1.0)
        Map_Range.inputs[9].default_value = (0.0, 0.0, 0.0)
        Map_Range.inputs[10].default_value = (1.0, 1.0, 1.0)
        Map_Range.inputs[11].default_value = (4.0, 4.0, 4.0)

        Group_023__Attribute_004 = nt.nodes.new('ShaderNodeAttribute')
        Group_023__Attribute_004.location = (23.57, -151.28)
        Group_023__Attribute_004.label = 'Value Enhance'
        Group_023__Attribute_004.hide = True
        Group_023__Attribute_004.attribute_type = 'GEOMETRY'
        Group_023__Attribute_004.attribute_name = 'valEnh'

        Group_023__Attribute_005 = nt.nodes.new('ShaderNodeAttribute')
        Group_023__Attribute_005.location = (-258.41, -292.87)
        Group_023__Attribute_005.label = 'World Color'
        Group_023__Attribute_005.hide = True
        Group_023__Attribute_005.attribute_type = 'GEOMETRY'
        Group_023__Attribute_005.attribute_name = 'wCol'

        Group_023__Group = nt.nodes.new('ShaderNodeGroup')
        Group_023__Group.location = (-427.83, -276.72)
        Group_023__Group.hide = True
        Group_023__Group.node_tree = ensure_node_group('.lscherry.utils.bnodes.Background Color')

        Group_023__Mix_003 = nt.nodes.new('ShaderNodeMix')
        Group_023__Mix_003.location = (-253.24, -253.39)
        Group_023__Mix_003.hide = True
        Group_023__Mix_003.data_type = 'RGBA'
        Group_023__Mix_003.factor_mode = 'UNIFORM'
        Group_023__Mix_003.blend_type = 'ADD'
        Group_023__Mix_003.clamp_factor = True
        Group_023__Mix_003.clamp_result = False
        Group_023__Mix_003.inputs[1].default_value = (0.5, 0.5, 0.5)
        Group_023__Mix_003.inputs[2].default_value = 0.0
        Group_023__Mix_003.inputs[3].default_value = 0.0
        Group_023__Mix_003.inputs[4].default_value = (0.0, 0.0, 0.0)
        Group_023__Mix_003.inputs[5].default_value = (0.0, 0.0, 0.0)
        Group_023__Mix_003.inputs[7].default_value = (1.0, 1.0, 1.0, 1.0)
        Group_023__Mix_003.inputs[8].default_value = (0.0, 0.0, 0.0)
        Group_023__Mix_003.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_023__Attribute_006 = nt.nodes.new('ShaderNodeAttribute')
        Group_023__Attribute_006.location = (-430.35, -239.75)
        Group_023__Attribute_006.label = 'World Value Enhance'
        Group_023__Attribute_006.hide = True
        Group_023__Attribute_006.attribute_type = 'GEOMETRY'
        Group_023__Attribute_006.attribute_name = 'wValEnh'

        Group_023__Mix_007 = nt.nodes.new('ShaderNodeMix')
        Group_023__Mix_007.location = (24.55, -244.4)
        Group_023__Mix_007.hide = True
        Group_023__Mix_007.data_type = 'RGBA'
        Group_023__Mix_007.factor_mode = 'UNIFORM'
        Group_023__Mix_007.blend_type = 'MIX'
        Group_023__Mix_007.clamp_factor = True
        Group_023__Mix_007.clamp_result = False
        Group_023__Mix_007.inputs[1].default_value = (0.5, 0.5, 0.5)
        Group_023__Mix_007.inputs[2].default_value = 0.0
        Group_023__Mix_007.inputs[3].default_value = 0.0
        Group_023__Mix_007.inputs[4].default_value = (0.0, 0.0, 0.0)
        Group_023__Mix_007.inputs[5].default_value = (0.0, 0.0, 0.0)
        Group_023__Mix_007.inputs[8].default_value = (0.0, 0.0, 0.0)
        Group_023__Mix_007.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_023__Attribute_008 = nt.nodes.new('ShaderNodeAttribute')
        Group_023__Attribute_008.location = (-844.8, -123.71)
        Group_023__Attribute_008.label = 'Blend Mode'
        Group_023__Attribute_008.hide = True
        Group_023__Attribute_008.attribute_type = 'GEOMETRY'
        Group_023__Attribute_008.attribute_name = 'blendM'

        Group_023__Math = nt.nodes.new('ShaderNodeMath')
        Group_023__Math.location = (-608.11, -168.08)
        Group_023__Math.label = 'Light Sources'
        Group_023__Math.hide = True
        Group_023__Math.operation = 'COMPARE'
        Group_023__Math.use_clamp = False
        Group_023__Math.inputs[1].default_value = 1.0
        Group_023__Math.inputs[2].default_value = 0.0

        Group_023__Math_001 = nt.nodes.new('ShaderNodeMath')
        Group_023__Math_001.location = (-608.32, -129.77)
        Group_023__Math_001.label = 'Background'
        Group_023__Math_001.hide = True
        Group_023__Math_001.operation = 'COMPARE'
        Group_023__Math_001.use_clamp = False
        Group_023__Math_001.inputs[1].default_value = 2.0
        Group_023__Math_001.inputs[2].default_value = 0.0

        Group_023__Math_002 = nt.nodes.new('ShaderNodeMath')
        Group_023__Math_002.location = (-608.11, -92.43)
        Group_023__Math_002.label = 'None'
        Group_023__Math_002.hide = True
        Group_023__Math_002.operation = 'COMPARE'
        Group_023__Math_002.use_clamp = False
        Group_023__Math_002.inputs[1].default_value = 3.0
        Group_023__Math_002.inputs[2].default_value = 0.0

        Group_023__Math_003 = nt.nodes.new('ShaderNodeMath')
        Group_023__Math_003.location = (-268.37, -94.07)
        Group_023__Math_003.hide = True
        Group_023__Math_003.operation = 'SUBTRACT'
        Group_023__Math_003.use_clamp = False
        Group_023__Math_003.inputs[0].default_value = 1.0
        Group_023__Math_003.inputs[2].default_value = 0.5

        Group_018__Mix_004 = nt.nodes.new('ShaderNodeMix')
        Group_018__Mix_004.location = (695.77, 207.06)
        Group_018__Mix_004.data_type = 'RGBA'
        Group_018__Mix_004.factor_mode = 'UNIFORM'
        Group_018__Mix_004.blend_type = 'ADD'
        Group_018__Mix_004.clamp_factor = True
        Group_018__Mix_004.clamp_result = False
        Group_018__Mix_004.inputs[1].default_value = (0.5, 0.5, 0.5)
        Group_018__Mix_004.inputs[2].default_value = 0.0
        Group_018__Mix_004.inputs[3].default_value = 0.0
        Group_018__Mix_004.inputs[4].default_value = (0.0, 0.0, 0.0)
        Group_018__Mix_004.inputs[5].default_value = (0.0, 0.0, 0.0)
        Group_018__Mix_004.inputs[8].default_value = (0.0, 0.0, 0.0)
        Group_018__Mix_004.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_018__Mix_005 = nt.nodes.new('ShaderNodeMix')
        Group_018__Mix_005.location = (870.91, 404.94)
        Group_018__Mix_005.data_type = 'RGBA'
        Group_018__Mix_005.factor_mode = 'UNIFORM'
        Group_018__Mix_005.blend_type = 'MIX'
        Group_018__Mix_005.clamp_factor = True
        Group_018__Mix_005.clamp_result = False
        Group_018__Mix_005.inputs[1].default_value = (0.5, 0.5, 0.5)
        Group_018__Mix_005.inputs[2].default_value = 0.0
        Group_018__Mix_005.inputs[3].default_value = 0.0
        Group_018__Mix_005.inputs[4].default_value = (0.0, 0.0, 0.0)
        Group_018__Mix_005.inputs[5].default_value = (0.0, 0.0, 0.0)
        Group_018__Mix_005.inputs[8].default_value = (0.0, 0.0, 0.0)
        Group_018__Mix_005.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_018__Group = nt.nodes.new('ShaderNodeGroup')
        Group_018__Group.location = (15.26, -33.57)
        Group_018__Group.node_tree = ensure_node_group('.lscherry.utils.normal.Use Default Normal')

        Group_018__Group_004 = nt.nodes.new('ShaderNodeGroup')
        Group_018__Group_004.location = (207.59, 95.91)
        Group_018__Group_004.node_tree = ensure_node_group('.lscherry.core.Specular Dot')

        Group_018__Attribute = nt.nodes.new('ShaderNodeAttribute')
        Group_018__Attribute.location = (15.26, 89.44)
        Group_018__Attribute.attribute_type = 'GEOMETRY'
        Group_018__Attribute.attribute_name = 'm'

        Group_018__Map_Range_001 = nt.nodes.new('ShaderNodeMapRange')
        Group_018__Map_Range_001.location = (394.48, 119.25)
        Group_018__Map_Range_001.clamp = True
        Group_018__Map_Range_001.interpolation_type = 'LINEAR'
        Group_018__Map_Range_001.data_type = 'FLOAT'
        Group_018__Map_Range_001.inputs[2].default_value = 1.0
        Group_018__Map_Range_001.inputs[3].default_value = 0.0
        Group_018__Map_Range_001.inputs[4].default_value = 1.0
        Group_018__Map_Range_001.inputs[5].default_value = 4.0
        Group_018__Map_Range_001.inputs[6].default_value = (0.0, 0.0, 0.0)
        Group_018__Map_Range_001.inputs[7].default_value = (0.0, 0.0, 0.0)
        Group_018__Map_Range_001.inputs[8].default_value = (1.0, 1.0, 1.0)
        Group_018__Map_Range_001.inputs[9].default_value = (0.0, 0.0, 0.0)
        Group_018__Map_Range_001.inputs[10].default_value = (1.0, 1.0, 1.0)
        Group_018__Map_Range_001.inputs[11].default_value = (4.0, 4.0, 4.0)

        Group_018__Math = nt.nodes.new('ShaderNodeMath')
        Group_018__Math.location = (207.23, -30.13)
        Group_018__Math.operation = 'SUBTRACT'
        Group_018__Math.use_clamp = False
        Group_018__Math.inputs[0].default_value = 1.0
        Group_018__Math.inputs[2].default_value = 0.5

        Group_025__Attribute_001 = nt.nodes.new('ShaderNodeAttribute')
        Group_025__Attribute_001.location = (0.0, -123.16)
        Group_025__Attribute_001.hide = True
        Group_025__Attribute_001.attribute_type = 'GEOMETRY'
        Group_025__Attribute_001.attribute_name = 'tn'

        Group_025__Attribute_002 = nt.nodes.new('ShaderNodeAttribute')
        Group_025__Attribute_002.location = (0.0, 22.36)
        Group_025__Attribute_002.hide = True
        Group_025__Attribute_002.attribute_type = 'GEOMETRY'
        Group_025__Attribute_002.attribute_name = 'm'

        Group_025__Attribute_003 = nt.nodes.new('ShaderNodeAttribute')
        Group_025__Attribute_003.location = (0.0, -13.01)
        Group_025__Attribute_003.hide = True
        Group_025__Attribute_003.attribute_type = 'GEOMETRY'
        Group_025__Attribute_003.attribute_name = 'b'

        Group_025__Attribute_004 = nt.nodes.new('ShaderNodeAttribute')
        Group_025__Attribute_004.location = (0.0, -49.85)
        Group_025__Attribute_004.hide = True
        Group_025__Attribute_004.attribute_type = 'GEOMETRY'
        Group_025__Attribute_004.attribute_name = 'fx'

        Group_025__Attribute_005 = nt.nodes.new('ShaderNodeAttribute')
        Group_025__Attribute_005.location = (0.0, -85.91)
        Group_025__Attribute_005.hide = True
        Group_025__Attribute_005.attribute_type = 'GEOMETRY'
        Group_025__Attribute_005.attribute_name = 'fy'


        nt.links.new(Group_012.outputs['Normal'], Group_004.inputs['Normal'])
        nt.links.new(Group_012.outputs['Normal'], Group_002.inputs['Normal'])
        nt.links.new(Group_012.outputs['Normal'], Group_001.inputs['Normal'])
        nt.links.new(Mix_016.outputs['Result'], Group_Output.inputs['Combined'])
        nt.links.new(Group_002.outputs['NdotL'], Group_Output.inputs['Diffuse Mask'])
        nt.links.new(Group_019.outputs['Enhanced Shading'], Group_Output.inputs['Post Diffuse Mask'])
        nt.links.new(Group_017.outputs['Shading'], Group_Output.inputs['SSS Mask'])
        nt.links.new(Map_Range_007.outputs['Result'], Group_Output.inputs['Rim Mask'])
        nt.links.new(Mix_023.outputs['Result'], Group_Output.inputs['Back Mask'])
        nt.links.new(Group_001.outputs['Toon'], Group_Output.inputs['Light Sources Mask'])
        nt.links.new(Group_Input_011.outputs['Back Color'], Group_027.inputs['Target Color'])
        nt.links.new(Group_Input_014.outputs['Base Color'], Group_027.inputs['Limit Color'])
        nt.links.new(Mix_025.outputs['Result'], Mix_008.inputs['A'])
        nt.links.new(Group_027.outputs['Limited Color'], Mix_008.inputs['B'])
        nt.links.new(Mix_024.outputs['Result'], Mix_006.inputs['A'])
        nt.links.new(Group_026.outputs['Limited Color'], Mix_006.inputs['B'])
        nt.links.new(Group_Input_010.outputs['SSS Color'], Group_026.inputs['Target Color'])
        nt.links.new(Group_Input_013.outputs['Base Color'], Group_026.inputs['Limit Color'])
        nt.links.new(Group_019.outputs['Enhanced Shading'], Mix_001.inputs['Factor'])
        nt.links.new(Mix_002.outputs['Result'], Mix_001.inputs['A'])
        nt.links.new(Mix_004.outputs['Result'], Mix_001.inputs['B'])
        nt.links.new(Group_019.outputs['Enhanced Shading'], Mix_004.inputs['A'])
        nt.links.new(Group_Input_007.outputs['Base Color'], Mix_004.inputs['B'])
        nt.links.new(Group_019.outputs['Enhanced Shading'], Invert_Color.inputs['Color'])
        nt.links.new(Map_Range_007.outputs['Result'], Mix_005.inputs['A'])
        nt.links.new(Group_Input_006.outputs['Rim Color'], Mix_005.inputs['B'])
        nt.links.new(Invert_Color.outputs['Color'], Mix_002.inputs['Factor'])
        nt.links.new(Group_Input_007.outputs['Base Color'], Mix_002.inputs['A'])
        nt.links.new(Group_Input_008.outputs['Shadow Color'], Mix_002.inputs['B'])
        nt.links.new(Mix_005.outputs['Result'], Mix_015.inputs['A'])
        nt.links.new(Map_Range_001.outputs['Result'], Mix_015.inputs['B'])
        nt.links.new(Mix_018.outputs['Result'], Mix_012.inputs['A'])
        nt.links.new(Map_Range_001.outputs['Result'], Mix_012.inputs['B'])
        nt.links.new(Mix_006.outputs['Result'], Mix_013.inputs['A'])
        nt.links.new(Map_Range_001.outputs['Result'], Mix_013.inputs['B'])
        nt.links.new(Group_017.outputs['Shading'], Math.inputs['Value'])
        nt.links.new(Group_Input_001.outputs['Enable Custom Ramp'], Math_001.inputs['Value'])
        nt.links.new(Math_001.outputs['Value'], Math_003.inputs['Value'])
        nt.links.new(Math.outputs['Value'], Math_003.inputs['Value'])
        nt.links.new(Map_Range_001.outputs['Result'], Mix_014.inputs['A'])
        nt.links.new(Mix_008.outputs['Result'], Mix_014.inputs['B'])
        nt.links.new(Math_003.outputs['Value'], Mix_009.inputs['Factor'])
        nt.links.new(Mix_012.outputs['Result'], Mix_009.inputs['A'])
        nt.links.new(Mix_013.outputs['Result'], Mix_009.inputs['B'])
        nt.links.new(Mix_009.outputs['Result'], Mix_011.inputs['A'])
        nt.links.new(Mix_014.outputs['Result'], Mix_011.inputs['B'])
        nt.links.new(Group_Input_016.outputs['Emission'], Mix_017.inputs['A'])
        nt.links.new(Group_Input_016.outputs['Emission Strength'], Mix_017.inputs['B'])
        nt.links.new(Mix_010.outputs['Result'], Mix_016.inputs['A'])
        nt.links.new(Mix_017.outputs['Result'], Mix_016.inputs['B'])
        nt.links.new(Mix_015.outputs['Result'], Mix_010.inputs['B'])
        nt.links.new(Group_Input_003.outputs['Disable Back Style'], Group_009.inputs['Disable Back Style'])
        nt.links.new(Mix_023.outputs['Result'], Group_009.inputs['Shading'])
        nt.links.new(Group_008.outputs['Fresnel'], Group_009.inputs['Fresnel (Required)'])
        nt.links.new(Group_Input_003.outputs['Back Style'], Group_009.inputs['Back Style'])
        nt.links.new(Mix_007.outputs['Result'], Mix_021.inputs['A'])
        nt.links.new(Group_Input_021.outputs['Pattern'], Mix_021.inputs['B'])
        nt.links.new(Mix_019.outputs['Result'], Mix_023.inputs['A'])
        nt.links.new(Group_Input_021.outputs['Pattern'], Mix_023.inputs['B'])
        nt.links.new(Invert_Color_001.outputs['Color'], Mix_020.inputs['Factor'])
        nt.links.new(Group_Input_020.outputs['Base Color'], Mix_020.inputs['A'])
        nt.links.new(Group_Input_020.outputs['Shadow Color'], Mix_020.inputs['B'])
        nt.links.new(Group_019.outputs['Enhanced Shading'], Invert_Color_001.inputs['Color'])
        nt.links.new(Group_Input_022.outputs['Blend With Custom Ramp'], Group_003.inputs['Fac'])
        nt.links.new(Mix_020.outputs['Result'], Group_003.inputs['Color A'])
        nt.links.new(Combine_Color.outputs['Color'], Group_003.inputs['Color B'])
        nt.links.new(Group_013.outputs['Shading'], Group_019.inputs['Shading'])
        nt.links.new(Group_003.outputs['Color'], Mix_018.inputs['A'])
        nt.links.new(Mix_001.outputs['Result'], Mix_018.inputs['B'])
        nt.links.new(Group_Input_003.outputs['Disable Toon Style'], Group_013.inputs['Disable Toon Style'])
        nt.links.new(Mix_021.outputs['Result'], Group_013.inputs['Shading'])
        nt.links.new(Group_008.outputs['Fresnel'], Group_013.inputs['Fresnel (Required)'])
        nt.links.new(Group_Input_003.outputs['Toon Style'], Group_013.inputs['Toon Style'])
        nt.links.new(Group_Input_003.outputs['Disable SSS Style'], Group_017.inputs['Disable SSS Style'])
        nt.links.new(Mix_021.outputs['Result'], Group_017.inputs['Shading'])
        nt.links.new(Group_013.outputs['Toon Style'], Group_017.inputs['Toon Style (If only using Toon Style)'])
        nt.links.new(Group_Input_003.outputs['SSS Style'], Group_017.inputs['SSS Style'])
        nt.links.new(Group_Input_027.outputs['Enable Custom Ramp'], Mix_007.inputs['Factor'])
        nt.links.new(Group_002.outputs['NdotL'], Mix_007.inputs['A'])
        nt.links.new(Group_Input_027.outputs['Custom Ramp'], Mix_007.inputs['B'])
        nt.links.new(Vector_Math.outputs['Value'], Mix_019.inputs['Factor'])
        nt.links.new(Group_004.outputs['NdotL'], Mix_019.inputs['B'])
        nt.links.new(Group_Input_009.outputs['Normal'], Group_012.inputs['Normal'])
        nt.links.new(Group_Input_015.outputs['Roughness'], Group_008.inputs['Roughness'])
        nt.links.new(Group_017.outputs['Shading'], Mix_024.inputs['A'])
        nt.links.new(Mix.outputs['Result'], Mix_024.inputs['B'])
        nt.links.new(Separate_Color.outputs['Blue'], Mix.inputs['A'])
        nt.links.new(Group_001.outputs['Toon'], Separate_Color.inputs['Color'])
        nt.links.new(Group_009.outputs['Shading'], Mix_025.inputs['A'])
        nt.links.new(Mix.outputs['Result'], Mix_025.inputs['B'])
        nt.links.new(Group_001.outputs['Toon'], Separate_Color_001.inputs['Color'])
        nt.links.new(Separate_Color_001.outputs['Red'], Combine_Color.inputs['Red'])
        nt.links.new(Math_002.outputs['Value'], Combine_Color.inputs['Green'])
        nt.links.new(Math_004.outputs['Value'], Combine_Color.inputs['Blue'])
        nt.links.new(Separate_Color_001.outputs['Green'], Math_002.inputs['Value'])
        nt.links.new(Separate_Color_002.outputs['Blue'], Map_Range_001.inputs['Value'])
        nt.links.new(Value.outputs['Value'], Map_Range_001.inputs['To Min'])
        nt.links.new(Separate_Color_001.outputs['Blue'], Math_004.inputs['Value'])
        nt.links.new(Group_019.outputs['Enhanced Shading'], Math_004.inputs['Value'])
        nt.links.new(Math_004.outputs['Value'], Mix_026.inputs['A'])
        nt.links.new(Group_019.outputs['Enhanced Shading'], Mix_026.inputs['B'])
        nt.links.new(Group_Input_017.outputs['Specular Tint'], Math_005.inputs['Value'])
        nt.links.new(Mix_026.outputs['Result'], Math_005.inputs['Value'])
        nt.links.new(Group_012.outputs['Normal'], Group_028.inputs['Normal'])
        nt.links.new(Map_Range.outputs['Result'], Fresnel_003.inputs['IOR'])
        nt.links.new(Fresnel_003.outputs['Factor'], Mix_028.inputs['A'])
        nt.links.new(Map_Range_006.outputs['Result'], Mix_028.inputs['B'])
        nt.links.new(Group_028.outputs['NdotL'], Map_Range_006.inputs['Value'])
        nt.links.new(Math_006.outputs['Value'], Map_Range_006.inputs['From Min'])
        nt.links.new(Mix_028.outputs['Result'], Map_Range_007.inputs['Value'])
        nt.links.new(Math_007.outputs['Value'], Map_Range_007.inputs['From Min'])
        nt.links.new(Group_Input_002.outputs['Rim Strength'], Map_Range_007.inputs['To Max'])
        nt.links.new(Group_Input_002.outputs['Rim Size'], Math_006.inputs['Value'])
        nt.links.new(Group_Input_002.outputs['Rim Smooth'], Math_007.inputs['Value'])
        nt.links.new(Group_Input_002.outputs['Rim Size'], Map_Range.inputs['Value'])
        nt.links.new(Group_023__Math_003.outputs['Value'], Mix_011.inputs['Factor'])
        nt.links.new(Group_023__Math_003.outputs['Value'], Mix_018.inputs['Factor'])
        nt.links.new(Group_023__Math_003.outputs['Value'], Mix.inputs['Factor'])
        nt.links.new(Group_023__Math_003.outputs['Value'], Mix_026.inputs['Factor'])
        nt.links.new(Group_023__Attribute_004.outputs['Factor'], Group_019.inputs['Value Enhance'])
        nt.links.new(Group_023__Mix_007.outputs['Result'], Separate_Color_002.inputs['Color'])
        nt.links.new(Group_023__Attribute_006.outputs['Factor'], Group_023__Mix_003.inputs['Factor'])
        nt.links.new(Group_023__Group.outputs['Stylized'], Group_023__Mix_003.inputs['A'])
        nt.links.new(Group_023__Math_002.outputs['Value'], Group_023__Mix_007.inputs['Factor'])
        nt.links.new(Group_023__Mix_003.outputs['Result'], Group_023__Mix_007.inputs['A'])
        nt.links.new(Group_023__Attribute_005.outputs['Color'], Group_023__Mix_007.inputs['B'])
        nt.links.new(Group_023__Attribute_008.outputs['Factor'], Group_023__Math.inputs['Value'])
        nt.links.new(Group_023__Attribute_008.outputs['Factor'], Group_023__Math_001.inputs['Value'])
        nt.links.new(Group_023__Attribute_008.outputs['Factor'], Group_023__Math_002.inputs['Value'])
        nt.links.new(Group_023__Math.outputs['Value'], Group_023__Math_003.inputs['Value'])
        nt.links.new(Group_018__Mix_005.outputs['Result'], Mix_010.inputs['A'])
        nt.links.new(Group_018__Map_Range_001.outputs['Result'], Group_018__Mix_004.inputs['Factor'])
        nt.links.new(Mix_011.outputs['Result'], Group_018__Mix_004.inputs['A'])
        nt.links.new(Group_Input_017.outputs['Specular Color'], Group_018__Mix_004.inputs['B'])
        nt.links.new(Math_005.outputs['Value'], Group_018__Mix_005.inputs['Factor'])
        nt.links.new(Mix_011.outputs['Result'], Group_018__Mix_005.inputs['A'])
        nt.links.new(Group_018__Mix_004.outputs['Result'], Group_018__Mix_005.inputs['B'])
        nt.links.new(Group_Input_017.outputs['Normal'], Group_018__Group.inputs['Normal'])
        nt.links.new(Group_018__Attribute.outputs['Vector'], Group_018__Group_004.inputs['Light Dir'])
        nt.links.new(Group_018__Group.outputs['Normal'], Group_018__Group_004.inputs['Normal'])
        nt.links.new(Group_018__Group_004.outputs['Specular'], Group_018__Map_Range_001.inputs['Value'])
        nt.links.new(Group_018__Math.outputs['Value'], Group_018__Map_Range_001.inputs['From Min'])
        nt.links.new(Group_Input_017.outputs['Roughness'], Group_018__Math.inputs['Value'])
        nt.links.new(Group_025__Attribute_002.outputs['Vector'], Group_002.inputs['Light Dir'])
        nt.links.new(Group_025__Attribute_002.outputs['Vector'], Group_028.inputs['Light Dir'])
        nt.links.new(Group_025__Attribute_003.outputs['Vector'], Group_004.inputs['Light Dir'])
        nt.links.new(Group_025__Attribute_003.outputs['Vector'], Vector_Math.inputs['Vector'])
