# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ...node import GeometryNode


class GeometryNodeCompiled_LS_Outline_And_ShrinkWarp(GeometryNode):
    bl_idname = 'GeometryNodeCompiled_LS_Outline_And_ShrinkWarp'
    bl_label = 'lscherry.LS Outline And ShrinkWarp'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'LS Outline And ShrinkWarp'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Ratio'].default_value = 1.2000000476837158
        self.inputs['Affected Vertex'].default_value = False
        self.inputs['Strength'].default_value = 1.0

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'GeometryNodeTree'
        )
        nt.color_tag = 'GEOMETRY'

        _sock_out_Geometry = nt.interface.new_socket(name='Geometry', in_out='OUTPUT', socket_type='NodeSocketGeometry')
        _sock_inp_Geometry = nt.interface.new_socket(name='Geometry', in_out='INPUT', socket_type='NodeSocketGeometry')
        _sock_inp_Outlined_Material = nt.interface.new_socket(name='Outlined Material', in_out='INPUT', socket_type='NodeSocketMaterial')
        _sock_inp_Ratio = nt.interface.new_socket(name='Ratio', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Ratio.default_value = 1.2000000476837158
        _sock_inp_Ratio.min_value = 0.0
        _sock_inp_Ratio.max_value = 100.0
        _sock_inp_Affected_Vertex = nt.interface.new_socket(name='Affected Vertex', in_out='INPUT', socket_type='NodeSocketBool')
        _sock_inp_Affected_Vertex.default_value = False
        _sock_inp_Affected_Vertex.hide_value = True
        _sock_inp_Shrink_To = nt.interface.new_socket(name='Shrink To', in_out='INPUT', socket_type='NodeSocketObject')
        _sock_inp_Strength = nt.interface.new_socket(name='Strength', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Strength.default_value = 1.0
        _sock_inp_Strength.min_value = 0.0
        _sock_inp_Strength.max_value = 100.0

        Set_Material = nt.nodes.new('GeometryNodeSetMaterial')
        Set_Material.location = (-238.66, -106.72)

        Math_002 = nt.nodes.new('ShaderNodeMath')
        Math_002.location = (-837.09, -128.9)
        Math_002.label = 'Invert'
        Math_002.hide = True
        Math_002.operation = 'SUBTRACT'
        Math_002.use_clamp = False
        Math_002.inputs[0].default_value = 1.0
        Math_002.inputs[2].default_value = 0.5

        Set_Position = nt.nodes.new('GeometryNodeSetPosition')
        Set_Position.location = (-448.43, -68.23)
        Set_Position.inputs[2].default_value = (0.0, 0.0, 0.0)

        Flip_Faces = nt.nodes.new('GeometryNodeFlipFaces')
        Flip_Faces.location = (-14.68, -80.93)

        Join_Geometry = nt.nodes.new('GeometryNodeJoinGeometry')
        Join_Geometry.location = (169.66, 20.22)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-2176.09, 20.22)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (347.63, 18.9)

        Normal = nt.nodes.new('GeometryNodeInputNormal')
        Normal.location = (216.04, -199.33)

        Group_Input_002 = nt.nodes.new('NodeGroupInput')
        Group_Input_002.location = (-449.73, -279.25)

        Group_Input_003 = nt.nodes.new('NodeGroupInput')
        Group_Input_003.location = (29.9, -131.42)

        Vector_Math = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math.location = (419.49, -85.53)
        Vector_Math.operation = 'SCALE'
        Vector_Math.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math.inputs[2].default_value = (0.0, 0.0, 0.0)

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (218.29, -39.79)
        Math.operation = 'DIVIDE'
        Math.use_clamp = False
        Math.inputs[1].default_value = 1000.0
        Math.inputs[2].default_value = 0.5

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (-836.23, -66.32)

        Object_Info = nt.nodes.new('GeometryNodeObjectInfo')
        Object_Info.location = (30.01, -154.31)
        Object_Info.transform_space = 'RELATIVE'
        Object_Info.inputs[1].default_value = False

        Geometry_Proximity = nt.nodes.new('GeometryNodeProximity')
        Geometry_Proximity.location = (204.44, -151.75)
        Geometry_Proximity.inputs[1].default_value = 0
        Geometry_Proximity.inputs[2].default_value = (0.0, 0.0, 0.0)
        Geometry_Proximity.inputs[3].default_value = 0

        Set_Position_001 = nt.nodes.new('GeometryNodeSetPosition')
        Set_Position_001.location = (539.83, -40.26)
        Set_Position_001.inputs[1].default_value = True

        Vector_Math_001 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_001.location = (386.25, -206.08)
        Vector_Math_001.operation = 'MULTIPLY'
        Vector_Math_001.inputs[1].default_value = (0.10000000149011612, 0.10000000149011612, 0.10000000149011612)
        Vector_Math_001.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_001.inputs[3].default_value = 1.0

        Vector_Math_002 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_002.location = (198.16, -265.86)
        Vector_Math_002.operation = 'SCALE'
        Vector_Math_002.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math_002.inputs[2].default_value = (0.0, 0.0, 0.0)

        Normal_001 = nt.nodes.new('GeometryNodeInputNormal')
        Normal_001.location = (30.01, -275.62)

        Group_Input_004 = nt.nodes.new('NodeGroupInput')
        Group_Input_004.location = (30.01, -334.83)


        nt.links.new(Set_Position.outputs['Geometry'], Set_Material.inputs['Geometry'])
        nt.links.new(Math_002.outputs['Value'], Set_Material.inputs['Selection'])
        nt.links.new(Group_Input_002.outputs['Outlined Material'], Set_Material.inputs['Material'])
        nt.links.new(Group_Input_001.outputs['Affected Vertex'], Math_002.inputs['Value'])
        nt.links.new(Set_Position_001.outputs['Geometry'], Set_Position.inputs['Geometry'])
        nt.links.new(Math_002.outputs['Value'], Set_Position.inputs['Selection'])
        nt.links.new(Vector_Math.outputs['Vector'], Set_Position.inputs['Offset'])
        nt.links.new(Set_Material.outputs['Geometry'], Flip_Faces.inputs['Mesh'])
        nt.links.new(Math_002.outputs['Value'], Flip_Faces.inputs['Selection'])
        nt.links.new(Set_Position_001.outputs['Geometry'], Join_Geometry.inputs['Geometry'])
        nt.links.new(Join_Geometry.outputs['Geometry'], Group_Output.inputs['Geometry'])
        nt.links.new(Normal.outputs['Normal'], Vector_Math.inputs['Vector'])
        nt.links.new(Math.outputs['Value'], Vector_Math.inputs['Scale'])
        nt.links.new(Group_Input_003.outputs['Ratio'], Math.inputs['Value'])
        nt.links.new(Group_Input.outputs['Shrink To'], Object_Info.inputs['Object'])
        nt.links.new(Object_Info.outputs['Geometry'], Geometry_Proximity.inputs['Geometry'])
        nt.links.new(Group_Input.outputs['Geometry'], Set_Position_001.inputs['Geometry'])
        nt.links.new(Geometry_Proximity.outputs['Position'], Set_Position_001.inputs['Position'])
        nt.links.new(Vector_Math_001.outputs['Vector'], Set_Position_001.inputs['Offset'])
        nt.links.new(Vector_Math_002.outputs['Vector'], Vector_Math_001.inputs['Vector'])
        nt.links.new(Normal_001.outputs['Normal'], Vector_Math_002.inputs['Vector'])
        nt.links.new(Group_Input_004.outputs['Strength'], Vector_Math_002.inputs['Scale'])
