# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ..node import GeometryNode


class GeometryNodeCompiled_LSCherryProvider(GeometryNode):
    bl_label = 'lscherry.Core.LSCherryProvider'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Blend Mode'].default_value = 1
        self.inputs['Value Enhance'].default_value = 0.10000000149011612
        self.inputs['World Value Enhance'].default_value = 0.0
        self.inputs['World Color'].default_value = (1.0, 1.0, 1.0, 1.0)

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'GeometryNodeTree'
        )
        nt.color_tag = 'ATTRIBUTE'

        _sock_out_Geometry = nt.interface.new_socket(name='Geometry', in_out='OUTPUT', socket_type='NodeSocketGeometry')
        _sock_inp_Geometry = nt.interface.new_socket(name='Geometry', in_out='INPUT', socket_type='NodeSocketGeometry')
        _sock_inp_Main_Light_Dot = nt.interface.new_socket(name='Main Light Dot', in_out='INPUT', socket_type='NodeSocketObject')
        _sock_inp_Back_Light_Dot = nt.interface.new_socket(name='Back Light Dot', in_out='INPUT', socket_type='NodeSocketObject')
        _sock_inp_Main_Head = nt.interface.new_socket(name='Main Head', in_out='INPUT', socket_type='NodeSocketObject')
        _sock_inp_Sub_Head_X = nt.interface.new_socket(name='Sub Head-X', in_out='INPUT', socket_type='NodeSocketObject')
        _sock_inp_Sub_Head_Y = nt.interface.new_socket(name='Sub Head-Y', in_out='INPUT', socket_type='NodeSocketObject')
        _sock_inp_Blend_Mode = nt.interface.new_socket(name='Blend Mode', in_out='INPUT', socket_type='NodeSocketInt')
        _sock_inp_Blend_Mode.default_value = 1
        _sock_inp_Blend_Mode.min_value = 1
        _sock_inp_Blend_Mode.max_value = 3
        _sock_inp_Value_Enhance = nt.interface.new_socket(name='Value Enhance', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Value_Enhance.default_value = 0.10000000149011612
        _sock_inp_Value_Enhance.min_value = 0.0
        _sock_inp_Value_Enhance.max_value = 1.0
        _sock_inp_World_Value_Enhance = nt.interface.new_socket(name='World Value Enhance', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_World_Value_Enhance.default_value = 0.0
        _sock_inp_World_Value_Enhance.min_value = 0.0
        _sock_inp_World_Value_Enhance.max_value = 1.0
        _sock_inp_World_Color = nt.interface.new_socket(name='World Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_World_Color.default_value = (1.0, 1.0, 1.0, 1.0)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-789.18, -804.77)

        Object_Info_004 = nt.nodes.new('GeometryNodeObjectInfo')
        Object_Info_004.location = (30.29, -39.54)
        Object_Info_004.label = 'headPivot'
        Object_Info_004.hide = True
        Object_Info_004.transform_space = 'ORIGINAL'
        Object_Info_004.inputs[1].default_value = False

        Vector_Math_001 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_001.location = (-1.62, -1000.07)
        Vector_Math_001.hide = True
        Vector_Math_001.operation = 'SUBTRACT'
        Vector_Math_001.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_001.inputs[3].default_value = 1.0

        Vector_Math = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math.location = (-1.62, -948.68)
        Vector_Math.hide = True
        Vector_Math.operation = 'SUBTRACT'
        Vector_Math.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math.inputs[3].default_value = 1.0

        Object_Info = nt.nodes.new('GeometryNodeObjectInfo')
        Object_Info.location = (29.84, -40.23)
        Object_Info.label = 'mainLightDir'
        Object_Info.hide = True
        Object_Info.transform_space = 'ORIGINAL'
        Object_Info.inputs[1].default_value = False

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1078.84, -805.87)

        Object_Info_003 = nt.nodes.new('GeometryNodeObjectInfo')
        Object_Info_003.location = (30.29, -39.64)
        Object_Info_003.label = 'headPivot'
        Object_Info_003.hide = True
        Object_Info_003.transform_space = 'ORIGINAL'
        Object_Info_003.inputs[1].default_value = False

        Object_Info_001 = nt.nodes.new('GeometryNodeObjectInfo')
        Object_Info_001.location = (30.29, -39.57)
        Object_Info_001.label = 'backLightDir'
        Object_Info_001.hide = True
        Object_Info_001.transform_space = 'ORIGINAL'
        Object_Info_001.inputs[1].default_value = False

        Object_Info_005 = nt.nodes.new('GeometryNodeObjectInfo')
        Object_Info_005.location = (30.29, -39.71)
        Object_Info_005.label = 'headPivot'
        Object_Info_005.hide = True
        Object_Info_005.transform_space = 'ORIGINAL'
        Object_Info_005.inputs[1].default_value = False

        Store_Named_Attribute = nt.nodes.new('GeometryNodeStoreNamedAttribute')
        Store_Named_Attribute.location = (226.22, -707.61)
        Store_Named_Attribute.inputs[1].default_value = True
        Store_Named_Attribute.inputs[2].default_value = 'm'

        Store_Named_Attribute_001 = nt.nodes.new('GeometryNodeStoreNamedAttribute')
        Store_Named_Attribute_001.location = (425.85, -707.61)
        Store_Named_Attribute_001.inputs[1].default_value = True
        Store_Named_Attribute_001.inputs[2].default_value = 'b'

        Store_Named_Attribute_002 = nt.nodes.new('GeometryNodeStoreNamedAttribute')
        Store_Named_Attribute_002.location = (599.69, -707.61)
        Store_Named_Attribute_002.inputs[1].default_value = True
        Store_Named_Attribute_002.inputs[2].default_value = 'fx'

        Store_Named_Attribute_003 = nt.nodes.new('GeometryNodeStoreNamedAttribute')
        Store_Named_Attribute_003.location = (785.8, -707.61)
        Store_Named_Attribute_003.inputs[1].default_value = True
        Store_Named_Attribute_003.inputs[2].default_value = 'fy'

        Store_Named_Attribute_004 = nt.nodes.new('GeometryNodeStoreNamedAttribute')
        Store_Named_Attribute_004.location = (242.27, -1132.63)
        Store_Named_Attribute_004.inputs[1].default_value = True
        Store_Named_Attribute_004.inputs[2].default_value = 'blendM'

        Store_Named_Attribute_005 = nt.nodes.new('GeometryNodeStoreNamedAttribute')
        Store_Named_Attribute_005.location = (425.85, -1132.63)
        Store_Named_Attribute_005.inputs[1].default_value = True
        Store_Named_Attribute_005.inputs[2].default_value = 'valEnh'

        Store_Named_Attribute_006 = nt.nodes.new('GeometryNodeStoreNamedAttribute')
        Store_Named_Attribute_006.location = (599.69, -1132.63)
        Store_Named_Attribute_006.inputs[1].default_value = True
        Store_Named_Attribute_006.inputs[2].default_value = 'wValEnh'

        Store_Named_Attribute_007 = nt.nodes.new('GeometryNodeStoreNamedAttribute')
        Store_Named_Attribute_007.location = (785.8, -1132.63)
        Store_Named_Attribute_007.inputs[1].default_value = True
        Store_Named_Attribute_007.inputs[2].default_value = 'wCol'


        nt.links.new(Group_Input.outputs['Sub Head-X'], Object_Info_004.inputs['Object'])
        nt.links.new(Object_Info_003.outputs['Location'], Vector_Math_001.inputs['Vector'])
        nt.links.new(Object_Info_005.outputs['Location'], Vector_Math_001.inputs['Vector'])
        nt.links.new(Object_Info_004.outputs['Location'], Vector_Math.inputs['Vector'])
        nt.links.new(Object_Info_003.outputs['Location'], Vector_Math.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Main Light Dot'], Object_Info.inputs['Object'])
        nt.links.new(Store_Named_Attribute_007.outputs['Geometry'], Group_Output.inputs['Geometry'])
        nt.links.new(Group_Input.outputs['Main Head'], Object_Info_003.inputs['Object'])
        nt.links.new(Group_Input.outputs['Back Light Dot'], Object_Info_001.inputs['Object'])
        nt.links.new(Group_Input.outputs['Sub Head-Y'], Object_Info_005.inputs['Object'])
        nt.links.new(Group_Input.outputs['Geometry'], Store_Named_Attribute.inputs['Geometry'])
        nt.links.new(Object_Info.outputs['Rotation'], Store_Named_Attribute.inputs['Value'])
        nt.links.new(Store_Named_Attribute.outputs['Geometry'], Store_Named_Attribute_001.inputs['Geometry'])
        nt.links.new(Object_Info_001.outputs['Rotation'], Store_Named_Attribute_001.inputs['Value'])
        nt.links.new(Store_Named_Attribute_001.outputs['Geometry'], Store_Named_Attribute_002.inputs['Geometry'])
        nt.links.new(Vector_Math.outputs['Vector'], Store_Named_Attribute_002.inputs['Value'])
        nt.links.new(Store_Named_Attribute_002.outputs['Geometry'], Store_Named_Attribute_003.inputs['Geometry'])
        nt.links.new(Vector_Math_001.outputs['Vector'], Store_Named_Attribute_003.inputs['Value'])
        nt.links.new(Store_Named_Attribute_003.outputs['Geometry'], Store_Named_Attribute_004.inputs['Geometry'])
        nt.links.new(Group_Input.outputs['Blend Mode'], Store_Named_Attribute_004.inputs['Value'])
        nt.links.new(Store_Named_Attribute_004.outputs['Geometry'], Store_Named_Attribute_005.inputs['Geometry'])
        nt.links.new(Group_Input.outputs['Value Enhance'], Store_Named_Attribute_005.inputs['Value'])
        nt.links.new(Store_Named_Attribute_005.outputs['Geometry'], Store_Named_Attribute_006.inputs['Geometry'])
        nt.links.new(Group_Input.outputs['World Value Enhance'], Store_Named_Attribute_006.inputs['Value'])
        nt.links.new(Store_Named_Attribute_006.outputs['Geometry'], Store_Named_Attribute_007.inputs['Geometry'])
        nt.links.new(Group_Input.outputs['World Color'], Store_Named_Attribute_007.inputs['Value'])
