# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ...node import ShaderNode, ensure_node_group


class ShaderNodeCompiled_Stacked_Toon_Builder(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Stacked_Toon_Builder'
    bl_label = 'lscherry.Stacked Toon Builder'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Stacked Toon Builder'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Pattern'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Enable Dot'].default_value = False
        self.inputs['Normal'].default_value = (0.0, 0.0, 0.0)

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'SHADER'

        _sock_out_Shading = nt.interface.new_socket(name='Shading', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Shading.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_inp_Pattern = nt.interface.new_socket(name='Pattern', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Pattern.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Pattern.hide_value = True
        _sock_inp_Enable_Dot = nt.interface.new_socket(name='Enable Dot', in_out='INPUT', socket_type='NodeSocketBool')
        _sock_inp_Enable_Dot.default_value = False
        _sock_inp_Normal = nt.interface.new_socket(name='Normal', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Normal.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Normal.min_value = -10000.0
        _sock_inp_Normal.max_value = 10000.0
        _sock_inp_Normal.hide_value = True
        _sock_inp_Normal.dimensions = 3

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (722.86, 88.47)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (338.76, 204.42)

        Group_013 = nt.nodes.new('ShaderNodeGroup')
        Group_013.location = (112.66, 207.96)
        Group_013.node_tree = ensure_node_group('.lscherry.core.Toon Core')
        Group_013.inputs[0].default_value = 1.0
        Group_013.inputs[1].default_value = 0.0

        Group_014 = nt.nodes.new('ShaderNodeGroup')
        Group_014.location = (112.66, 59.04)
        Group_014.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Group_014.inputs[0].default_value = False
        Group_014.inputs[2].default_value = 0.0

        Group_015 = nt.nodes.new('ShaderNodeGroup')
        Group_015.location = (-169.65, -197.87)
        Group_015.hide = True
        Group_015.node_tree = ensure_node_group('.lscherry.utils.normal.Use Default Normal')

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (338.76, 146.14)
        Mix.data_type = 'RGBA'
        Mix.factor_mode = 'UNIFORM'
        Mix.blend_type = 'MIX'
        Mix.clamp_factor = True
        Mix.clamp_result = False
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Mix_002 = nt.nodes.new('ShaderNodeMix')
        Mix_002.location = (522.32, 144.95)
        Mix_002.data_type = 'RGBA'
        Mix_002.factor_mode = 'UNIFORM'
        Mix_002.blend_type = 'MULTIPLY'
        Mix_002.clamp_factor = True
        Mix_002.clamp_result = False
        Mix_002.inputs[0].default_value = 1.0
        Mix_002.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_002.inputs[2].default_value = 0.0
        Mix_002.inputs[3].default_value = 0.0
        Mix_002.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (338.76, -85.5)

        Group_Input_002 = nt.nodes.new('NodeGroupInput')
        Group_Input_002.location = (-169.65, -136.42)

        Group_009__Attribute_001 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_001.location = (0.0, -123.16)
        Group_009__Attribute_001.hide = True
        Group_009__Attribute_001.attribute_type = 'GEOMETRY'
        Group_009__Attribute_001.attribute_name = 'tn'

        Group_009__Attribute_002 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_002.location = (0.0, 22.36)
        Group_009__Attribute_002.hide = True
        Group_009__Attribute_002.attribute_type = 'GEOMETRY'
        Group_009__Attribute_002.attribute_name = 'm'

        Group_009__Attribute_003 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_003.location = (0.0, -13.01)
        Group_009__Attribute_003.hide = True
        Group_009__Attribute_003.attribute_type = 'GEOMETRY'
        Group_009__Attribute_003.attribute_name = 'b'

        Group_009__Attribute_004 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_004.location = (0.0, -49.85)
        Group_009__Attribute_004.hide = True
        Group_009__Attribute_004.attribute_type = 'GEOMETRY'
        Group_009__Attribute_004.attribute_name = 'fx'

        Group_009__Attribute_005 = nt.nodes.new('ShaderNodeAttribute')
        Group_009__Attribute_005.location = (0.0, -85.91)
        Group_009__Attribute_005.hide = True
        Group_009__Attribute_005.attribute_type = 'GEOMETRY'
        Group_009__Attribute_005.attribute_name = 'fy'


        nt.links.new(Mix_002.outputs[2], Group_Output.inputs['Shading'])
        nt.links.new(Group_015.outputs['Normal'], Group_013.inputs['Normal'])
        nt.links.new(Group_015.outputs['Normal'], Group_014.inputs['Normal'])
        nt.links.new(Group_Input_002.outputs['Normal'], Group_015.inputs['Normal'])
        nt.links.new(Group_Input.outputs['Enable Dot'], Mix.inputs[0])
        nt.links.new(Group_013.outputs['Toon'], Mix.inputs[6])
        nt.links.new(Group_014.outputs['NdotL'], Mix.inputs[7])
        nt.links.new(Mix.outputs[2], Mix_002.inputs[6])
        nt.links.new(Group_Input_001.outputs['Pattern'], Mix_002.inputs[7])
        nt.links.new(Group_009__Attribute_002.outputs['Vector'], Group_014.inputs['Light Dir'])
