# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ..node import ShaderNode


class ShaderNodeCompiled_XTR__Parallax_UV(ShaderNode):
    bl_label = 'lscherry.XTR: Parallax UV'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['UV Map'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Tangent UV'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Distance'].default_value = 0.0

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'VECTOR'

        _sock_out_Parallax_UV = nt.interface.new_socket(name='Parallax UV', in_out='OUTPUT', socket_type='NodeSocketVector')
        _sock_out_Parallax_UV.default_value = (0.0, 0.0, 0.0)
        _sock_out_Parallax_UV.min_value = -3.4028234663852886e+38
        _sock_out_Parallax_UV.max_value = 3.4028234663852886e+38
        _sock_out_Parallax_UV.dimensions = 3
        _sock_inp_UV_Map = nt.interface.new_socket(name='UV Map', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_UV_Map.default_value = (0.0, 0.0, 0.0)
        _sock_inp_UV_Map.min_value = -10000.0
        _sock_inp_UV_Map.max_value = 10000.0
        _sock_inp_UV_Map.hide_value = True
        _sock_inp_UV_Map.dimensions = 3
        _sock_inp_Tangent_UV = nt.interface.new_socket(name='Tangent UV', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Tangent_UV.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Tangent_UV.min_value = -10000.0
        _sock_inp_Tangent_UV.max_value = 10000.0
        _sock_inp_Tangent_UV.hide_value = True
        _sock_inp_Tangent_UV.dimensions = 3
        _sock_inp_Distance = nt.interface.new_socket(name='Distance', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Distance.default_value = 0.0
        _sock_inp_Distance.min_value = 0.0
        _sock_inp_Distance.max_value = 100.0

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (832.83, 56.04)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-860.59, -137.42)

        Geometry = nt.nodes.new('ShaderNodeNewGeometry')
        Geometry.location = (-649.34, 73.59)

        Vector_Math = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math.location = (-369.16, -109.8)
        Vector_Math.hide = True
        Vector_Math.operation = 'CROSS_PRODUCT'
        Vector_Math.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math.inputs[3].default_value = 1.0

        Vector_Math_001 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_001.location = (-128.46, -38.05)
        Vector_Math_001.hide = True
        Vector_Math_001.operation = 'DOT_PRODUCT'
        Vector_Math_001.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_001.inputs[3].default_value = 1.0

        Vector_Math_002 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_002.location = (-128.46, -75.02)
        Vector_Math_002.hide = True
        Vector_Math_002.operation = 'DOT_PRODUCT'
        Vector_Math_002.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_002.inputs[3].default_value = 1.0

        Combine_XYZ = nt.nodes.new('ShaderNodeCombineXYZ')
        Combine_XYZ.location = (62.57, -29.36)
        Combine_XYZ.hide = True
        Combine_XYZ.inputs[2].default_value = 0.0

        Vector_Math_003 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_003.location = (238.41, 1.09)
        Vector_Math_003.hide = True
        Vector_Math_003.operation = 'TANGENT'
        Vector_Math_003.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math_003.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_003.inputs[3].default_value = 1.0

        Vector_Math_004 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_004.location = (429.44, -19.76)
        Vector_Math_004.hide = True
        Vector_Math_004.operation = 'SCALE'
        Vector_Math_004.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math_004.inputs[2].default_value = (0.0, 0.0, 0.0)

        Vector_Math_005 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_005.location = (635.03, 58.98)
        Vector_Math_005.hide = True
        Vector_Math_005.operation = 'SUBTRACT'
        Vector_Math_005.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_005.inputs[3].default_value = 1.159999966621399

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (237.57, -112.66)


        nt.links.new(Vector_Math_005.outputs['Vector'], Group_Output.inputs['Parallax UV'])
        nt.links.new(Geometry.outputs['Normal'], Vector_Math.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Tangent UV'], Vector_Math.inputs['Vector'])
        nt.links.new(Geometry.outputs['Incoming'], Vector_Math_001.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Tangent UV'], Vector_Math_001.inputs['Vector'])
        nt.links.new(Geometry.outputs['Incoming'], Vector_Math_002.inputs['Vector'])
        nt.links.new(Vector_Math.outputs['Vector'], Vector_Math_002.inputs['Vector'])
        nt.links.new(Vector_Math_001.outputs['Value'], Combine_XYZ.inputs['X'])
        nt.links.new(Vector_Math_002.outputs['Value'], Combine_XYZ.inputs['Y'])
        nt.links.new(Combine_XYZ.outputs['Vector'], Vector_Math_003.inputs['Vector'])
        nt.links.new(Vector_Math_003.outputs['Vector'], Vector_Math_004.inputs['Vector'])
        nt.links.new(Group_Input_001.outputs['Distance'], Vector_Math_004.inputs['Scale'])
        nt.links.new(Group_Input.outputs['UV Map'], Vector_Math_005.inputs['Vector'])
        nt.links.new(Vector_Math_004.outputs['Vector'], Vector_Math_005.inputs['Vector'])
