# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from .....node import ShaderNode


class ShaderNodeCompiled_Use_Override(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Use_Override'
    bl_label = 'lscherry.utils.bnodes.? Use Override'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return '? Use Override'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Condition '].default_value = 0.0
        self.inputs['Color'].default_value = (0.5, 0.5, 0.5, 1.0)
        self.inputs['Override Color'].default_value = (0.0, 0.0, 0.0, 1.0)

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'CONVERTER'

        _sock_out_Color = nt.interface.new_socket(name='Color', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Color.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_inp_Condition = nt.interface.new_socket(name='Condition ', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Condition.default_value = 0.0
        _sock_inp_Condition.min_value = 0.0
        _sock_inp_Condition.max_value = 1.0
        _sock_inp_Color = nt.interface.new_socket(name='Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Color.default_value = (0.5, 0.5, 0.5, 1.0)
        _sock_inp_Override_Color = nt.interface.new_socket(name='Override Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Override_Color.default_value = (0.0, 0.0, 0.0, 1.0)

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (292.4, 121.62)
        Mix.data_type = 'RGBA'
        Mix.factor_mode = 'UNIFORM'
        Mix.blend_type = 'MIX'
        Mix.clamp_factor = True
        Mix.clamp_result = False
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (536.14, 124.32)
        Group_Output.is_active_output = True

        Separate_Color = nt.nodes.new('ShaderNodeSeparateColor')
        Separate_Color.location = (-167.45, 138.94)
        Separate_Color.mode = 'HSV'

        Math_002 = nt.nodes.new('ShaderNodeMath')
        Math_002.location = (59.85, 165.47)
        Math_002.operation = 'GREATER_THAN'
        Math_002.use_clamp = True
        Math_002.inputs[1].default_value = 0.0
        Math_002.inputs[2].default_value = 0.5

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-388.56, 33.71)


        nt.links.new(Math_002.outputs['Value'], Mix.inputs['Factor'])
        nt.links.new(Group_Input.outputs['Color'], Mix.inputs['A'])
        nt.links.new(Group_Input.outputs['Override Color'], Mix.inputs['B'])
        nt.links.new(Mix.outputs['Result'], Group_Output.inputs['Color'])
        nt.links.new(Group_Input.outputs['Condition '], Separate_Color.inputs['Color'])
        nt.links.new(Separate_Color.outputs['Blue'], Math_002.inputs['Value'])
