# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from .....node import ShaderNode


class ShaderNodeCompiled_World_Color(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_World_Color'
    bl_label = 'lscherry.utils.bnodes.World Color'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'World Color'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Color'].default_value = (1.0, 1.0, 1.0, 1.0)
        self.inputs['Strength'].default_value = 0.0

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'INPUT'

        _sock_out_WorldColor = nt.interface.new_socket(name='WorldColor', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_WorldColor.default_value = (0.5, 0.5, 0.5, 1.0)
        _sock_inp_Color = nt.interface.new_socket(name='Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Color.default_value = (1.0, 1.0, 1.0, 1.0)
        _sock_inp_Strength = nt.interface.new_socket(name='Strength', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Strength.default_value = 0.0
        _sock_inp_Strength.min_value = 0.0
        _sock_inp_Strength.max_value = 3.4028234663852886e+38

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (172.0, 8.87)
        Mix.data_type = 'RGBA'
        Mix.factor_mode = 'UNIFORM'
        Mix.blend_type = 'MULTIPLY'
        Mix.clamp_factor = True
        Mix.clamp_result = False
        Mix.inputs[0].default_value = 1.0
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (392.18, 0.0)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-444.88, -5.09)


        nt.links.new(Group_Input.outputs['Color'], Mix.inputs[6])
        nt.links.new(Group_Input.outputs['Strength'], Mix.inputs[7])
        nt.links.new(Mix.outputs[2], Group_Output.inputs['WorldColor'])
