# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ....node import ShaderNode


class ShaderNodeCompiled_Plugin__Anisotropic_Spherical(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Plugin__Anisotropic_Spherical'
    bl_label = 'lscherry.plugin.Plugin: Anisotropic Spherical'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Plugin: Anisotropic Spherical'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Mix Various'].default_value = 0.05000000074505806
        self.inputs['Up Pattern Value'].default_value = 1.0
        self.inputs['Strength'].default_value = 0.05000000074505806
        self.inputs['Location'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Rotation'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Scale'].default_value = (1.0, 1.0, 1.0)
        self.inputs['W'].default_value = 1.0
        self.inputs['Scale'].default_value = 50.0
        self.inputs['Detail'].default_value = 15.0
        self.inputs['Roughness'].default_value = 0.20000000298023224
        self.inputs['Lacunarity'].default_value = 2.0
        self.inputs['Distortion'].default_value = 0.0

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'SCRIPT'

        _sock_out_Pattern = nt.interface.new_socket(name='Pattern', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Pattern.default_value = 0.0
        _sock_out_Pattern.min_value = -3.4028234663852886e+38
        _sock_out_Pattern.max_value = 3.4028234663852886e+38
        _sock_out_Normal = nt.interface.new_socket(name='Normal', in_out='OUTPUT', socket_type='NodeSocketVector')
        _sock_out_Normal.default_value = (0.0, 0.0, 0.0)
        _sock_out_Normal.min_value = -3.4028234663852886e+38
        _sock_out_Normal.max_value = 3.4028234663852886e+38
        _sock_out_Normal.dimensions = 3
        _sock_inp_Mix_Various = nt.interface.new_socket(name='Mix Various', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Mix_Various.default_value = 0.05000000074505806
        _sock_inp_Mix_Various.min_value = 0.0
        _sock_inp_Mix_Various.max_value = 1.0
        _sock_inp_Mix_Various.subtype = 'FACTOR'
        _sock_inp_Up_Pattern_Value = nt.interface.new_socket(name='Up Pattern Value', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Up_Pattern_Value.default_value = 1.0
        _sock_inp_Up_Pattern_Value.min_value = 0.0
        _sock_inp_Up_Pattern_Value.max_value = 1.0
        _sock_inp_Up_Pattern_Value.subtype = 'FACTOR'
        _sock_inp_Strength = nt.interface.new_socket(name='Strength', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Strength.default_value = 0.05000000074505806
        _sock_inp_Strength.min_value = 0.0
        _sock_inp_Strength.max_value = 1.0
        _sock_inp_Strength.subtype = 'FACTOR'
        _panel_Transform = nt.interface.new_panel(name='Transform', default_closed=True)
        _sock_inp_Location = nt.interface.new_socket(name='Location', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Location.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Location.min_value = -3.4028234663852886e+38
        _sock_inp_Location.max_value = 3.4028234663852886e+38
        _sock_inp_Location.subtype = 'TRANSLATION'
        _sock_inp_Location.dimensions = 3
        _sock_inp_Rotation = nt.interface.new_socket(name='Rotation', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Rotation.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Rotation.min_value = -3.4028234663852886e+38
        _sock_inp_Rotation.max_value = 3.4028234663852886e+38
        _sock_inp_Rotation.subtype = 'EULER'
        _sock_inp_Rotation.dimensions = 3
        _sock_inp_Scale = nt.interface.new_socket(name='Scale', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Scale.default_value = (1.0, 1.0, 1.0)
        _sock_inp_Scale.min_value = -3.4028234663852886e+38
        _sock_inp_Scale.max_value = 3.4028234663852886e+38
        _sock_inp_Scale.subtype = 'XYZ'
        _sock_inp_Scale.dimensions = 3
        _panel_Noise = nt.interface.new_panel(name='Noise', default_closed=True)
        _sock_inp_W = nt.interface.new_socket(name='W', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_W.default_value = 1.0
        _sock_inp_W.min_value = -1000.0
        _sock_inp_W.max_value = 1000.0
        _sock_inp_Scale = nt.interface.new_socket(name='Scale', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Scale.default_value = 50.0
        _sock_inp_Scale.min_value = -1000.0
        _sock_inp_Scale.max_value = 1000.0
        _sock_inp_Detail = nt.interface.new_socket(name='Detail', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Detail.default_value = 15.0
        _sock_inp_Detail.min_value = 0.0
        _sock_inp_Detail.max_value = 15.0
        _sock_inp_Roughness = nt.interface.new_socket(name='Roughness', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Roughness.default_value = 0.20000000298023224
        _sock_inp_Roughness.min_value = 0.0
        _sock_inp_Roughness.max_value = 1.0
        _sock_inp_Roughness.subtype = 'FACTOR'
        _sock_inp_Lacunarity = nt.interface.new_socket(name='Lacunarity', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Lacunarity.default_value = 2.0
        _sock_inp_Lacunarity.min_value = 0.0
        _sock_inp_Lacunarity.max_value = 1000.0
        _sock_inp_Distortion = nt.interface.new_socket(name='Distortion', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Distortion.default_value = 0.0
        _sock_inp_Distortion.min_value = -1000.0
        _sock_inp_Distortion.max_value = 1000.0

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (772.14, 0.0)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-578.17, -192.52)

        Gradient_Texture = nt.nodes.new('ShaderNodeTexGradient')
        Gradient_Texture.location = (-112.98, 75.98)
        Gradient_Texture.gradient_type = 'SPHERICAL'

        Mapping = nt.nodes.new('ShaderNodeMapping')
        Mapping.location = (-349.11, -11.38)
        Mapping.vector_type = 'POINT'

        Texture_Coordinate = nt.nodes.new('ShaderNodeTexCoord')
        Texture_Coordinate.location = (-571.16, -45.57)

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (51.99, 2.76)
        Mix.data_type = 'RGBA'
        Mix.blend_type = 'LINEAR_LIGHT'
        Mix.clamp_result = False
        Mix.clamp_factor = True
        Mix.factor_mode = 'UNIFORM'
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Noise_Texture = nt.nodes.new('ShaderNodeTexNoise')
        Noise_Texture.location = (212.43, -7.92)
        Noise_Texture.noise_dimensions = '4D'
        Noise_Texture.inputs[6].default_value = 0.0
        Noise_Texture.inputs[7].default_value = 1.0

        Map_Range = nt.nodes.new('ShaderNodeMapRange')
        Map_Range.location = (400.36, 127.17)
        Map_Range.data_type = 'FLOAT'
        Map_Range.interpolation_type = 'LINEAR'
        Map_Range.clamp = True
        Map_Range.inputs[1].default_value = 0.0
        Map_Range.inputs[2].default_value = 1.0
        Map_Range.inputs[3].default_value = -1.0
        Map_Range.inputs[4].default_value = 1.0
        Map_Range.inputs[5].default_value = 4.0
        Map_Range.inputs[6].default_value = (0.0, 0.0, 0.0)
        Map_Range.inputs[7].default_value = (0.0, 0.0, 0.0)
        Map_Range.inputs[8].default_value = (1.0, 1.0, 1.0)
        Map_Range.inputs[9].default_value = (0.0, 0.0, 0.0)
        Map_Range.inputs[10].default_value = (1.0, 1.0, 1.0)
        Map_Range.inputs[11].default_value = (4.0, 4.0, 4.0)

        Hue_Saturation_Value = nt.nodes.new('ShaderNodeHueSaturation')
        Hue_Saturation_Value.location = (572.14, 102.85)
        Hue_Saturation_Value.width = 150.0
        Hue_Saturation_Value.inputs[0].default_value = 0.5
        Hue_Saturation_Value.inputs[1].default_value = 1.0
        Hue_Saturation_Value.inputs[2].default_value = 2.0

        Bump = nt.nodes.new('ShaderNodeBump')
        Bump.location = (494.86, -127.17)
        Bump.invert = False
        Bump.inputs[1].default_value = 1.0
        Bump.inputs[2].default_value = 1.0
        Bump.inputs[4].default_value = (0.0, 0.0, 0.0)

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (31.46, -260.22)
        Group_Input_001.hide = True


        nt.links.new(Hue_Saturation_Value.outputs['Color'], Group_Output.inputs['Pattern'])
        nt.links.new(Bump.outputs['Normal'], Group_Output.inputs['Normal'])
        nt.links.new(Mapping.outputs['Vector'], Gradient_Texture.inputs['Vector'])
        nt.links.new(Texture_Coordinate.outputs['Object'], Mapping.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Location'], Mapping.inputs['Location'])
        nt.links.new(Group_Input.outputs['Rotation'], Mapping.inputs['Rotation'])
        nt.links.new(Group_Input.outputs['Scale'], Mapping.inputs['Scale'])
        nt.links.new(Group_Input.outputs['Mix Various'], Mix.inputs['Factor'])
        nt.links.new(Gradient_Texture.outputs['Color'], Mix.inputs['A'])
        nt.links.new(Mapping.outputs['Vector'], Mix.inputs['B'])
        nt.links.new(Mix.outputs['Result'], Noise_Texture.inputs['Vector'])
        nt.links.new(Group_Input_001.outputs['W'], Noise_Texture.inputs['W'])
        nt.links.new(Group_Input_001.outputs['Scale'], Noise_Texture.inputs['Scale'])
        nt.links.new(Group_Input_001.outputs['Detail'], Noise_Texture.inputs['Detail'])
        nt.links.new(Group_Input_001.outputs['Roughness'], Noise_Texture.inputs['Roughness'])
        nt.links.new(Group_Input_001.outputs['Lacunarity'], Noise_Texture.inputs['Lacunarity'])
        nt.links.new(Group_Input_001.outputs['Distortion'], Noise_Texture.inputs['Distortion'])
        nt.links.new(Noise_Texture.outputs['Factor'], Map_Range.inputs['Value'])
        nt.links.new(Group_Input.outputs['Up Pattern Value'], Hue_Saturation_Value.inputs['Factor'])
        nt.links.new(Map_Range.outputs['Result'], Hue_Saturation_Value.inputs['Color'])
        nt.links.new(Group_Input.outputs['Strength'], Bump.inputs['Strength'])
        nt.links.new(Noise_Texture.outputs['Factor'], Bump.inputs['Height'])
