# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ....node import ShaderNode, ensure_node_group


class ShaderNodeCompiled_Plugin__Dot_Hatching_Pattern(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Plugin__Dot_Hatching_Pattern'
    bl_label = 'lscherry.plugin.Plugin: Dot Hatching Pattern'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Plugin: Dot Hatching Pattern'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Scale'].default_value = 15.0
        self.inputs['Dot Size'].default_value = 0.4000000059604645
        self.inputs['Enable Light Dot Blend'].default_value = False
        self.inputs['Toon Style'].default_value = (0.0, 0.0, 0.0)

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'SCRIPT'

        _sock_out_Pattern = nt.interface.new_socket(name='Pattern', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Pattern.default_value = 0.0
        _sock_out_Pattern.min_value = -3.4028234663852886e+38
        _sock_out_Pattern.max_value = 3.4028234663852886e+38
        _sock_inp_Scale = nt.interface.new_socket(name='Scale', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Scale.default_value = 15.0
        _sock_inp_Scale.min_value = -1000.0
        _sock_inp_Scale.max_value = 1000.0
        _sock_inp_Dot_Size = nt.interface.new_socket(name='Dot Size', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Dot_Size.default_value = 0.4000000059604645
        _sock_inp_Dot_Size.min_value = 0.0
        _sock_inp_Dot_Size.max_value = 1.0
        _sock_inp_Dot_Size.subtype = 'FACTOR'
        _sock_inp_Enable_Light_Dot_Blend = nt.interface.new_socket(name='Enable Light Dot Blend', in_out='INPUT', socket_type='NodeSocketBool')
        _sock_inp_Enable_Light_Dot_Blend.default_value = False
        _sock_inp_Toon_Style = nt.interface.new_socket(name='Toon Style', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Toon_Style.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Toon_Style.min_value = -3.4028234663852886e+38
        _sock_inp_Toon_Style.max_value = 3.4028234663852886e+38
        _sock_inp_Toon_Style.subtype = 'XYZ'
        _sock_inp_Toon_Style.hide_value = True
        _sock_inp_Toon_Style.dimensions = 3

        Voronoi_Texture = nt.nodes.new('ShaderNodeTexVoronoi')
        Voronoi_Texture.location = (-131.39, -112.81)
        Voronoi_Texture.width = 155.0
        Voronoi_Texture.voronoi_dimensions = '2D'
        Voronoi_Texture.distance = 'EUCLIDEAN'
        Voronoi_Texture.feature = 'F1'
        Voronoi_Texture.normalize = False
        Voronoi_Texture.inputs[1].default_value = 0.0
        Voronoi_Texture.inputs[3].default_value = 0.0
        Voronoi_Texture.inputs[4].default_value = 0.5
        Voronoi_Texture.inputs[5].default_value = 2.0
        Voronoi_Texture.inputs[6].default_value = 1.0
        Voronoi_Texture.inputs[7].default_value = 0.5
        Voronoi_Texture.inputs[8].default_value = 0.0

        Map_Range = nt.nodes.new('ShaderNodeMapRange')
        Map_Range.location = (76.68, -96.19)
        Map_Range.clamp = True
        Map_Range.interpolation_type = 'LINEAR'
        Map_Range.data_type = 'FLOAT'
        Map_Range.inputs[1].default_value = 0.0
        Map_Range.inputs[2].default_value = 1.0
        Map_Range.inputs[3].default_value = 0.0
        Map_Range.inputs[4].default_value = 1.5
        Map_Range.inputs[5].default_value = 4.0
        Map_Range.inputs[6].default_value = (0.0, 0.0, 0.0)
        Map_Range.inputs[7].default_value = (0.0, 0.0, 0.0)
        Map_Range.inputs[8].default_value = (1.0, 1.0, 1.0)
        Map_Range.inputs[9].default_value = (0.0, 0.0, 0.0)
        Map_Range.inputs[10].default_value = (1.0, 1.0, 1.0)
        Map_Range.inputs[11].default_value = (4.0, 4.0, 4.0)

        Texture_Coordinate = nt.nodes.new('ShaderNodeTexCoord')
        Texture_Coordinate.location = (-309.57, -111.85)
        Texture_Coordinate.hide = True
        Texture_Coordinate.from_instancer = False

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (554.75, -15.0)
        Math.hide = True
        Math.operation = 'GREATER_THAN'
        Math.use_clamp = False
        Math.inputs[2].default_value = 0.5

        Math_001 = nt.nodes.new('ShaderNodeMath')
        Math_001.location = (-76.65, 128.7)
        Math_001.hide = True
        Math_001.operation = 'SUBTRACT'
        Math_001.use_clamp = False
        Math_001.inputs[0].default_value = 1.0
        Math_001.inputs[2].default_value = 0.5

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (994.79, -3.7)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-467.46, 2.71)

        Math_002 = nt.nodes.new('ShaderNodeMath')
        Math_002.location = (354.61, -78.82)
        Math_002.hide = True
        Math_002.operation = 'MULTIPLY'
        Math_002.use_clamp = False
        Math_002.inputs[2].default_value = 0.5

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (808.38, 126.25)
        Mix.data_type = 'FLOAT'
        Mix.factor_mode = 'UNIFORM'
        Mix.blend_type = 'MIX'
        Mix.clamp_factor = True
        Mix.clamp_result = False
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[6].default_value = (0.5, 0.5, 0.5, 1.0)
        Mix.inputs[7].default_value = (0.5, 0.5, 0.5, 1.0)
        Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (555.71, 101.87)

        Toon_Style = nt.nodes.new('ShaderNodeGroup')
        Toon_Style.location = (118.34, 252.53)
        Toon_Style.node_tree = ensure_node_group('.lscherry.utils.ramp_style.Toon Style')
        Toon_Style.inputs[0].default_value = False
        Toon_Style.inputs[2].default_value = 0.0
        Toon_Style.inputs[4].default_value = 0.800000011920929
        Toon_Style.inputs[5].default_value = 0.5
        Toon_Style.inputs[6].default_value = 0.5
        Toon_Style.inputs[7].default_value = 0.0

        Math_003 = nt.nodes.new('ShaderNodeMath')
        Math_003.location = (554.75, 25.58)
        Math_003.hide = True
        Math_003.operation = 'GREATER_THAN'
        Math_003.use_clamp = False
        Math_003.inputs[2].default_value = 0.5

        Simple_Toon_Dot__Group_002 = nt.nodes.new('ShaderNodeGroup')
        Simple_Toon_Dot__Group_002.location = (233.47, 186.79)
        Simple_Toon_Dot__Group_002.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Simple_Toon_Dot__Group_002.inputs[0].default_value = False
        Simple_Toon_Dot__Group_002.inputs[2].default_value = 0.0

        Simple_Toon_Dot__Use_Default_Normal = nt.nodes.new('ShaderNodeGroup')
        Simple_Toon_Dot__Use_Default_Normal.location = (-67.42, -38.23)
        Simple_Toon_Dot__Use_Default_Normal.node_tree = ensure_node_group('.lscherry.utils.normal.Use Default Normal')
        Simple_Toon_Dot__Use_Default_Normal.inputs[0].default_value = (0.0, 0.0, 0.0)

        Simple_Toon_Dot__Group_009__Attribute_001 = nt.nodes.new('ShaderNodeAttribute')
        Simple_Toon_Dot__Group_009__Attribute_001.location = (0.0, -123.16)
        Simple_Toon_Dot__Group_009__Attribute_001.hide = True
        Simple_Toon_Dot__Group_009__Attribute_001.attribute_type = 'GEOMETRY'
        Simple_Toon_Dot__Group_009__Attribute_001.attribute_name = 'tn'

        Simple_Toon_Dot__Group_009__Attribute_002 = nt.nodes.new('ShaderNodeAttribute')
        Simple_Toon_Dot__Group_009__Attribute_002.location = (0.0, 22.36)
        Simple_Toon_Dot__Group_009__Attribute_002.hide = True
        Simple_Toon_Dot__Group_009__Attribute_002.attribute_type = 'GEOMETRY'
        Simple_Toon_Dot__Group_009__Attribute_002.attribute_name = 'm'

        Simple_Toon_Dot__Group_009__Attribute_003 = nt.nodes.new('ShaderNodeAttribute')
        Simple_Toon_Dot__Group_009__Attribute_003.location = (0.0, -13.01)
        Simple_Toon_Dot__Group_009__Attribute_003.hide = True
        Simple_Toon_Dot__Group_009__Attribute_003.attribute_type = 'GEOMETRY'
        Simple_Toon_Dot__Group_009__Attribute_003.attribute_name = 'b'

        Simple_Toon_Dot__Group_009__Attribute_004 = nt.nodes.new('ShaderNodeAttribute')
        Simple_Toon_Dot__Group_009__Attribute_004.location = (0.0, -49.85)
        Simple_Toon_Dot__Group_009__Attribute_004.hide = True
        Simple_Toon_Dot__Group_009__Attribute_004.attribute_type = 'GEOMETRY'
        Simple_Toon_Dot__Group_009__Attribute_004.attribute_name = 'fx'

        Simple_Toon_Dot__Group_009__Attribute_005 = nt.nodes.new('ShaderNodeAttribute')
        Simple_Toon_Dot__Group_009__Attribute_005.location = (0.0, -85.91)
        Simple_Toon_Dot__Group_009__Attribute_005.hide = True
        Simple_Toon_Dot__Group_009__Attribute_005.attribute_type = 'GEOMETRY'
        Simple_Toon_Dot__Group_009__Attribute_005.attribute_name = 'fy'


        nt.links.new(Texture_Coordinate.outputs['Camera'], Voronoi_Texture.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Scale'], Voronoi_Texture.inputs['Scale'])
        nt.links.new(Voronoi_Texture.outputs['Distance'], Map_Range.inputs['Value'])
        nt.links.new(Math_002.outputs['Value'], Math.inputs['Value'])
        nt.links.new(Toon_Style.outputs['Shading'], Math.inputs['Value'])
        nt.links.new(Mix.outputs['Result'], Group_Output.inputs['Pattern'])
        nt.links.new(Map_Range.outputs['Result'], Math_002.inputs['Value'])
        nt.links.new(Group_Input.outputs['Dot Size'], Math_002.inputs['Value'])
        nt.links.new(Group_Input_001.outputs['Enable Light Dot Blend'], Mix.inputs['Factor'])
        nt.links.new(Math_003.outputs['Value'], Mix.inputs['A'])
        nt.links.new(Math.outputs['Value'], Mix.inputs['B'])
        nt.links.new(Math_001.outputs['Value'], Toon_Style.inputs['Shading'])
        nt.links.new(Group_Input.outputs['Toon Style'], Toon_Style.inputs['Toon Style'])
        nt.links.new(Map_Range.outputs['Result'], Math_003.inputs['Value'])
        nt.links.new(Group_Input.outputs['Dot Size'], Math_003.inputs['Value'])
        nt.links.new(Simple_Toon_Dot__Group_002.outputs['NdotL'], Math_001.inputs['Value'])
        nt.links.new(Simple_Toon_Dot__Use_Default_Normal.outputs['Normal'], Simple_Toon_Dot__Group_002.inputs['Normal'])
        nt.links.new(Simple_Toon_Dot__Group_009__Attribute_002.outputs['Vector'], Simple_Toon_Dot__Group_002.inputs['Light Dir'])
