# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ....node import ShaderNode, load_packaged_image


class ShaderNodeCompiled_Plugin__Brush_Set(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Plugin__Brush_Set'
    bl_label = 'lscherry.plugin.Plugin: Brush Set'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Plugin: Brush Set'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Texture Normal'].default_value = 'Type 1'
        self.inputs['Brush Texture'].default_value = 'Object'
        self.inputs['Transformation Location'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Transformation Rotation'].default_value = (0.0, 0.0, 0.0)
        self.inputs['Transformation Scale'].default_value = (1.0, 1.0, 1.0)
        self.inputs['Noise Mixture'].default_value = 0.2750000059604645
        self.inputs['Noise Scale'].default_value = 5.0
        self.inputs['Noise Detail'].default_value = 2.0
        self.inputs['Noise Roughness'].default_value = 0.5
        self.inputs['Noise Distortion'].default_value = 0.0

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'INPUT'

        _sock_out_Brush = nt.interface.new_socket(name='Brush', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Brush.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_inp_Texture_Normal = nt.interface.new_socket(name='Texture Normal', in_out='INPUT', socket_type='NodeSocketMenu')
        _sock_inp_Texture_Normal.default_value = 'Type 1'
        _sock_inp_Brush_Texture = nt.interface.new_socket(name='Brush Texture', in_out='INPUT', socket_type='NodeSocketMenu')
        _sock_inp_Brush_Texture.default_value = 'Object'
        _panel_Transformation = nt.interface.new_panel(name='Transformation', default_closed=True)
        _sock_inp_Transformation_Location = nt.interface.new_socket(name='Transformation Location', in_out='INPUT', socket_type='NodeSocketVector', parent=_panel_Transformation)
        _sock_inp_Transformation_Location.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Transformation_Location.min_value = -3.4028234663852886e+38
        _sock_inp_Transformation_Location.max_value = 3.4028234663852886e+38
        _sock_inp_Transformation_Location.subtype = 'TRANSLATION'
        _sock_inp_Transformation_Location.dimensions = 3
        _sock_inp_Transformation_Rotation = nt.interface.new_socket(name='Transformation Rotation', in_out='INPUT', socket_type='NodeSocketVector', parent=_panel_Transformation)
        _sock_inp_Transformation_Rotation.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Transformation_Rotation.min_value = -3.4028234663852886e+38
        _sock_inp_Transformation_Rotation.max_value = 3.4028234663852886e+38
        _sock_inp_Transformation_Rotation.subtype = 'EULER'
        _sock_inp_Transformation_Rotation.dimensions = 3
        _sock_inp_Transformation_Scale = nt.interface.new_socket(name='Transformation Scale', in_out='INPUT', socket_type='NodeSocketVector', parent=_panel_Transformation)
        _sock_inp_Transformation_Scale.default_value = (1.0, 1.0, 1.0)
        _sock_inp_Transformation_Scale.min_value = -3.4028234663852886e+38
        _sock_inp_Transformation_Scale.max_value = 3.4028234663852886e+38
        _sock_inp_Transformation_Scale.subtype = 'XYZ'
        _sock_inp_Transformation_Scale.dimensions = 3
        _panel_Noise = nt.interface.new_panel(name='Noise', default_closed=True)
        _sock_inp_Noise_Mixture = nt.interface.new_socket(name='Noise Mixture', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Noise)
        _sock_inp_Noise_Mixture.default_value = 0.2750000059604645
        _sock_inp_Noise_Mixture.min_value = 0.0
        _sock_inp_Noise_Mixture.max_value = 1.0
        _sock_inp_Noise_Mixture.subtype = 'FACTOR'
        _sock_inp_Noise_Scale = nt.interface.new_socket(name='Noise Scale', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Noise)
        _sock_inp_Noise_Scale.default_value = 5.0
        _sock_inp_Noise_Scale.min_value = -1000.0
        _sock_inp_Noise_Scale.max_value = 1000.0
        _sock_inp_Noise_Detail = nt.interface.new_socket(name='Noise Detail', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Noise)
        _sock_inp_Noise_Detail.default_value = 2.0
        _sock_inp_Noise_Detail.min_value = 0.0
        _sock_inp_Noise_Detail.max_value = 15.0
        _sock_inp_Noise_Roughness = nt.interface.new_socket(name='Noise Roughness', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Noise)
        _sock_inp_Noise_Roughness.default_value = 0.5
        _sock_inp_Noise_Roughness.min_value = 0.0
        _sock_inp_Noise_Roughness.max_value = 1.0
        _sock_inp_Noise_Roughness.subtype = 'FACTOR'
        _sock_inp_Noise_Distortion = nt.interface.new_socket(name='Noise Distortion', in_out='INPUT', socket_type='NodeSocketFloat', parent=_panel_Noise)
        _sock_inp_Noise_Distortion.default_value = 0.0
        _sock_inp_Noise_Distortion.min_value = -1000.0
        _sock_inp_Noise_Distortion.max_value = 1000.0

        Image_Texture = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture.location = (248.7, -52.56)
        Image_Texture.width = 240.0
        Image_Texture.hide = True
        Image_Texture.image = load_packaged_image('49.png')
        Image_Texture.projection = 'FLAT'
        Image_Texture.interpolation = 'Linear'
        Image_Texture.projection_blend = 0.0
        Image_Texture.extension = 'REPEAT'

        Mapping = nt.nodes.new('ShaderNodeMapping')
        Mapping.location = (68.7, -22.95)
        Mapping.vector_type = 'POINT'

        Texture_Coordinate = nt.nodes.new('ShaderNodeTexCoord')
        Texture_Coordinate.location = (-652.56, -260.85)
        Texture_Coordinate.hide = True
        Texture_Coordinate.from_instancer = False

        Noise_Texture = nt.nodes.new('ShaderNodeTexNoise')
        Noise_Texture.location = (-383.27, -301.22)
        Noise_Texture.width = 145.0
        Noise_Texture.noise_dimensions = '3D'
        Noise_Texture.noise_type = 'FBM'
        Noise_Texture.normalize = True
        Noise_Texture.inputs[1].default_value = 0.0
        Noise_Texture.inputs[5].default_value = 2.0
        Noise_Texture.inputs[6].default_value = 0.0
        Noise_Texture.inputs[7].default_value = 1.0

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (-111.05, -74.12)
        Mix.data_type = 'RGBA'
        Mix.factor_mode = 'UNIFORM'
        Mix.blend_type = 'MIX'
        Mix.clamp_factor = True
        Mix.clamp_result = False
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Menu_Switch = nt.nodes.new('GeometryNodeMenuSwitch')
        Menu_Switch.location = (849.38, 68.19)
        Menu_Switch.active_index = 33
        Menu_Switch.data_type = 'RGBA'

        Image_Texture_001 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_001.location = (249.35, 571.23)
        Image_Texture_001.width = 240.0
        Image_Texture_001.hide = True
        Image_Texture_001.image = load_packaged_image('8.png')
        Image_Texture_001.projection = 'FLAT'
        Image_Texture_001.interpolation = 'Linear'
        Image_Texture_001.projection_blend = 0.0
        Image_Texture_001.extension = 'REPEAT'

        Image_Texture_002 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_002.location = (249.35, 536.61)
        Image_Texture_002.width = 240.0
        Image_Texture_002.hide = True
        Image_Texture_002.image = load_packaged_image('10.png')
        Image_Texture_002.projection = 'FLAT'
        Image_Texture_002.interpolation = 'Linear'
        Image_Texture_002.projection_blend = 0.0
        Image_Texture_002.extension = 'REPEAT'

        Image_Texture_003 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_003.location = (249.35, 501.99)
        Image_Texture_003.width = 240.0
        Image_Texture_003.hide = True
        Image_Texture_003.image = load_packaged_image('11.png')
        Image_Texture_003.projection = 'FLAT'
        Image_Texture_003.interpolation = 'Linear'
        Image_Texture_003.projection_blend = 0.0
        Image_Texture_003.extension = 'REPEAT'

        Image_Texture_004 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_004.location = (249.35, 467.37)
        Image_Texture_004.width = 240.0
        Image_Texture_004.hide = True
        Image_Texture_004.image = load_packaged_image('17.png')
        Image_Texture_004.projection = 'FLAT'
        Image_Texture_004.interpolation = 'Linear'
        Image_Texture_004.projection_blend = 0.0
        Image_Texture_004.extension = 'REPEAT'

        Image_Texture_005 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_005.location = (249.35, 432.75)
        Image_Texture_005.width = 240.0
        Image_Texture_005.hide = True
        Image_Texture_005.image = load_packaged_image('24.png')
        Image_Texture_005.projection = 'FLAT'
        Image_Texture_005.interpolation = 'Linear'
        Image_Texture_005.projection_blend = 0.0
        Image_Texture_005.extension = 'REPEAT'

        Image_Texture_006 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_006.location = (249.35, 398.13)
        Image_Texture_006.width = 240.0
        Image_Texture_006.hide = True
        Image_Texture_006.image = load_packaged_image('25.png')
        Image_Texture_006.projection = 'FLAT'
        Image_Texture_006.interpolation = 'Linear'
        Image_Texture_006.projection_blend = 0.0
        Image_Texture_006.extension = 'REPEAT'

        Image_Texture_007 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_007.location = (249.35, 363.51)
        Image_Texture_007.width = 240.0
        Image_Texture_007.hide = True
        Image_Texture_007.image = load_packaged_image('26.png')
        Image_Texture_007.projection = 'FLAT'
        Image_Texture_007.interpolation = 'Linear'
        Image_Texture_007.projection_blend = 0.0
        Image_Texture_007.extension = 'REPEAT'

        Image_Texture_008 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_008.location = (249.35, 328.89)
        Image_Texture_008.width = 240.0
        Image_Texture_008.hide = True
        Image_Texture_008.image = load_packaged_image('32.png')
        Image_Texture_008.projection = 'FLAT'
        Image_Texture_008.interpolation = 'Linear'
        Image_Texture_008.projection_blend = 0.0
        Image_Texture_008.extension = 'REPEAT'

        Image_Texture_009 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_009.location = (249.35, 294.27)
        Image_Texture_009.width = 240.0
        Image_Texture_009.hide = True
        Image_Texture_009.image = load_packaged_image('33.png')
        Image_Texture_009.projection = 'FLAT'
        Image_Texture_009.interpolation = 'Linear'
        Image_Texture_009.projection_blend = 0.0
        Image_Texture_009.extension = 'REPEAT'

        Image_Texture_010 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_010.location = (249.35, 259.65)
        Image_Texture_010.width = 240.0
        Image_Texture_010.hide = True
        Image_Texture_010.image = load_packaged_image('34.png')
        Image_Texture_010.projection = 'FLAT'
        Image_Texture_010.interpolation = 'Linear'
        Image_Texture_010.projection_blend = 0.0
        Image_Texture_010.extension = 'REPEAT'

        Image_Texture_011 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_011.location = (249.35, 225.03)
        Image_Texture_011.width = 240.0
        Image_Texture_011.hide = True
        Image_Texture_011.image = load_packaged_image('39.png')
        Image_Texture_011.projection = 'FLAT'
        Image_Texture_011.interpolation = 'Linear'
        Image_Texture_011.projection_blend = 0.0
        Image_Texture_011.extension = 'REPEAT'

        Image_Texture_012 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_012.location = (249.35, -571.78)
        Image_Texture_012.width = 240.0
        Image_Texture_012.hide = True
        Image_Texture_012.image = load_packaged_image('40.png')
        Image_Texture_012.projection = 'FLAT'
        Image_Texture_012.interpolation = 'Linear'
        Image_Texture_012.projection_blend = 0.0
        Image_Texture_012.extension = 'REPEAT'

        Image_Texture_013 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_013.location = (249.35, 189.3)
        Image_Texture_013.width = 240.0
        Image_Texture_013.hide = True
        Image_Texture_013.image = load_packaged_image('41.png')
        Image_Texture_013.projection = 'FLAT'
        Image_Texture_013.interpolation = 'Linear'
        Image_Texture_013.projection_blend = 0.0
        Image_Texture_013.extension = 'REPEAT'

        Image_Texture_014 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_014.location = (249.35, 154.68)
        Image_Texture_014.width = 240.0
        Image_Texture_014.hide = True
        Image_Texture_014.image = load_packaged_image('42.png')
        Image_Texture_014.projection = 'FLAT'
        Image_Texture_014.interpolation = 'Linear'
        Image_Texture_014.projection_blend = 0.0
        Image_Texture_014.extension = 'REPEAT'

        Image_Texture_015 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_015.location = (249.35, 120.05)
        Image_Texture_015.width = 240.0
        Image_Texture_015.hide = True
        Image_Texture_015.image = load_packaged_image('43.png')
        Image_Texture_015.projection = 'FLAT'
        Image_Texture_015.interpolation = 'Linear'
        Image_Texture_015.projection_blend = 0.0
        Image_Texture_015.extension = 'REPEAT'

        Image_Texture_016 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_016.location = (249.35, 85.43)
        Image_Texture_016.width = 240.0
        Image_Texture_016.hide = True
        Image_Texture_016.image = load_packaged_image('45.png')
        Image_Texture_016.projection = 'FLAT'
        Image_Texture_016.interpolation = 'Linear'
        Image_Texture_016.projection_blend = 0.0
        Image_Texture_016.extension = 'REPEAT'

        Image_Texture_017 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_017.location = (249.35, 50.81)
        Image_Texture_017.width = 240.0
        Image_Texture_017.hide = True
        Image_Texture_017.image = load_packaged_image('46.png')
        Image_Texture_017.projection = 'FLAT'
        Image_Texture_017.interpolation = 'Linear'
        Image_Texture_017.projection_blend = 0.0
        Image_Texture_017.extension = 'REPEAT'

        Image_Texture_018 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_018.location = (249.35, 16.19)
        Image_Texture_018.width = 240.0
        Image_Texture_018.hide = True
        Image_Texture_018.image = load_packaged_image('47.png')
        Image_Texture_018.projection = 'FLAT'
        Image_Texture_018.interpolation = 'Linear'
        Image_Texture_018.projection_blend = 0.0
        Image_Texture_018.extension = 'REPEAT'

        Image_Texture_019 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_019.location = (249.35, -18.43)
        Image_Texture_019.width = 240.0
        Image_Texture_019.hide = True
        Image_Texture_019.image = load_packaged_image('48.png')
        Image_Texture_019.projection = 'FLAT'
        Image_Texture_019.interpolation = 'Linear'
        Image_Texture_019.projection_blend = 0.0
        Image_Texture_019.extension = 'REPEAT'

        Image_Texture_020 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_020.location = (249.35, -87.67)
        Image_Texture_020.width = 240.0
        Image_Texture_020.hide = True
        Image_Texture_020.image = load_packaged_image('50.png')
        Image_Texture_020.projection = 'FLAT'
        Image_Texture_020.interpolation = 'Linear'
        Image_Texture_020.projection_blend = 0.0
        Image_Texture_020.extension = 'REPEAT'

        Image_Texture_021 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_021.location = (249.35, -122.29)
        Image_Texture_021.width = 240.0
        Image_Texture_021.hide = True
        Image_Texture_021.image = load_packaged_image('51.png')
        Image_Texture_021.projection = 'FLAT'
        Image_Texture_021.interpolation = 'Linear'
        Image_Texture_021.projection_blend = 0.0
        Image_Texture_021.extension = 'REPEAT'

        Image_Texture_022 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_022.location = (249.35, -156.91)
        Image_Texture_022.width = 240.0
        Image_Texture_022.hide = True
        Image_Texture_022.image = load_packaged_image('53.png')
        Image_Texture_022.projection = 'FLAT'
        Image_Texture_022.interpolation = 'Linear'
        Image_Texture_022.projection_blend = 0.0
        Image_Texture_022.extension = 'REPEAT'

        Image_Texture_023 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_023.location = (249.35, -191.53)
        Image_Texture_023.width = 240.0
        Image_Texture_023.hide = True
        Image_Texture_023.image = load_packaged_image('54.png')
        Image_Texture_023.projection = 'FLAT'
        Image_Texture_023.interpolation = 'Linear'
        Image_Texture_023.projection_blend = 0.0
        Image_Texture_023.extension = 'REPEAT'

        Image_Texture_024 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_024.location = (249.35, -226.15)
        Image_Texture_024.width = 240.0
        Image_Texture_024.hide = True
        Image_Texture_024.image = load_packaged_image('58.png')
        Image_Texture_024.projection = 'FLAT'
        Image_Texture_024.interpolation = 'Linear'
        Image_Texture_024.projection_blend = 0.0
        Image_Texture_024.extension = 'REPEAT'

        Image_Texture_025 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_025.location = (249.35, -260.77)
        Image_Texture_025.width = 240.0
        Image_Texture_025.hide = True
        Image_Texture_025.image = load_packaged_image('59.png')
        Image_Texture_025.projection = 'FLAT'
        Image_Texture_025.interpolation = 'Linear'
        Image_Texture_025.projection_blend = 0.0
        Image_Texture_025.extension = 'REPEAT'

        Image_Texture_026 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_026.location = (249.35, -295.39)
        Image_Texture_026.width = 240.0
        Image_Texture_026.hide = True
        Image_Texture_026.image = load_packaged_image('60.png')
        Image_Texture_026.projection = 'FLAT'
        Image_Texture_026.interpolation = 'Linear'
        Image_Texture_026.projection_blend = 0.0
        Image_Texture_026.extension = 'REPEAT'

        Image_Texture_027 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_027.location = (249.35, -330.01)
        Image_Texture_027.width = 240.0
        Image_Texture_027.hide = True
        Image_Texture_027.image = load_packaged_image('61.png')
        Image_Texture_027.projection = 'FLAT'
        Image_Texture_027.interpolation = 'Linear'
        Image_Texture_027.projection_blend = 0.0
        Image_Texture_027.extension = 'REPEAT'

        Image_Texture_028 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_028.location = (249.35, -364.63)
        Image_Texture_028.width = 240.0
        Image_Texture_028.hide = True
        Image_Texture_028.image = load_packaged_image('64.png')
        Image_Texture_028.projection = 'FLAT'
        Image_Texture_028.interpolation = 'Linear'
        Image_Texture_028.projection_blend = 0.0
        Image_Texture_028.extension = 'REPEAT'

        Image_Texture_029 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_029.location = (249.35, -399.25)
        Image_Texture_029.width = 240.0
        Image_Texture_029.hide = True
        Image_Texture_029.image = load_packaged_image('69.png')
        Image_Texture_029.projection = 'FLAT'
        Image_Texture_029.interpolation = 'Linear'
        Image_Texture_029.projection_blend = 0.0
        Image_Texture_029.extension = 'REPEAT'

        Image_Texture_030 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_030.location = (249.35, -433.87)
        Image_Texture_030.width = 240.0
        Image_Texture_030.hide = True
        Image_Texture_030.image = load_packaged_image('71.png')
        Image_Texture_030.projection = 'FLAT'
        Image_Texture_030.interpolation = 'Linear'
        Image_Texture_030.projection_blend = 0.0
        Image_Texture_030.extension = 'REPEAT'

        Image_Texture_031 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_031.location = (249.35, -468.49)
        Image_Texture_031.width = 240.0
        Image_Texture_031.hide = True
        Image_Texture_031.image = load_packaged_image('72.png')
        Image_Texture_031.projection = 'FLAT'
        Image_Texture_031.interpolation = 'Linear'
        Image_Texture_031.projection_blend = 0.0
        Image_Texture_031.extension = 'REPEAT'

        Image_Texture_032 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_032.location = (249.35, -503.11)
        Image_Texture_032.width = 240.0
        Image_Texture_032.hide = True
        Image_Texture_032.image = load_packaged_image('73.png')
        Image_Texture_032.projection = 'FLAT'
        Image_Texture_032.interpolation = 'Linear'
        Image_Texture_032.projection_blend = 0.0
        Image_Texture_032.extension = 'REPEAT'

        Image_Texture_033 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_033.location = (249.35, -537.73)
        Image_Texture_033.width = 240.0
        Image_Texture_033.hide = True
        Image_Texture_033.image = load_packaged_image('75.png')
        Image_Texture_033.projection = 'FLAT'
        Image_Texture_033.interpolation = 'Linear'
        Image_Texture_033.projection_blend = 0.0
        Image_Texture_033.extension = 'REPEAT'

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1039.38, 0.0)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (849.47, 99.14)
        Group_Input.hide = True

        Menu_Switch_001 = nt.nodes.new('GeometryNodeMenuSwitch')
        Menu_Switch_001.location = (-377.16, -86.51)
        Menu_Switch_001.active_index = 2
        Menu_Switch_001.data_type = 'VECTOR'

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (-652.85, -108.35)
        Group_Input_001.hide = True

        Group_Input_002 = nt.nodes.new('NodeGroupInput')
        Group_Input_002.location = (64.39, -199.58)
        Group_Input_002.hide = True

        Group_Input_003 = nt.nodes.new('NodeGroupInput')
        Group_Input_003.location = (-658.97, -424.78)

        Group_Input_004 = nt.nodes.new('NodeGroupInput')
        Group_Input_004.location = (-658.97, -424.78)

        Group_Input_005 = nt.nodes.new('NodeGroupInput')
        Group_Input_005.location = (-380.8, -1.98)


        nt.links.new(Mapping.outputs['Vector'], Image_Texture.inputs['Vector'])
        nt.links.new(Mix.outputs['Result'], Mapping.inputs['Vector'])
        nt.links.new(Group_Input_002.outputs['Transformation Location'], Mapping.inputs['Location'])
        nt.links.new(Group_Input_002.outputs['Transformation Rotation'], Mapping.inputs['Rotation'])
        nt.links.new(Group_Input_002.outputs['Transformation Scale'], Mapping.inputs['Scale'])
        nt.links.new(Texture_Coordinate.outputs['Normal'], Noise_Texture.inputs['Vector'])
        nt.links.new(Group_Input_003.outputs['Noise Scale'], Noise_Texture.inputs['Scale'])
        nt.links.new(Group_Input_003.outputs['Noise Detail'], Noise_Texture.inputs['Detail'])
        nt.links.new(Group_Input_003.outputs['Noise Roughness'], Noise_Texture.inputs['Roughness'])
        nt.links.new(Group_Input_003.outputs['Noise Distortion'], Noise_Texture.inputs['Distortion'])
        nt.links.new(Group_Input_005.outputs['Noise Mixture'], Mix.inputs['Factor'])
        nt.links.new(Menu_Switch_001.outputs['Output'], Mix.inputs['A'])
        nt.links.new(Noise_Texture.outputs['Color'], Mix.inputs['B'])
        nt.links.new(Group_Input.outputs['Texture Normal'], Menu_Switch.inputs['Menu'])
        nt.links.new(Image_Texture_001.outputs['Alpha'], Menu_Switch.inputs['Type 1'])
        nt.links.new(Image_Texture_002.outputs['Alpha'], Menu_Switch.inputs['Type 2'])
        nt.links.new(Image_Texture_003.outputs['Alpha'], Menu_Switch.inputs['Type 3'])
        nt.links.new(Image_Texture_004.outputs['Alpha'], Menu_Switch.inputs['Type 4'])
        nt.links.new(Image_Texture_005.outputs['Alpha'], Menu_Switch.inputs['Type 5'])
        nt.links.new(Image_Texture_006.outputs['Alpha'], Menu_Switch.inputs['Type 6'])
        nt.links.new(Image_Texture_007.outputs['Alpha'], Menu_Switch.inputs['Type 7'])
        nt.links.new(Image_Texture_008.outputs['Alpha'], Menu_Switch.inputs['Type 8'])
        nt.links.new(Image_Texture_009.outputs['Alpha'], Menu_Switch.inputs['Type 9'])
        nt.links.new(Image_Texture_010.outputs['Alpha'], Menu_Switch.inputs['Type 10'])
        nt.links.new(Image_Texture_011.outputs['Alpha'], Menu_Switch.inputs['Type 11'])
        nt.links.new(Image_Texture_013.outputs['Alpha'], Menu_Switch.inputs['Type 12'])
        nt.links.new(Image_Texture_014.outputs['Alpha'], Menu_Switch.inputs['Type 13'])
        nt.links.new(Image_Texture_015.outputs['Alpha'], Menu_Switch.inputs['Type 14'])
        nt.links.new(Image_Texture_016.outputs['Alpha'], Menu_Switch.inputs['Type 15'])
        nt.links.new(Image_Texture_017.outputs['Alpha'], Menu_Switch.inputs['Type 16'])
        nt.links.new(Image_Texture_018.outputs['Alpha'], Menu_Switch.inputs['Type 17'])
        nt.links.new(Image_Texture_019.outputs['Alpha'], Menu_Switch.inputs['Type 18'])
        nt.links.new(Image_Texture.outputs['Alpha'], Menu_Switch.inputs['Type 19'])
        nt.links.new(Image_Texture_020.outputs['Alpha'], Menu_Switch.inputs['Type 20'])
        nt.links.new(Image_Texture_021.outputs['Alpha'], Menu_Switch.inputs['Type 21'])
        nt.links.new(Image_Texture_022.outputs['Alpha'], Menu_Switch.inputs['Type 22'])
        nt.links.new(Image_Texture_023.outputs['Alpha'], Menu_Switch.inputs['Type 23'])
        nt.links.new(Image_Texture_024.outputs['Alpha'], Menu_Switch.inputs['Type 24'])
        nt.links.new(Image_Texture_025.outputs['Alpha'], Menu_Switch.inputs['Type 25'])
        nt.links.new(Image_Texture_026.outputs['Alpha'], Menu_Switch.inputs['Type 26'])
        nt.links.new(Image_Texture_027.outputs['Alpha'], Menu_Switch.inputs['Type 27'])
        nt.links.new(Image_Texture_028.outputs['Alpha'], Menu_Switch.inputs['Type 28'])
        nt.links.new(Image_Texture_029.outputs['Alpha'], Menu_Switch.inputs['Type 29'])
        nt.links.new(Image_Texture_030.outputs['Alpha'], Menu_Switch.inputs['Type 30'])
        nt.links.new(Image_Texture_031.outputs['Alpha'], Menu_Switch.inputs['Type 31'])
        nt.links.new(Image_Texture_032.outputs['Alpha'], Menu_Switch.inputs['Type 32'])
        nt.links.new(Image_Texture_033.outputs['Alpha'], Menu_Switch.inputs['Type 33'])
        nt.links.new(Image_Texture_012.outputs['Alpha'], Menu_Switch.inputs['Type 34'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_001.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_002.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_003.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_004.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_005.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_006.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_007.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_008.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_009.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_010.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_011.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_012.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_013.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_014.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_015.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_016.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_017.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_018.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_019.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_020.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_021.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_022.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_023.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_024.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_025.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_026.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_027.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_028.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_029.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_030.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_031.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_032.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture_033.inputs['Vector'])
        nt.links.new(Menu_Switch.outputs['Output'], Group_Output.inputs['Brush'])
        nt.links.new(Group_Input_001.outputs['Brush Texture'], Menu_Switch_001.inputs['Menu'])
        nt.links.new(Texture_Coordinate.outputs['Normal'], Menu_Switch_001.inputs['Normal'])
        nt.links.new(Texture_Coordinate.outputs['UV'], Menu_Switch_001.inputs['UV'])
        nt.links.new(Texture_Coordinate.outputs['Object'], Menu_Switch_001.inputs['Object'])
