"""
Exporter
Writes generated Python source files to the compiled output directory.
"""

from __future__ import annotations
import os

_FILE_HEADER = """\
# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

"""

_INIT_HEADER = """\
# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# ============================================================

"""


def write_compiled_file(directory: str, filename: str, code: str) -> str:
    """
    Write *code* to ``<directory>/<filename>``.
    Returns the absolute path of the written file.
    """
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, filename)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_FILE_HEADER)
        fh.write(code)
    return path


def write_init(directory: str, module_names: list[str]) -> str:
    """
    Write an ``__init__.py`` that wildcard-imports every compiled module.
    Returns the absolute path.
    """
    lines = [_INIT_HEADER]
    for name in module_names:
        lines.append(f"from .{name} import *")
    lines.append("")

    path = os.path.join(directory, "__init__.py")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return path


def ng_name_to_filename(ng_name: str) -> str:
    """'My Group.001' → 'my_group_001'"""
    clean = "".join(c if c.isalnum() else "_" for c in ng_name)
    return clean.strip("_").lower()


def ng_name_to_class(ng_name: str, ng_type: str) -> str:
    """'My Group' (SHADER) → 'ShaderNodeCompiled_My_Group'"""
    prefix_map = {
        'SHADER':      'ShaderNode',
        'GEOMETRY':    'GeometryNode',
        'COMPOSITING': 'CompositorNode',
    }
    prefix = prefix_map.get(ng_type, 'ShaderNode')
    clean  = "".join(c if c.isalnum() else "_" for c in ng_name).strip("_")
    return f"{prefix}Compiled_{clean}"
