"""
Exporter
Writes compiled .py files into the correct subfolder under compiled/,
mirroring the LSCherry node group hierarchy.
"""

from __future__ import annotations
import os
import bpy  # type: ignore

_FILE_HEADER = """\
# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

"""

_INIT_HEADER = """\
# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# ============================================================

"""


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------

def write_compiled_file(base_out_dir: str, subpath: str, filename: str, code: str) -> str:
    """
    Write *code* to ``<base_out_dir>/<subpath>/<filename>``.
    Creates the subfolder if it doesn't exist.
    Returns the absolute path of the written file.
    """
    folder = os.path.join(base_out_dir, subpath)
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, filename)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_FILE_HEADER)
        fh.write(code)
    return path


def write_all_inits(base_out_dir: str, subpath_modules: dict[str, list[str]]):
    """
    Write an ``__init__.py`` for every subfolder that has compiled modules.

    Parameters
    ----------
    base_out_dir    : root output dir (e.g. .../src/nodes/compiled)
    subpath_modules : { subpath → [module_stem, ...] }
                      e.g. {"lscherry/utils/bnodes": ["tangent_fix", "normal_blend"]}
    """
    # Collect all unique folder paths (including intermediary parents)
    all_folders: set[str] = set()
    for subpath in subpath_modules:
        parts = subpath.split("/")
        for i in range(len(parts)):
            all_folders.add("/".join(parts[: i + 1]))
    all_folders.add("")  # root compiled/ itself

    for folder_rel in sorted(all_folders):
        folder_abs = os.path.join(base_out_dir, folder_rel) if folder_rel else base_out_dir
        os.makedirs(folder_abs, exist_ok=True)

        # Gather direct-child module stems for this folder
        module_stems = subpath_modules.get(folder_rel, [])

        # Gather direct-child subfolders that contain at least one module
        child_subfolders: list[str] = []
        for sp in subpath_modules:
            parts = sp.split("/")
            if folder_rel == "":
                # root: direct children are top-level subpaths
                if len(parts) == 1:
                    child_subfolders.append(parts[0])
            else:
                # non-root: direct children start with folder_rel + "/"
                prefix = folder_rel + "/"
                if sp.startswith(prefix):
                    remainder = sp[len(prefix):]
                    if "/" not in remainder:
                        child_subfolders.append(remainder)

        _write_init(folder_abs, module_stems, child_subfolders)


def _write_init(folder: str, module_stems: list[str], child_subfolders: list[str]):
    lines = [_INIT_HEADER]
    for sub in sorted(child_subfolders):
        lines.append(f"from . import {sub}")
    for stem in sorted(module_stems):
        lines.append(f"from .{stem} import *")
    lines.append("")
    path = os.path.join(folder, "__init__.py")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def export_packed_images(base_out_dir: str, images: dict) -> list[str]:
    """
    Save predefined textures into ``<base_out_dir>/images/`` (sibling of the
    ``lscherry/`` tree), matching where load_packaged_image() looks at runtime.

    ``images`` maps target filename → bpy.types.Image. LSCherry textures are
    packed inside the source .blend, so each is copied first (to avoid
    mutating the source datablock's filepath) and then saved out, decoding the
    packed pixels to disk. Existing files are left untouched so re-compiles are
    idempotent. Returns the list of written/extant paths.
    """
    folder = os.path.join(base_out_dir, "images")
    os.makedirs(folder, exist_ok=True)
    written: list[str] = []
    for filename, img in images.items():
        dest = os.path.join(folder, filename)
        if os.path.exists(dest):
            written.append(dest)
            continue
        tmp = img.copy()
        try:
            tmp.filepath_raw = dest
            if getattr(img, "file_format", None):
                tmp.file_format = img.file_format
            tmp.save()
            written.append(dest)
        finally:
            bpy.data.images.remove(tmp)
    return written


# ---------------------------------------------------------------------------
# Name helpers
# ---------------------------------------------------------------------------

def ng_name_to_filename(ng_name: str) -> str:
    """
    'lscherry.utils.bnodes.TangentFix' → 'tangent_fix'
    'lscherry.plugin.Pattern'          → 'pattern'
    Only the last segment (after the last dot) becomes the filename.
    """
    last = ng_name.split(".")[-1] if "." in ng_name else ng_name
    clean = "".join(c if c.isalnum() else "_" for c in last)
    return clean.strip("_").lower()


def ng_name_to_class(ng_name: str, ng_type: str) -> str:
    """
    'lscherry.utils.bnodes.TangentFix' (SHADER) → 'ShaderNodeCompiled_TangentFix'
    Only the last segment is used so class names stay short.
    """
    prefix_map = {
        "SHADER":      "ShaderNode",
        "GEOMETRY":    "GeometryNode",
        "COMPOSITING": "CompositorNode",
    }
    prefix = prefix_map.get(ng_type, "ShaderNode")
    last   = ng_name.split(".")[-1] if "." in ng_name else ng_name
    clean  = "".join(c if c.isalnum() else "_" for c in last).strip("_")
    return f"{prefix}Compiled_{clean}"