# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from .....node import ShaderNode, ensure_node_group


class ShaderNodeCompiled_WuWa__Ramp_Texture_Resolver(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_WuWa__Ramp_Texture_Resolver'
    bl_label = 'lscherry.starters.wuthering_waves.WuWa: Ramp Texture Resolver'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'WuWa: Ramp Texture Resolver'

    image_texture: bpy.props.PointerProperty(
        name='Ramp Texture',
        type=bpy.types.Image,
        description='Ramp Texture texture',
        update=lambda self, ctx: self.valuesUpdate(ctx),
    )  # type: ignore

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Shading'].default_value = 0.0
        self.inputs['Shadow Factor'].default_value = 1.0
        self.inputs['Shadow Mask'].default_value = 0.0

    def draw_buttons(self, context, layout):
        layout.template_ID(self, 'image_texture', open="image.open")

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'INPUT'

        _sock_out_1_1 = nt.interface.new_socket(name='1-1', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_1_1.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_1_2 = nt.interface.new_socket(name='1-2', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_1_2.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_1_3 = nt.interface.new_socket(name='1-3', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_1_3.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_1_4 = nt.interface.new_socket(name='1-4', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_1_4.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_1_5 = nt.interface.new_socket(name='1-5', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_1_5.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_2_1 = nt.interface.new_socket(name='2-1', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_2_1.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_2_2 = nt.interface.new_socket(name='2-2', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_2_2.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_2_3 = nt.interface.new_socket(name='2-3', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_2_3.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_2_4 = nt.interface.new_socket(name='2-4', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_2_4.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_2_5 = nt.interface.new_socket(name='2-5', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_2_5.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_inp_Shading = nt.interface.new_socket(name='Shading', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Shading.default_value = 0.0
        _sock_inp_Shading.min_value = 0.0
        _sock_inp_Shading.max_value = 1.0
        _sock_inp_Shading.hide_value = True
        _sock_inp_Shadow_Factor = nt.interface.new_socket(name='Shadow Factor', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Shadow_Factor.default_value = 1.0
        _sock_inp_Shadow_Factor.min_value = 0.0
        _sock_inp_Shadow_Factor.max_value = 1.0
        _sock_inp_Shadow_Factor.subtype = 'FACTOR'
        _sock_inp_Shadow_Mask = nt.interface.new_socket(name='Shadow Mask', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Shadow_Mask.default_value = 0.0
        _sock_inp_Shadow_Mask.min_value = 0.0
        _sock_inp_Shadow_Mask.max_value = 1.0
        _sock_inp_Shadow_Mask.hide_value = True

        Group_003 = nt.nodes.new('ShaderNodeGroup')
        Group_003.location = (-142.9, 107.15)
        Group_003.width = 222.01
        Group_003.node_tree = ensure_node_group('.lscherry.starters.wuthering_waves.WuWa: Build Ramps From Map')

        Image_Texture = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture.location = (142.9, 69.3)
        Image_Texture.width = 240.0
        Image_Texture.label = 'Ramp Texture'
        Image_Texture.hide = True
        Image_Texture.projection = 'FLAT'
        Image_Texture.interpolation = 'Linear'
        Image_Texture.projection_blend = 0.0
        Image_Texture.extension = 'REPEAT'

        Image_Texture_001 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_001.location = (142.9, 36.76)
        Image_Texture_001.width = 240.0
        Image_Texture_001.label = 'Ramp Texture'
        Image_Texture_001.hide = True
        Image_Texture_001.projection = 'FLAT'
        Image_Texture_001.interpolation = 'Linear'
        Image_Texture_001.projection_blend = 0.0
        Image_Texture_001.extension = 'REPEAT'

        Image_Texture_002 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_002.location = (142.9, 5.11)
        Image_Texture_002.width = 240.0
        Image_Texture_002.label = 'Ramp Texture'
        Image_Texture_002.hide = True
        Image_Texture_002.projection = 'FLAT'
        Image_Texture_002.interpolation = 'Linear'
        Image_Texture_002.projection_blend = 0.0
        Image_Texture_002.extension = 'REPEAT'

        Image_Texture_003 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_003.location = (142.9, -27.44)
        Image_Texture_003.width = 240.0
        Image_Texture_003.label = 'Ramp Texture'
        Image_Texture_003.hide = True
        Image_Texture_003.projection = 'FLAT'
        Image_Texture_003.interpolation = 'Linear'
        Image_Texture_003.projection_blend = 0.0
        Image_Texture_003.extension = 'REPEAT'

        Image_Texture_004 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_004.location = (142.9, -60.89)
        Image_Texture_004.width = 240.0
        Image_Texture_004.label = 'Ramp Texture'
        Image_Texture_004.hide = True
        Image_Texture_004.projection = 'FLAT'
        Image_Texture_004.interpolation = 'Linear'
        Image_Texture_004.projection_blend = 0.0
        Image_Texture_004.extension = 'REPEAT'

        Image_Texture_005 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_005.location = (142.9, -93.44)
        Image_Texture_005.width = 240.0
        Image_Texture_005.label = 'Ramp Texture'
        Image_Texture_005.hide = True
        Image_Texture_005.projection = 'FLAT'
        Image_Texture_005.interpolation = 'Linear'
        Image_Texture_005.projection_blend = 0.0
        Image_Texture_005.extension = 'REPEAT'

        Image_Texture_006 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_006.location = (142.9, -125.08)
        Image_Texture_006.width = 240.0
        Image_Texture_006.label = 'Ramp Texture'
        Image_Texture_006.hide = True
        Image_Texture_006.projection = 'FLAT'
        Image_Texture_006.interpolation = 'Linear'
        Image_Texture_006.projection_blend = 0.0
        Image_Texture_006.extension = 'REPEAT'

        Image_Texture_007 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_007.location = (142.9, -157.63)
        Image_Texture_007.width = 240.0
        Image_Texture_007.label = 'Ramp Texture'
        Image_Texture_007.hide = True
        Image_Texture_007.projection = 'FLAT'
        Image_Texture_007.interpolation = 'Linear'
        Image_Texture_007.projection_blend = 0.0
        Image_Texture_007.extension = 'REPEAT'

        Image_Texture_008 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_008.location = (142.9, -190.18)
        Image_Texture_008.width = 240.0
        Image_Texture_008.label = 'Ramp Texture'
        Image_Texture_008.hide = True
        Image_Texture_008.projection = 'FLAT'
        Image_Texture_008.interpolation = 'Linear'
        Image_Texture_008.projection_blend = 0.0
        Image_Texture_008.extension = 'REPEAT'

        Image_Texture_009 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_009.location = (142.9, -222.73)
        Image_Texture_009.width = 240.0
        Image_Texture_009.label = 'Ramp Texture'
        Image_Texture_009.hide = True
        Image_Texture_009.projection = 'FLAT'
        Image_Texture_009.interpolation = 'Linear'
        Image_Texture_009.projection_blend = 0.0
        Image_Texture_009.extension = 'REPEAT'

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (432.9, 0.0)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-342.9, 0.0)


        nt.links.new(Group_Input.outputs['Shading'], Group_003.inputs['Toon'])
        nt.links.new(Group_Input.outputs['Shadow Factor'], Group_003.inputs['Shadow Factor'])
        nt.links.new(Group_Input.outputs['Shadow Mask'], Group_003.inputs['Shadow Mask'])
        nt.links.new(Group_003.outputs['UV1-1'], Image_Texture.inputs['Vector'])
        nt.links.new(Group_003.outputs['UV1-2'], Image_Texture_001.inputs['Vector'])
        nt.links.new(Group_003.outputs['UV1-3'], Image_Texture_002.inputs['Vector'])
        nt.links.new(Group_003.outputs['UV1-4'], Image_Texture_003.inputs['Vector'])
        nt.links.new(Group_003.outputs['UV1-5'], Image_Texture_004.inputs['Vector'])
        nt.links.new(Group_003.outputs['UV2-1'], Image_Texture_005.inputs['Vector'])
        nt.links.new(Group_003.outputs['UV2-2'], Image_Texture_006.inputs['Vector'])
        nt.links.new(Group_003.outputs['UV2-3'], Image_Texture_007.inputs['Vector'])
        nt.links.new(Group_003.outputs['UV2-4'], Image_Texture_008.inputs['Vector'])
        nt.links.new(Group_003.outputs['UV2-5'], Image_Texture_009.inputs['Vector'])
        nt.links.new(Image_Texture.outputs['Color'], Group_Output.inputs['1-1'])
        nt.links.new(Image_Texture_001.outputs['Color'], Group_Output.inputs['1-2'])
        nt.links.new(Image_Texture_002.outputs['Color'], Group_Output.inputs['1-3'])
        nt.links.new(Image_Texture_003.outputs['Color'], Group_Output.inputs['1-4'])
        nt.links.new(Image_Texture_004.outputs['Color'], Group_Output.inputs['1-5'])
        nt.links.new(Image_Texture_005.outputs['Color'], Group_Output.inputs['2-1'])
        nt.links.new(Image_Texture_006.outputs['Color'], Group_Output.inputs['2-2'])
        nt.links.new(Image_Texture_007.outputs['Color'], Group_Output.inputs['2-3'])
        nt.links.new(Image_Texture_008.outputs['Color'], Group_Output.inputs['2-4'])
        nt.links.new(Image_Texture_009.outputs['Color'], Group_Output.inputs['2-5'])
        self.valuesUpdate(None)

    def valuesUpdate(self, context):
        if context is not None and self.node_tree.users > 1:
            self.node_tree = self.node_tree.copy()
        _placeholder_images = {'Image Texture': 'image_texture', 'Image Texture.001': 'image_texture', 'Image Texture.002': 'image_texture', 'Image Texture.003': 'image_texture', 'Image Texture.004': 'image_texture', 'Image Texture.005': 'image_texture', 'Image Texture.006': 'image_texture', 'Image Texture.007': 'image_texture', 'Image Texture.008': 'image_texture', 'Image Texture.009': 'image_texture'}
        for node in self.node_tree.nodes:
            if node.type == "TEX_IMAGE" and node.name in _placeholder_images:
                node.image = getattr(self, _placeholder_images[node.name])
