# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from .....node import ShaderNode


class ShaderNodeCompiled_WuWa__Build_Face_Ramp(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_WuWa__Build_Face_Ramp'
    bl_label = 'lscherry.starters.wuthering_waves.WuWa: Build Face Ramp'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'WuWa: Build Face Ramp'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Face Value'].default_value = 0.5
        self.inputs['Face Color'].default_value = (0.0, 0.0, 0.0, 1.0)

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'CONVERTER'

        _sock_out_Custom_Ramp = nt.interface.new_socket(name='Custom Ramp', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Custom_Ramp.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_out_Custom_Ramp.hide_value = True
        _sock_inp_Face_Value = nt.interface.new_socket(name='Face Value', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Face_Value.default_value = 0.5
        _sock_inp_Face_Value.min_value = -10000.0
        _sock_inp_Face_Value.max_value = 10000.0
        _sock_inp_Face_Value.hide_value = True
        _sock_inp_Face_Color = nt.interface.new_socket(name='Face Color', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Face_Color.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Face_Color.hide_value = True

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (229.33, 59.68)
        Math.operation = 'GREATER_THAN'
        Math.use_clamp = False
        Math.inputs[2].default_value = 0.5

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1624.71, 14.53)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-368.86, -12.79)

        Separate_Color = nt.nodes.new('ShaderNodeSeparateColor')
        Separate_Color.location = (-107.64, -65.85)
        Separate_Color.mode = 'RGB'


        nt.links.new(Separate_Color.outputs['Red'], Math.inputs[0])
        nt.links.new(Group_Input.outputs['Face Value'], Math.inputs[1])
        nt.links.new(Math.outputs['Value'], Group_Output.inputs['Custom Ramp'])
        nt.links.new(Group_Input.outputs['Face Color'], Separate_Color.inputs['Color'])
