# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ..utils import ShaderNode


class ShaderNodeCompiled_AVR__Metal_Ramp(ShaderNode):
    bl_label = 'AVR: Metal Ramp'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Use Dot'].default_value = False
        self.inputs['Roughness'].default_value = 0.3919999897480011
        self.inputs['Scale'].default_value = 4.010000228881836
        self.inputs['Distortion'].default_value = 1.0
        self.inputs['Value Enhance'].default_value = 0.10000000149011612
        self.inputs['Normal'].default_value = (0.0, 0.0, 0.0)

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'SHADER'

        _sock_out_Shader = nt.interface.new_socket(name='Shader', in_out='OUTPUT', socket_type='NodeSocketShader')
        _sock_out_Ramp = nt.interface.new_socket(name='Ramp', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Ramp.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_inp_Use_Dot = nt.interface.new_socket(name='Use Dot', in_out='INPUT', socket_type='NodeSocketBool')
        _sock_inp_Use_Dot.default_value = False
        _sock_inp_Roughness = nt.interface.new_socket(name='Roughness', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Roughness.default_value = 0.3919999897480011
        _sock_inp_Roughness.min_value = 0.0
        _sock_inp_Roughness.max_value = 1.0
        _sock_inp_Roughness.subtype = 'FACTOR'
        _sock_inp_Scale = nt.interface.new_socket(name='Scale', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Scale.default_value = 4.010000228881836
        _sock_inp_Scale.min_value = 0.0
        _sock_inp_Scale.max_value = 100.0
        _sock_inp_Distortion = nt.interface.new_socket(name='Distortion', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Distortion.default_value = 1.0
        _sock_inp_Distortion.min_value = 0.0
        _sock_inp_Distortion.max_value = 100.0
        _sock_inp_Value_Enhance = nt.interface.new_socket(name='Value Enhance', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Value_Enhance.default_value = 0.10000000149011612
        _sock_inp_Value_Enhance.min_value = 0.0
        _sock_inp_Value_Enhance.max_value = 1.0
        _sock_inp_Value_Enhance.subtype = 'FACTOR'
        _sock_inp_Normal = nt.interface.new_socket(name='Normal', in_out='INPUT', socket_type='NodeSocketVector')
        _sock_inp_Normal.default_value = (0.0, 0.0, 0.0)
        _sock_inp_Normal.min_value = -3.4028234663852886e+38
        _sock_inp_Normal.max_value = 3.4028234663852886e+38
        _sock_inp_Normal.hide_value = True
        _sock_inp_Normal.dimensions = 3

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1540.87, 215.89)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-142.33, -450.59)

        Texture_Coordinate = nt.nodes.new('ShaderNodeTexCoord')
        Texture_Coordinate.location = (-59.06, -107.3)
        Texture_Coordinate.hide = True

        Vector_Transform = nt.nodes.new('ShaderNodeVectorTransform')
        Vector_Transform.location = (-58.85, -139.39)
        Vector_Transform.hide = True
        Vector_Transform.vector_type = 'NORMAL'
        Vector_Transform.convert_from = 'OBJECT'
        Vector_Transform.convert_to = 'CAMERA'

        Magic_Texture = nt.nodes.new('ShaderNodeTexMagic')
        Magic_Texture.location = (128.22, -97.24)

        Brightness_Contrast = nt.nodes.new('ShaderNodeBrightContrast')
        Brightness_Contrast.location = (315.77, -107.52)
        Brightness_Contrast.inputs[1].default_value = 0.0
        Brightness_Contrast.inputs[2].default_value = 2.0

        RGB = nt.nodes.new('ShaderNodeRGB')
        RGB.location = (311.6, 87.26)

        Mix = nt.nodes.new('ShaderNodeMix')
        Mix.location = (505.54, 27.77)
        Mix.data_type = 'RGBA'
        Mix.blend_type = 'LINEAR_LIGHT'
        Mix.clamp_result = False
        Mix.clamp_factor = True
        Mix.factor_mode = 'UNIFORM'
        Mix.inputs[0].default_value = 1.0
        Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix.inputs[2].default_value = 0.0
        Mix.inputs[3].default_value = 0.0
        Mix.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Glossy_BSDF = nt.nodes.new('ShaderNodeBsdfAnisotropic')
        Glossy_BSDF.location = (785.16, 134.77)
        Glossy_BSDF.width = 150.0
        Glossy_BSDF.distribution = 'MULTI_GGX'
        Glossy_BSDF.inputs[2].default_value = 0.0
        Glossy_BSDF.inputs[3].default_value = 0.0
        Glossy_BSDF.inputs[5].default_value = (0.0, 0.0, 0.0)
        Glossy_BSDF.inputs[6].default_value = 0.0

        Group = nt.nodes.new('ShaderNodeGroup')
        Group.location = (500.93, -219.12)
        Group.node_tree = bpy.data.node_groups['Specular Dot']

        Attribute = nt.nodes.new('ShaderNodeAttribute')
        Attribute.location = (313.78, -243.63)
        Attribute.attribute_name = 'm'
        Attribute.attribute_type = 'GEOMETRY'

        Shader_to_RGB = nt.nodes.new('ShaderNodeShaderToRGB')
        Shader_to_RGB.location = (985.38, 114.63)

        Mix_001 = nt.nodes.new('ShaderNodeMix')
        Mix_001.location = (1180.79, 147.2)
        Mix_001.data_type = 'RGBA'
        Mix_001.blend_type = 'MIX'
        Mix_001.clamp_result = True
        Mix_001.clamp_factor = True
        Mix_001.factor_mode = 'UNIFORM'
        Mix_001.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_001.inputs[2].default_value = 0.0
        Mix_001.inputs[3].default_value = 0.0
        Mix_001.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_001.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix_001.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Mix_002 = nt.nodes.new('ShaderNodeMix')
        Mix_002.location = (785.71, -96.95)
        Mix_002.data_type = 'RGBA'
        Mix_002.blend_type = 'MULTIPLY'
        Mix_002.clamp_result = False
        Mix_002.clamp_factor = True
        Mix_002.factor_mode = 'UNIFORM'
        Mix_002.inputs[0].default_value = 1.0
        Mix_002.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_002.inputs[2].default_value = 0.0
        Mix_002.inputs[3].default_value = 0.0
        Mix_002.inputs[4].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[5].default_value = (0.0, 0.0, 0.0)
        Mix_002.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix_002.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Group_Input_001 = nt.nodes.new('NodeGroupInput')
        Group_Input_001.location = (985.38, 183.81)

        Group_Input_002 = nt.nodes.new('NodeGroupInput')
        Group_Input_002.location = (508.84, 115.43)

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (67.48, -414.91)
        Math.hide = True
        Math.operation = 'GREATER_THAN'
        Math.use_clamp = False
        Math.inputs[1].default_value = 0.0
        Math.inputs[2].default_value = 0.5

        Mix_003 = nt.nodes.new('ShaderNodeMix')
        Mix_003.location = (312.65, -360.61)
        Mix_003.data_type = 'VECTOR'
        Mix_003.blend_type = 'MIX'
        Mix_003.clamp_result = False
        Mix_003.clamp_factor = True
        Mix_003.factor_mode = 'UNIFORM'
        Mix_003.inputs[1].default_value = (0.5, 0.5, 0.5)
        Mix_003.inputs[2].default_value = 0.0
        Mix_003.inputs[3].default_value = 0.0
        Mix_003.inputs[6].default_value = (0.5, 0.5, 0.5, 1.0)
        Mix_003.inputs[7].default_value = (0.5, 0.5, 0.5, 1.0)
        Mix_003.inputs[8].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')
        Mix_003.inputs[9].default_value = Euler((0.0, 0.0, 0.0), 'XYZ')

        Normal_Map = nt.nodes.new('ShaderNodeNormalMap')
        Normal_Map.location = (65.79, -453.13)
        Normal_Map.width = 150.0
        Normal_Map.hide = True
        Normal_Map.space = 'TANGENT'
        Normal_Map.uv_map = ''
        Normal_Map.inputs[0].default_value = 1.0
        Normal_Map.inputs[1].default_value = (0.5, 0.5, 1.0, 1.0)

        Group_Input_003 = nt.nodes.new('NodeGroupInput')
        Group_Input_003.location = (-58.79, -204.25)

        Mix_Shader = nt.nodes.new('ShaderNodeMixShader')
        Mix_Shader.location = (1184.1, -86.28)

        Math_001 = nt.nodes.new('ShaderNodeMath')
        Math_001.location = (1361.0, 209.44)
        Math_001.operation = 'ADD'
        Math_001.use_clamp = False
        Math_001.inputs[2].default_value = 0.5

        Group_Input_004 = nt.nodes.new('NodeGroupInput')
        Group_Input_004.location = (1179.52, 209.03)


        nt.links.new(Mix_Shader.outputs['Shader'], Group_Output.inputs['Shader'])
        nt.links.new(Math_001.outputs['Value'], Group_Output.inputs['Ramp'])
        nt.links.new(Texture_Coordinate.outputs['Normal'], Vector_Transform.inputs['Vector'])
        nt.links.new(Vector_Transform.outputs['Vector'], Magic_Texture.inputs['Vector'])
        nt.links.new(Group_Input_003.outputs['Scale'], Magic_Texture.inputs['Scale'])
        nt.links.new(Group_Input_003.outputs['Distortion'], Magic_Texture.inputs['Distortion'])
        nt.links.new(Magic_Texture.outputs['Factor'], Brightness_Contrast.inputs['Color'])
        nt.links.new(RGB.outputs['Color'], Mix.inputs['A'])
        nt.links.new(Brightness_Contrast.outputs['Color'], Mix.inputs['B'])
        nt.links.new(Mix.outputs['Result'], Glossy_BSDF.inputs['Color'])
        nt.links.new(Group_Input_002.outputs['Roughness'], Glossy_BSDF.inputs['Roughness'])
        nt.links.new(Group_Input_002.outputs['Normal'], Glossy_BSDF.inputs['Normal'])
        nt.links.new(Attribute.outputs['Vector'], Group.inputs['Light Dir'])
        nt.links.new(Mix_003.outputs['Result'], Group.inputs['Normal'])
        nt.links.new(Glossy_BSDF.outputs['BSDF'], Shader_to_RGB.inputs['Shader'])
        nt.links.new(Group_Input_001.outputs['Use Dot'], Mix_001.inputs['Factor'])
        nt.links.new(Shader_to_RGB.outputs['Color'], Mix_001.inputs['A'])
        nt.links.new(Mix_002.outputs['Result'], Mix_001.inputs['B'])
        nt.links.new(Group.outputs['Specular'], Mix_002.inputs['A'])
        nt.links.new(Mix.outputs['Result'], Mix_002.inputs['B'])
        nt.links.new(Group_Input.outputs['Normal'], Math.inputs['Value'])
        nt.links.new(Math.outputs['Value'], Mix_003.inputs['Factor'])
        nt.links.new(Normal_Map.outputs['Normal'], Mix_003.inputs['A'])
        nt.links.new(Group_Input.outputs['Normal'], Mix_003.inputs['B'])
        nt.links.new(Group_Input_001.outputs['Use Dot'], Mix_Shader.inputs['Factor'])
        nt.links.new(Glossy_BSDF.outputs['BSDF'], Mix_Shader.inputs['Shader'])
        nt.links.new(Mix_002.outputs['Result'], Mix_Shader.inputs['Shader'])
        nt.links.new(Mix_001.outputs['Result'], Math_001.inputs['Value'])
        nt.links.new(Group_Input_004.outputs['Value Enhance'], Math_001.inputs['Value'])
