# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ..utils import GeometryNode


class GeometryNodeCompiled_Core_PrincipleProvider(GeometryNode):
    bl_label = 'Core.PrincipleProvider'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Size'].default_value = 1.0
        self.inputs['Smooth'].default_value = 0.10000000149011612

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'GeometryNodeTree'
        )
        nt.color_tag = 'NONE'

        _sock_out_Geometry = nt.interface.new_socket(name='Geometry', in_out='OUTPUT', socket_type='NodeSocketGeometry')
        _sock_inp_Geometry = nt.interface.new_socket(name='Geometry', in_out='INPUT', socket_type='NodeSocketGeometry')
        _sock_inp_Size = nt.interface.new_socket(name='Size', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Size.default_value = 1.0
        _sock_inp_Size.min_value = 0.0
        _sock_inp_Size.max_value = 1.0
        _sock_inp_Size.subtype = 'FACTOR'
        _sock_inp_Smooth = nt.interface.new_socket(name='Smooth', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Smooth.default_value = 0.10000000149011612
        _sock_inp_Smooth.min_value = 0.0
        _sock_inp_Smooth.max_value = 1.0
        _sock_inp_Smooth.subtype = 'FACTOR'

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-1182.74, 81.41)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (1049.24, 111.83)

        Named_Attribute = nt.nodes.new('GeometryNodeInputNamedAttribute')
        Named_Attribute.location = (-965.68, -203.24)
        Named_Attribute.inputs[0].default_value = 'm'

        Vector_Math = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math.location = (-383.78, -145.04)
        Vector_Math.operation = 'DOT_PRODUCT'
        Vector_Math.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math.inputs[3].default_value = 1.0

        Normal = nt.nodes.new('GeometryNodeInputNormal')
        Normal.location = (-744.15, -263.97)

        Vector_Math_002 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_002.location = (515.57, -5.88)
        Vector_Math_002.operation = 'NORMALIZE'
        Vector_Math_002.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math_002.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_002.inputs[3].default_value = 1.0

        Store_Named_Attribute = nt.nodes.new('GeometryNodeStoreNamedAttribute')
        Store_Named_Attribute.location = (811.88, 144.68)
        Store_Named_Attribute.inputs[1].default_value = True
        Store_Named_Attribute.inputs[2].default_value = 'tn'

        Vector_Rotate = nt.nodes.new('ShaderNodeVectorRotate')
        Vector_Rotate.location = (-746.88, -21.31)
        Vector_Rotate.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Rotate.inputs[2].default_value = (0.0, 0.0, 1.0)
        Vector_Rotate.inputs[3].default_value = 0.0

        Vector = nt.nodes.new('FunctionNodeInputVector')
        Vector.location = (-960.36, -74.47)

        Vector_Math_004 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_004.location = (336.0, -12.71)
        Vector_Math_004.operation = 'ADD'
        Vector_Math_004.inputs[2].default_value = (0.0, 0.0, 0.0)
        Vector_Math_004.inputs[3].default_value = 1.0

        Vector_Math_001 = nt.nodes.new('ShaderNodeVectorMath')
        Vector_Math_001.location = (129.65, -121.24)
        Vector_Math_001.operation = 'SCALE'
        Vector_Math_001.inputs[1].default_value = (0.0, 0.0, 0.0)
        Vector_Math_001.inputs[2].default_value = (0.0, 0.0, 0.0)

        Math = nt.nodes.new('ShaderNodeMath')
        Math.location = (-116.26, -223.97)
        Math.operation = 'MULTIPLY'
        Math.use_clamp = False
        Math.inputs[1].default_value = 5.0
        Math.inputs[2].default_value = 0.5


        nt.links.new(Store_Named_Attribute.outputs['Geometry'], Group_Output.inputs['Geometry'])
        nt.links.new(Vector_Rotate.outputs['Vector'], Vector_Math.inputs['Vector'])
        nt.links.new(Normal.outputs['Normal'], Vector_Math.inputs['Vector'])
        nt.links.new(Vector_Math_004.outputs['Vector'], Vector_Math_002.inputs['Vector'])
        nt.links.new(Group_Input.outputs['Geometry'], Store_Named_Attribute.inputs['Geometry'])
        nt.links.new(Vector_Math_002.outputs['Vector'], Store_Named_Attribute.inputs['Value'])
        nt.links.new(Vector.outputs['Vector'], Vector_Rotate.inputs['Vector'])
        nt.links.new(Named_Attribute.outputs['Attribute'], Vector_Rotate.inputs['Rotation'])
        nt.links.new(Vector_Rotate.outputs['Vector'], Vector_Math_004.inputs['Vector'])
        nt.links.new(Vector_Math_001.outputs['Vector'], Vector_Math_004.inputs['Vector'])
        nt.links.new(Vector_Rotate.outputs['Vector'], Vector_Math_001.inputs['Vector'])
        nt.links.new(Math.outputs['Value'], Vector_Math_001.inputs['Scale'])
        nt.links.new(Vector_Math.outputs['Value'], Math.inputs['Value'])
