# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ..utils import ShaderNode


class ShaderNodeCompiled_Deprecated(ShaderNode):
    bl_label = 'Deprecated'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'OUTPUT'

        _sock_out_Deprecated = nt.interface.new_socket(name='Deprecated', in_out='OUTPUT', socket_type='NodeSocketShader')
        _sock_out_Deprecated.hide_value = True
        _sock_out_USE_NEW_NODE_BELOW_INSTEAD = nt.interface.new_socket(name='USE NEW NODE BELOW INSTEAD', in_out='OUTPUT', socket_type='NodeSocketShader')
        _sock_out_USE_NEW_NODE_BELOW_INSTEAD.hide_value = True
        _sock_inp_Deprecated = nt.interface.new_socket(name='Deprecated', in_out='INPUT', socket_type='NodeSocketShader')
        _sock_inp_Deprecated.hide_value = True
        _sock_inp_USE_NEW_NODE_BELOW_INSTEAD = nt.interface.new_socket(name='USE NEW NODE BELOW INSTEAD', in_out='INPUT', socket_type='NodeSocketShader')
        _sock_inp_USE_NEW_NODE_BELOW_INSTEAD.hide_value = True

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (209.28, 92.1)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-190.72, 92.1)


        nt.links.new(Group_Input.outputs['Deprecated'], Group_Output.inputs['Deprecated'])
        nt.links.new(Group_Input.outputs['USE NEW NODE BELOW INSTEAD'], Group_Output.inputs['USE NEW NODE BELOW INSTEAD'])
