# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ..utils import ShaderNode


class ShaderNodeCompiled_HSR__Body_Color_From_Lightmap(ShaderNode):
    bl_label = 'HSR: Body Color From Lightmap'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Lighmap Alpha'].default_value = 0.0
        self.inputs['Map 0'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 1'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 2'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 3'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 4'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Map 5'].default_value = (0.0, 0.0, 0.0, 1.0)
        self.inputs['Range 1'].default_value = 0.10000000149011612
        self.inputs['Range 2'].default_value = 0.30000001192092896
        self.inputs['Range 3'].default_value = 0.44999998807907104
        self.inputs['Range 4'].default_value = 0.6200000047683716

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'COLOR'

        _sock_out_Color_Map = nt.interface.new_socket(name='Color Map', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Color_Map.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_inp_Lighmap_Alpha = nt.interface.new_socket(name='Lighmap Alpha', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Lighmap_Alpha.default_value = 0.0
        _sock_inp_Lighmap_Alpha.min_value = 0.0
        _sock_inp_Lighmap_Alpha.max_value = 1.0
        _sock_inp_Map_0 = nt.interface.new_socket(name='Map 0', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_0.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_1 = nt.interface.new_socket(name='Map 1', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_1.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_2 = nt.interface.new_socket(name='Map 2', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_2.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_3 = nt.interface.new_socket(name='Map 3', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_3.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_4 = nt.interface.new_socket(name='Map 4', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_4.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Map_5 = nt.interface.new_socket(name='Map 5', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Map_5.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_inp_Range_1 = nt.interface.new_socket(name='Range 1', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_1.default_value = 0.10000000149011612
        _sock_inp_Range_1.min_value = 0.0
        _sock_inp_Range_1.max_value = 1.0
        _sock_inp_Range_1.subtype = 'FACTOR'
        _sock_inp_Range_2 = nt.interface.new_socket(name='Range 2', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_2.default_value = 0.30000001192092896
        _sock_inp_Range_2.min_value = 0.0
        _sock_inp_Range_2.max_value = 1.0
        _sock_inp_Range_2.subtype = 'FACTOR'
        _sock_inp_Range_3 = nt.interface.new_socket(name='Range 3', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_3.default_value = 0.44999998807907104
        _sock_inp_Range_3.min_value = 0.0
        _sock_inp_Range_3.max_value = 1.0
        _sock_inp_Range_3.subtype = 'FACTOR'
        _sock_inp_Range_4 = nt.interface.new_socket(name='Range 4', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Range_4.default_value = 0.6200000047683716
        _sock_inp_Range_4.min_value = 0.0
        _sock_inp_Range_4.max_value = 1.0
        _sock_inp_Range_4.subtype = 'FACTOR'

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (190.0, 0.0)

        Group_001 = nt.nodes.new('ShaderNodeGroup')
        Group_001.location = (0.0, 0.0)
        Group_001.node_tree = bpy.data.node_groups['Set Color From LightMap']

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-200.0, -54.31)


        nt.links.new(Group_001.outputs['Color Map'], Group_Output.inputs['Color Map'])
        nt.links.new(Group_Input.outputs['Lighmap Alpha'], Group_001.inputs['Lighmap Alpha'])
        nt.links.new(Group_Input.outputs['Map 0'], Group_001.inputs['Map 0'])
        nt.links.new(Group_Input.outputs['Map 1'], Group_001.inputs['Map 1'])
        nt.links.new(Group_Input.outputs['Map 2'], Group_001.inputs['Map 2'])
        nt.links.new(Group_Input.outputs['Map 3'], Group_001.inputs['Map 3'])
        nt.links.new(Group_Input.outputs['Map 4'], Group_001.inputs['Map 4'])
        nt.links.new(Group_Input.outputs['Map 5'], Group_001.inputs['Map 5'])
        nt.links.new(Group_Input.outputs['Range 1'], Group_001.inputs['Range 1'])
        nt.links.new(Group_Input.outputs['Range 2'], Group_001.inputs['Range 2'])
        nt.links.new(Group_Input.outputs['Range 3'], Group_001.inputs['Range 3'])
        nt.links.new(Group_Input.outputs['Range 4'], Group_001.inputs['Range 4'])
