# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from ..utils import ShaderNode


class ShaderNodeCompiled_Number_Compress(ShaderNode):
    bl_label = 'Number Compress'
    bl_icon = "NONE"
    _PREFIX = "."

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Sequence 1'].default_value = 0.5
        self.inputs['Sequence 2'].default_value = 1000.0

    def createNodetree(self, name):
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + name, 'ShaderNodeTree'
        )
        nt.color_tag = 'CONVERTER'

        _sock_out_Compressed = nt.interface.new_socket(name='Compressed', in_out='OUTPUT', socket_type='NodeSocketFloat')
        _sock_out_Compressed.default_value = 0.0
        _sock_out_Compressed.min_value = -3.4028234663852886e+38
        _sock_out_Compressed.max_value = 3.4028234663852886e+38
        _sock_inp_MAX_2_SEQUENCES = nt.interface.new_socket(name='MAX 2 SEQUENCES', in_out='INPUT', socket_type='NodeSocketShader')
        _sock_inp_Sequence_1 = nt.interface.new_socket(name='Sequence 1', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Sequence_1.default_value = 0.5
        _sock_inp_Sequence_1.min_value = -10000.0
        _sock_inp_Sequence_1.max_value = 10000.0
        _sock_inp_Sequence_1.hide_value = True
        _sock_inp_Sequence_2 = nt.interface.new_socket(name='Sequence 2', in_out='INPUT', socket_type='NodeSocketFloat')
        _sock_inp_Sequence_2.default_value = 1000.0
        _sock_inp_Sequence_2.min_value = -10000.0
        _sock_inp_Sequence_2.max_value = 10000.0
        _sock_inp_Sequence_2.hide_value = True

        Math_004 = nt.nodes.new('ShaderNodeMath')
        Math_004.location = (29.89, -39.7)
        Math_004.operation = 'ADD'
        Math_004.use_clamp = False
        Math_004.inputs[2].default_value = 0.5

        Math_002 = nt.nodes.new('ShaderNodeMath')
        Math_002.location = (29.53, -40.06)
        Math_002.operation = 'MULTIPLY'
        Math_002.use_clamp = False
        Math_002.inputs[1].default_value = 10000.0
        Math_002.inputs[2].default_value = 0.5

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (584.34, 35.42)

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-407.62, -3.53)


        nt.links.new(Math_002.outputs['Value'], Math_004.inputs['Value'])
        nt.links.new(Group_Input.outputs['Sequence 2'], Math_004.inputs['Value'])
        nt.links.new(Group_Input.outputs['Sequence 1'], Math_002.inputs['Value'])
        nt.links.new(Math_004.outputs['Value'], Group_Output.inputs['Compressed'])
