# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ....node import ShaderNode


class ShaderNodeCompiled_Quick_To_Filmic(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Quick_To_Filmic'
    bl_label = 'lscherry.post_production.Quick To Filmic'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Quick To Filmic'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Combined'].default_value = (1.0, 1.0, 1.0, 1.0)

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'COLOR'

        _sock_out_Combined = nt.interface.new_socket(name='Combined', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Combined.default_value = (0.0, 0.0, 0.0, 0.0)
        _sock_inp_Combined = nt.interface.new_socket(name='Combined', in_out='INPUT', socket_type='NodeSocketColor')
        _sock_inp_Combined.default_value = (1.0, 1.0, 1.0, 1.0)

        Gamma = nt.nodes.new('ShaderNodeGamma')
        Gamma.location = (0.0, 0.0)
        Gamma.inputs[1].default_value = 2.200000047683716

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (190.0, 0.0)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-200.0, -25.86)


        nt.links.new(Group_Input.outputs['Combined'], Gamma.inputs['Color'])
        nt.links.new(Gamma.outputs['Color'], Group_Output.inputs['Combined'])
