# ============================================================
# AUTO-GENERATED by LSPotato NodeCompiler
# Do NOT edit manually — regenerate from the source .blend file.
# ============================================================

import bpy  # type: ignore
from mathutils import Color, Euler, Matrix, Quaternion, Vector  # type: ignore
from ....node import ShaderNode, ensure_node_group


class ShaderNodeCompiled_Strinova__Face(ShaderNode):
    bl_idname = 'ShaderNodeCompiled_Strinova__Face'
    bl_label = 'lscherry.starters.Strinova: Face'
    bl_icon = "NONE"
    _PREFIX = "."

    def draw_label(self):
        return 'Strinova: Face'

    image_texture: bpy.props.PointerProperty(
        name="Image Texture",
        type=bpy.types.Image,
        description="Image texture used by this node",
        update=lambda self, ctx: self.valuesUpdate(ctx),
    )  # type: ignore

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')

    def draw_buttons(self, context, layout):
        layout.template_ID(self, "image_texture", open="image.open")

    def createNodetree(self, name):
        # Use bl_label as a stable, class-level key so all instances share
        # one node tree and nested references resolve correctly.
        nt = self.node_tree = bpy.data.node_groups.new(
            self._PREFIX + self.bl_label, 'ShaderNodeTree'
        )
        nt.color_tag = 'TEXTURE'
        nt.description = 'Quick build Strinova face material'

        _sock_out_Base_Color = nt.interface.new_socket(name='Base Color', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Base_Color.default_value = (0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0)
        _sock_out_Custom_Ramp = nt.interface.new_socket(name='Custom Ramp', in_out='OUTPUT', socket_type='NodeSocketColor')
        _sock_out_Custom_Ramp.default_value = (0.0, 0.0, 0.0, 1.0)
        _sock_out_Custom_Ramp.hide_value = True

        Texture_Coordinate = nt.nodes.new('ShaderNodeTexCoord')
        Texture_Coordinate.location = (-460.62, -23.99)
        Texture_Coordinate.hide = True
        Texture_Coordinate.from_instancer = False

        Mapping = nt.nodes.new('ShaderNodeMapping')
        Mapping.location = (-268.11, 53.82)
        Mapping.vector_type = 'POINT'
        Mapping.inputs[1].default_value = (0.0, 0.0, 0.0)
        Mapping.inputs[2].default_value = (0.0, 0.0, 0.0)
        Mapping.inputs[3].default_value = (1.0, 1.0, 1.0)

        Image_Texture = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture.location = (92.35, 148.34)
        Image_Texture.width = 240.0
        Image_Texture.label = 'Face_D Texture'
        Image_Texture.projection = 'FLAT'
        Image_Texture.interpolation = 'Linear'
        Image_Texture.projection_blend = 0.0
        Image_Texture.extension = 'REPEAT'

        Image_Texture_001 = nt.nodes.new('ShaderNodeTexImage')
        Image_Texture_001.location = (92.35, -148.34)
        Image_Texture_001.width = 240.0
        Image_Texture_001.label = 'SDF Texture'
        Image_Texture_001.projection = 'FLAT'
        Image_Texture_001.interpolation = 'Linear'
        Image_Texture_001.projection_blend = 0.0
        Image_Texture_001.extension = 'REPEAT'

        lscherry_utils_procedural_Build_Face_Ramp = nt.nodes.new('ShaderNodeCompiled_Build_Face_Ramp')
        lscherry_utils_procedural_Build_Face_Ramp.location = (460.62, -52.35)

        Group_Output = nt.nodes.new('NodeGroupOutput')
        Group_Output.location = (650.62, 0.0)
        Group_Output.is_active_output = True

        Group_Input = nt.nodes.new('NodeGroupInput')
        Group_Input.location = (-660.62, 0.0)

        Face_Ramp_Builder__Vector_Math = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Vector_Math.location = (-436.76, 303.86)
        Face_Ramp_Builder__Vector_Math.operation = 'NORMALIZE'
        Face_Ramp_Builder__Vector_Math.inputs[1].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Vector_Math.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Vector_Math.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Vector_Math_004 = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Vector_Math_004.location = (29.82, -36.16)
        Face_Ramp_Builder__Vector_Math_004.operation = 'DOT_PRODUCT'
        Face_Ramp_Builder__Vector_Math_004.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Vector_Math_004.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Mapping = nt.nodes.new('ShaderNodeMapping')
        Face_Ramp_Builder__Mapping.location = (789.56, 166.19)
        Face_Ramp_Builder__Mapping.hide = True
        Face_Ramp_Builder__Mapping.vector_type = 'POINT'
        Face_Ramp_Builder__Mapping.inputs[1].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Mapping.inputs[2].default_value = (0.0, 0.0, 0.0)

        Face_Ramp_Builder__Mix = nt.nodes.new('ShaderNodeMix')
        Face_Ramp_Builder__Mix.location = (600.53, -64.78)
        Face_Ramp_Builder__Mix.hide = True
        Face_Ramp_Builder__Mix.data_type = 'VECTOR'
        Face_Ramp_Builder__Mix.factor_mode = 'UNIFORM'
        Face_Ramp_Builder__Mix.blend_type = 'MIX'
        Face_Ramp_Builder__Mix.clamp_factor = False
        Face_Ramp_Builder__Mix.clamp_result = False
        Face_Ramp_Builder__Mix.inputs[1].default_value = (0.5, 0.5, 0.5)
        Face_Ramp_Builder__Mix.inputs[2].default_value = 0.0
        Face_Ramp_Builder__Mix.inputs[3].default_value = 0.0
        Face_Ramp_Builder__Mix.inputs[6].default_value = (0.5, 0.5, 0.5, 1.0)
        Face_Ramp_Builder__Mix.inputs[7].default_value = (0.5, 0.5, 0.5, 1.0)
        Face_Ramp_Builder__Mix.inputs[8].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Mix.inputs[9].default_value = (0.0, 0.0, 0.0)

        Face_Ramp_Builder__Group_002 = nt.nodes.new('ShaderNodeGroup')
        Face_Ramp_Builder__Group_002.location = (-614.21, 303.86)
        Face_Ramp_Builder__Group_002.node_tree = ensure_node_group('.lscherry.utils.seperator.To Oxy')

        Face_Ramp_Builder__Combine_XYZ_001 = nt.nodes.new('ShaderNodeCombineXYZ')
        Face_Ramp_Builder__Combine_XYZ_001.location = (337.3, -131.72)
        Face_Ramp_Builder__Combine_XYZ_001.hide = True
        Face_Ramp_Builder__Combine_XYZ_001.inputs[1].default_value = 1.0
        Face_Ramp_Builder__Combine_XYZ_001.inputs[2].default_value = 1.0
        Face_Ramp_Builder__Combine_XYZ_001.inputs[0].default_value = 1.0

        Face_Ramp_Builder__Combine_XYZ = nt.nodes.new('ShaderNodeCombineXYZ')
        Face_Ramp_Builder__Combine_XYZ.location = (337.3, -96.75)
        Face_Ramp_Builder__Combine_XYZ.hide = True
        Face_Ramp_Builder__Combine_XYZ.inputs[1].default_value = 1.0
        Face_Ramp_Builder__Combine_XYZ.inputs[2].default_value = 1.0
        Face_Ramp_Builder__Combine_XYZ.inputs[0].default_value = -1.0

        Face_Ramp_Builder__Map_Range = nt.nodes.new('ShaderNodeMapRange')
        Face_Ramp_Builder__Map_Range.location = (273.43, -35.88)
        Face_Ramp_Builder__Map_Range.clamp = True
        Face_Ramp_Builder__Map_Range.interpolation_type = 'LINEAR'
        Face_Ramp_Builder__Map_Range.data_type = 'FLOAT'
        Face_Ramp_Builder__Map_Range.inputs[3].default_value = 0.0
        Face_Ramp_Builder__Map_Range.inputs[4].default_value = 1.0
        Face_Ramp_Builder__Map_Range.inputs[5].default_value = 4.0
        Face_Ramp_Builder__Map_Range.inputs[6].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Map_Range.inputs[7].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Map_Range.inputs[8].default_value = (1.0, 1.0, 1.0)
        Face_Ramp_Builder__Map_Range.inputs[9].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Map_Range.inputs[10].default_value = (1.0, 1.0, 1.0)
        Face_Ramp_Builder__Map_Range.inputs[11].default_value = (4.0, 4.0, 4.0)
        Face_Ramp_Builder__Map_Range.inputs[1].default_value = -0.5
        Face_Ramp_Builder__Map_Range.inputs[2].default_value = 0.5

        Face_Ramp_Builder__Vector_Math_003 = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Vector_Math_003.location = (34.96, -213.99)
        Face_Ramp_Builder__Vector_Math_003.operation = 'DOT_PRODUCT'
        Face_Ramp_Builder__Vector_Math_003.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Vector_Math_003.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Math = nt.nodes.new('ShaderNodeMath')
        Face_Ramp_Builder__Math.location = (213.76, -53.5)
        Face_Ramp_Builder__Math.hide = True
        Face_Ramp_Builder__Math.operation = 'GREATER_THAN'
        Face_Ramp_Builder__Math.use_clamp = False
        Face_Ramp_Builder__Math.inputs[1].default_value = 0.0
        Face_Ramp_Builder__Math.inputs[2].default_value = 0.5

        Face_Ramp_Builder__Group_001 = nt.nodes.new('ShaderNodeGroup')
        Face_Ramp_Builder__Group_001.location = (-793.53, 329.85)
        Face_Ramp_Builder__Group_001.node_tree = ensure_node_group('.lscherry.core.Toon Dot')
        Face_Ramp_Builder__Group_001.inputs[0].default_value = False
        Face_Ramp_Builder__Group_001.inputs[2].default_value = 0.0

        Face_Ramp_Builder__Attribute_002 = nt.nodes.new('ShaderNodeAttribute')
        Face_Ramp_Builder__Attribute_002.location = (-1074.02, 238.62)
        Face_Ramp_Builder__Attribute_002.attribute_type = 'GEOMETRY'
        Face_Ramp_Builder__Attribute_002.attribute_name = 'm'

        Face_Ramp_Builder__Geometry = nt.nodes.new('ShaderNodeNewGeometry')
        Face_Ramp_Builder__Geometry.location = (-1073.03, 100.35)

        Face_Ramp_Builder__Math_003 = nt.nodes.new('ShaderNodeMath')
        Face_Ramp_Builder__Math_003.location = (273.92, -288.96)
        Face_Ramp_Builder__Math_003.hide = True
        Face_Ramp_Builder__Math_003.operation = 'GREATER_THAN'
        Face_Ramp_Builder__Math_003.use_clamp = False
        Face_Ramp_Builder__Math_003.inputs[1].default_value = 0.0
        Face_Ramp_Builder__Math_003.inputs[2].default_value = 0.5

        Face_Ramp_Builder__Group__Group_004 = nt.nodes.new('ShaderNodeGroup')
        Face_Ramp_Builder__Group__Group_004.location = (275.03, 266.26)
        Face_Ramp_Builder__Group__Group_004.hide = True
        Face_Ramp_Builder__Group__Group_004.node_tree = ensure_node_group('.lscherry.utils.seperator.To Oxy')

        Face_Ramp_Builder__Group__Group_003 = nt.nodes.new('ShaderNodeGroup')
        Face_Ramp_Builder__Group__Group_003.location = (278.46, 34.25)
        Face_Ramp_Builder__Group__Group_003.hide = True
        Face_Ramp_Builder__Group__Group_003.node_tree = ensure_node_group('.lscherry.utils.seperator.To Oxy')

        Face_Ramp_Builder__Group__Vector_Math_002 = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Group__Vector_Math_002.location = (275.03, 231.08)
        Face_Ramp_Builder__Group__Vector_Math_002.hide = True
        Face_Ramp_Builder__Group__Vector_Math_002.operation = 'NORMALIZE'
        Face_Ramp_Builder__Group__Vector_Math_002.inputs[1].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Group__Vector_Math_002.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Group__Vector_Math_002.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Group__Vector_Math_001 = nt.nodes.new('ShaderNodeVectorMath')
        Face_Ramp_Builder__Group__Vector_Math_001.location = (278.46, -3.05)
        Face_Ramp_Builder__Group__Vector_Math_001.hide = True
        Face_Ramp_Builder__Group__Vector_Math_001.operation = 'NORMALIZE'
        Face_Ramp_Builder__Group__Vector_Math_001.inputs[1].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Group__Vector_Math_001.inputs[2].default_value = (0.0, 0.0, 0.0)
        Face_Ramp_Builder__Group__Vector_Math_001.inputs[3].default_value = 1.0

        Face_Ramp_Builder__Group__Attribute_001 = nt.nodes.new('ShaderNodeAttribute')
        Face_Ramp_Builder__Group__Attribute_001.location = (275.03, 382.69)
        Face_Ramp_Builder__Group__Attribute_001.attribute_type = 'GEOMETRY'
        Face_Ramp_Builder__Group__Attribute_001.attribute_name = 'fx'

        Face_Ramp_Builder__Group__Attribute = nt.nodes.new('ShaderNodeAttribute')
        Face_Ramp_Builder__Group__Attribute.location = (278.46, 153.46)
        Face_Ramp_Builder__Group__Attribute.attribute_type = 'GEOMETRY'
        Face_Ramp_Builder__Group__Attribute.attribute_name = 'fy'

        Face_Ramp_Builder__Group__Combine_XYZ_002 = nt.nodes.new('ShaderNodeCombineXYZ')
        Face_Ramp_Builder__Group__Combine_XYZ_002.location = (275.65, -242.83)
        Face_Ramp_Builder__Group__Combine_XYZ_002.inputs[0].default_value = 1.0
        Face_Ramp_Builder__Group__Combine_XYZ_002.inputs[1].default_value = 0.0
        Face_Ramp_Builder__Group__Combine_XYZ_002.inputs[2].default_value = 0.0

        Face_Ramp_Builder__Group__Combine_XYZ_003 = nt.nodes.new('ShaderNodeCombineXYZ')
        Face_Ramp_Builder__Group__Combine_XYZ_003.location = (275.65, -108.7)
        Face_Ramp_Builder__Group__Combine_XYZ_003.inputs[0].default_value = -1.0
        Face_Ramp_Builder__Group__Combine_XYZ_003.inputs[1].default_value = 0.0
        Face_Ramp_Builder__Group__Combine_XYZ_003.inputs[2].default_value = 0.0


        nt.links.new(Texture_Coordinate.outputs['UV'], Mapping.inputs['Vector'])
        nt.links.new(Mapping.outputs['Vector'], Image_Texture.inputs['Vector'])
        nt.links.new(Image_Texture_001.outputs['Color'], lscherry_utils_procedural_Build_Face_Ramp.inputs['Face Map'])
        nt.links.new(Image_Texture.outputs['Color'], Group_Output.inputs['Base Color'])
        nt.links.new(lscherry_utils_procedural_Build_Face_Ramp.outputs['Custom Ramp'], Group_Output.inputs['Custom Ramp'])
        nt.links.new(Face_Ramp_Builder__Map_Range.outputs['Result'], lscherry_utils_procedural_Build_Face_Ramp.inputs['Face Value'])
        nt.links.new(Face_Ramp_Builder__Mapping.outputs['Vector'], Image_Texture_001.inputs['Vector'])
        nt.links.new(Face_Ramp_Builder__Group_002.outputs['Oxy'], Face_Ramp_Builder__Vector_Math.inputs[0])
        nt.links.new(Face_Ramp_Builder__Vector_Math.outputs['Vector'], Face_Ramp_Builder__Vector_Math_004.inputs[0])
        nt.links.new(Mapping.outputs['Vector'], Face_Ramp_Builder__Mapping.inputs['Vector'])
        nt.links.new(Face_Ramp_Builder__Mix.outputs[1], Face_Ramp_Builder__Mapping.inputs['Scale'])
        nt.links.new(Face_Ramp_Builder__Math.outputs['Value'], Face_Ramp_Builder__Mix.inputs[0])
        nt.links.new(Face_Ramp_Builder__Combine_XYZ.outputs['Vector'], Face_Ramp_Builder__Mix.inputs[4])
        nt.links.new(Face_Ramp_Builder__Combine_XYZ_001.outputs['Vector'], Face_Ramp_Builder__Mix.inputs[5])
        nt.links.new(Face_Ramp_Builder__Group_001.outputs['Main Light Vector'], Face_Ramp_Builder__Group_002.inputs['Oxyz'])
        nt.links.new(Face_Ramp_Builder__Vector_Math_003.outputs['Value'], Face_Ramp_Builder__Map_Range.inputs['Value'])
        nt.links.new(Face_Ramp_Builder__Vector_Math.outputs['Vector'], Face_Ramp_Builder__Vector_Math_003.inputs[0])
        nt.links.new(Face_Ramp_Builder__Vector_Math_004.outputs['Value'], Face_Ramp_Builder__Math.inputs[0])
        nt.links.new(Face_Ramp_Builder__Attribute_002.outputs['Vector'], Face_Ramp_Builder__Group_001.inputs['Light Dir'])
        nt.links.new(Face_Ramp_Builder__Geometry.outputs['Normal'], Face_Ramp_Builder__Group_001.inputs['Normal'])
        nt.links.new(Face_Ramp_Builder__Map_Range.outputs['Result'], Face_Ramp_Builder__Math_003.inputs[0])
        nt.links.new(Face_Ramp_Builder__Group__Vector_Math_002.outputs['Vector'], Face_Ramp_Builder__Vector_Math_004.inputs[1])
        nt.links.new(Face_Ramp_Builder__Group__Vector_Math_001.outputs['Vector'], Face_Ramp_Builder__Vector_Math_003.inputs[1])
        nt.links.new(Face_Ramp_Builder__Group__Attribute_001.outputs['Vector'], Face_Ramp_Builder__Group__Group_004.inputs['Oxyz'])
        nt.links.new(Face_Ramp_Builder__Group__Attribute.outputs['Vector'], Face_Ramp_Builder__Group__Group_003.inputs['Oxyz'])
        nt.links.new(Face_Ramp_Builder__Group__Group_004.outputs['Oxy'], Face_Ramp_Builder__Group__Vector_Math_002.inputs[0])
        nt.links.new(Face_Ramp_Builder__Group__Group_003.outputs['Oxy'], Face_Ramp_Builder__Group__Vector_Math_001.inputs[0])
        self.valuesUpdate(None)

    def valuesUpdate(self, context):
        if context is not None and self.node_tree.users > 1:
            self.node_tree = self.node_tree.copy()
        _placeholder_images = ('Image Texture', 'Image Texture.001')
        for node in self.node_tree.nodes:
            if node.type == "TEX_IMAGE" and node.name in _placeholder_images:
                node.image = self.image_texture
